import type { NormalizedSiteProject, SiteSection } from "./types";

type SiteBlueprintInput = {
  businessName: string;
  niche: string;
  city: string;
  goal: string;
  offer?: string;
  targetAudience?: string;
  tier?: string;
  style?: string;
};

type SiteBlueprint = {
  key: string;
  match: RegExp;
  primaryCTA: string;
  mainPromise: (input: SiteBlueprintInput) => string;
  marketingAngle: (input: SiteBlueprintInput) => string;
  tagline: (input: SiteBlueprintInput) => string;
  valueProposition: (input: SiteBlueprintInput) => string;
  pricingSuggestion: string;
  leadCapture: string;
  trustElements: string[];
  objections: string[];
  recommendedSections: string[];
  layoutDirection: string;
  visualMood: string;
  components: string[];
  sections: (input: SiteBlueprintInput) => SiteSection[];
};

const normalize = (value: string) =>
  value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

const section = (
  id: string,
  type: string,
  title: string,
  subtitle: string,
  content: string,
  ctaLabel: string,
  items: string[],
  layout: string,
  conversionRole: string,
): SiteSection => ({
  id,
  type,
  title,
  subtitle,
  content,
  cta: { label: ctaLabel, action: type === "contact" || type === "cta" ? "#contact" : `#${id}` },
  items,
  media: [],
  layout,
  conversionRole,
});

const cityText = (city: string) => (city && normalize(city) !== "france" ? ` a ${city}` : "");

const ctaForGoal = (goal: string, fallback: string) => {
  const normalized = normalize(goal);
  if (/(reservation|reserver|rendez-vous|rdv|booking)/.test(normalized)) return "Reserver un rendez-vous";
  if (/(devis|lead|demande|contact)/.test(normalized)) return "Demander un devis";
  if (/(vendre|vente|achat|acheter|checkout|commande)/.test(normalized)) return "Acheter maintenant";
  if (/(appel|audit|diagnostic)/.test(normalized)) return "Planifier un audit";
  return fallback;
};

const blueprints: SiteBlueprint[] = [
  {
    key: "restaurant",
    match: /(restaurant|bistrot|brasserie|food|cuisine|menu|reservation|pizzeria|sushi|bar a vin)/,
    primaryCTA: "Reserver une table",
    mainPromise: ({ businessName, city }) => `${businessName} donne envie de reserver avant meme d'arriver${cityText(city)}.`,
    marketingAngle: ({ niche, city }) => `Experience ${niche} locale avec menu lisible, ambiance visible et reservation rapide${cityText(city)}.`,
    tagline: () => "Une table, une ambiance, une raison claire de reserver.",
    valueProposition: () => "Menu signature, preuves sociales, horaires et reservation sans friction.",
    pricingSuggestion: "Afficher menus, formules ou fourchettes pour qualifier les reservations.",
    leadCapture: "Bouton reservation, appel direct et carte d'acces.",
    trustElements: ["Avis clients", "Photos du lieu", "Menu visible", "Horaires", "Adresse"],
    objections: ["Est-ce ouvert aujourd'hui ?", "Le menu me correspond-il ?", "Puis-je reserver vite ?"],
    recommendedSections: ["Hero reservation", "Specialites", "Menu", "Avis", "Localisation"],
    layoutDirection: "hero immersif, menu en colonnes, preuves et carte proches du CTA",
    visualMood: "chaleureux, sensoriel, premium local",
    components: ["RestaurantHero", "MenuShowcase", "ReviewStrip", "LocationCard", "ReservationCTA"],
    sections: (input) => [
      section(
        "reservation-hero",
        "hero",
        `${input.businessName}, l'adresse ${input.niche} a reserver${cityText(input.city)}`,
        "Le visiteur comprend tout de suite le style, le moment ideal et l'action a faire.",
        input.offer || "Cuisine signature, service soigne et reservation simple en quelques secondes.",
        "Reserver une table",
        ["Menu visible", "Reservation rapide", `Adresse ${input.city}`],
        "immersive-restaurant-hero",
        "declencher l'envie et la reservation",
      ),
      section(
        "signature-menu",
        "menu",
        "Les signatures qui donnent une raison de venir",
        "Mettre en avant les plats, formules ou experiences qui differencient le restaurant.",
        "Chaque entree de menu doit raconter un benefice clair : gout, moment, produit ou experience.",
        "Voir le menu",
        ["Plat signature", "Formule midi", "Suggestion du chef"],
        "menu-editorial-columns",
        "rendre l'offre concrete",
      ),
      section(
        "ambiance-gallery",
        "gallery",
        "Une ambiance que l'on visualise avant de reserver",
        "La galerie rassure sur le lieu, le dressage et le niveau de gamme.",
        "Photos du lieu, de l'assiette et des moments clients remplacent les textes generiques.",
        "Voir l'ambiance",
        ["Salle", "Terrasse", "Assiettes", "Equipe"],
        "masonry-gallery-proof",
        "rassurer par le visuel",
      ),
      section(
        "reviews-reservation",
        "proof",
        "Ce que les clients retiennent",
        "Les avis doivent lever les doutes sur l'accueil, la qualite et le rapport experience/prix.",
        "Une selection courte d'avis vaut mieux qu'un bloc generique sans preuve.",
        "Reserver maintenant",
        ["Accueil", "Saveurs", "Service", "Moment"],
        "review-reservation-split",
        "convertir les hesitants",
      ),
      section(
        "location-hours",
        "contact",
        "Adresse, horaires et reservation",
        "Le dernier bloc doit rendre l'action impossible a manquer.",
        "Adresse, horaires, telephone, parking ou acces transport doivent etre visibles sans chercher.",
        "Reserver une table",
        [`${input.city}`, "Horaires", "Acces", "Telephone"],
        "map-hours-cta",
        "faciliter le passage a l'action",
      ),
    ],
  },
  {
    key: "coach",
    match: /(coach|coaching|sport|fitness|therapeute|consultant|formation|mentor|transformation)/,
    primaryCTA: "Planifier un bilan",
    mainPromise: ({ businessName }) => `${businessName} transforme un objectif flou en plan d'action suivi et mesurable.`,
    marketingAngle: ({ niche }) => `Positionnement ${niche} axe sur transformation, methode et preuves avant/apres.`,
    tagline: () => "Un plan clair, un suivi humain, des progres visibles.",
    valueProposition: () => "Diagnostic, methode, accompagnement et preuve de progression.",
    pricingSuggestion: "Proposer un bilan ou une offre de demarrage pour reduire la friction.",
    leadCapture: "Formulaire court de bilan, calendrier ou appel decouverte.",
    trustElements: ["Methode", "Avant/apres", "Temoignages", "Suivi", "Cadre"],
    objections: ["Est-ce adapte a mon niveau ?", "Vais-je tenir dans le temps ?", "Quel resultat attendre ?"],
    recommendedSections: ["Hero transformation", "Probleme", "Methode", "Preuves", "Bilan"],
    layoutDirection: "narratif transformation, avant/apres, etapes guidees, CTA bilan repetes",
    visualMood: "motivant, premium, humain, cadre",
    components: ["TransformationHero", "MethodTimeline", "ProofBeforeAfter", "OfferCard", "BookingCTA"],
    sections: (input) => [
      section(
        "transformation-hero",
        "hero",
        `${input.businessName} t'aide a atteindre un objectif clair sans t'eparpiller`,
        `Un accompagnement ${input.niche} pense pour ${input.targetAudience || "des personnes motivees"}.`,
        input.offer || "Bilan, plan personnalise et suivi pour transformer l'intention en progression visible.",
        "Planifier un bilan",
        ["Bilan initial", "Plan personnalise", "Suivi regulier"],
        "before-after-hero",
        "faire ressentir la transformation",
      ),
      section(
        "problem-method",
        "method",
        "Le probleme n'est pas la motivation, c'est le manque de cadre",
        "La methode explique pourquoi l'utilisateur n'a pas encore atteint son objectif.",
        "Identifier le blocage, choisir peu d'actions, mesurer les progres et ajuster chaque semaine.",
        "Voir la methode",
        ["Diagnostic", "Priorites", "Mesure", "Ajustement"],
        "problem-to-method-ladder",
        "creer la confiance dans le process",
      ),
      section(
        "programmes",
        "offers",
        "Des parcours selon le niveau et le rythme",
        "Les offres doivent etre lisibles sans noyer l'utilisateur sous les options.",
        "Un parcours court pour demarrer, un suivi complet pour progresser, un format intensif pour accelerer.",
        "Choisir mon parcours",
        ["Starter", "Suivi", "Intensif"],
        "tiered-program-cards",
        "clarifier l'achat",
      ),
      section(
        "proof-transformations",
        "proof",
        "Des progres visibles, pas des promesses vagues",
        "Les preuves doivent montrer le changement : energie, routine, performance ou confiance.",
        "Avant/apres, retours clients et chiffres de progression rendent l'offre credible.",
        "Voir les resultats",
        ["Avant/apres", "Retours", "Progression", "Habitudes"],
        "proof-timeline",
        "lever l'objection resultat",
      ),
      section(
        "booking-faq",
        "cta",
        "Commencer par un bilan simple",
        "Le dernier bloc repond aux doutes avant la prise de rendez-vous.",
        "Explique la duree, le prix de depart, le niveau requis et la prochaine etape.",
        "Planifier un bilan",
        ["Duree", "Niveau", "Prix de depart", "Prochaine etape"],
        "faq-booking-panel",
        "capturer le rendez-vous",
      ),
    ],
  },
  {
    key: "car-rental",
    match: /(location.*voiture|voiture|auto|vehicule|flotte|chauffeur|vsl|garage|rental|car)/,
    primaryCTA: "Verifier les disponibilites",
    mainPromise: ({ businessName, city }) => `${businessName} rend la location de vehicule plus claire, plus rapide et plus rassurante${cityText(city)}.`,
    marketingAngle: ({ city }) => `Flotte, conditions, disponibilites et garanties visibles pour convertir les demandes${cityText(city)}.`,
    tagline: () => "Choisir, reserver, partir avec une information claire.",
    valueProposition: () => "Categories de vehicules, conditions transparentes et demande de reservation rapide.",
    pricingSuggestion: "Afficher prix a partir de, cautions, kilometrage et options pour filtrer les demandes.",
    leadCapture: "Formulaire de disponibilite avec dates, categorie et lieu de retrait.",
    trustElements: ["Flotte", "Assurance", "Conditions", "Avis", "Retrait"],
    objections: ["Quel vehicule est disponible ?", "Quelles conditions ?", "Y a-t-il des frais caches ?"],
    recommendedSections: ["Hero disponibilite", "Flotte", "Process reservation", "Conditions", "Contact"],
    layoutDirection: "comparateur de flotte, bandeau disponibilite, conditions en blocs courts",
    visualMood: "premium, fiable, mobile-first, reservation",
    components: ["FleetHero", "VehicleCategoryGrid", "BookingSteps", "ConditionsPanel", "AvailabilityCTA"],
    sections: (input) => [
      section(
        "fleet-hero",
        "hero",
        `${input.businessName}, location de vehicules sans surprise${cityText(input.city)}`,
        "Le visiteur voit rapidement la flotte, les conditions et le bouton de disponibilite.",
        input.offer || "Des vehicules propres, des conditions lisibles et une reservation guidee.",
        "Verifier les disponibilites",
        ["Citadines", "SUV", "Utilitaires", "Options"],
        "fleet-availability-hero",
        "capturer une demande datee",
      ),
      section(
        "vehicle-categories",
        "fleet",
        "Choisir le bon vehicule selon le besoin",
        "La flotte doit etre presentee par usage, pas seulement par modele.",
        "Ville, famille, deplacement pro ou utilitaire : chaque categorie explique le bon cas d'usage.",
        "Comparer la flotte",
        ["Ville", "Famille", "Pro", "Utilitaire"],
        "vehicle-category-ribbon",
        "aider au choix",
      ),
      section(
        "reservation-flow",
        "process",
        "Reservation en trois etapes",
        "Un process clair reduit les appels inutiles et les abandons.",
        "Dates, categorie, confirmation : chaque etape doit etre simple et visible.",
        "Demarrer ma demande",
        ["Dates", "Categorie", "Confirmation"],
        "booking-steps-horizontal",
        "reduire la friction",
      ),
      section(
        "conditions-trust",
        "trust",
        "Conditions, assurance et garanties",
        "Les conditions doivent etre visibles avant le formulaire.",
        "Caution, kilometrage, assurance, pieces demandees et options doivent etre expliquees simplement.",
        "Voir les conditions",
        ["Caution", "Assurance", "Kilometrage", "Pieces"],
        "conditions-comparison-panel",
        "lever les objections",
      ),
      section(
        "pickup-contact",
        "contact",
        "Disponibilite et lieu de retrait",
        "Le bloc final concentre dates, contact, adresse et urgence.",
        "Le visiteur peut demander une disponibilite sans chercher l'information de contact.",
        "Verifier les disponibilites",
        [`Retrait ${input.city}`, "Contact rapide", "Horaires", "Options"],
        "availability-contact-card",
        "convertir en demande",
      ),
    ],
  },
  {
    key: "local-service",
    match: /(artisan|plombier|electricien|serrurier|nettoyage|depannage|devis|service local|climatisation|peintre|renovation|chauffage|jardinier)/,
    primaryCTA: "Demander un devis rapide",
    mainPromise: ({ businessName, city }) => `${businessName} transforme une urgence ou un besoin local en demande claire${cityText(city)}.`,
    marketingAngle: ({ niche, city }) => `Parcours ${niche} pense pour rassurer vite: probleme, solution, zones, delais, preuves et devis${cityText(city)}.`,
    tagline: () => "Un service local compris vite, joignable vite, prouve clairement.",
    valueProposition: () => "Diagnostic clair, zones desservies, delais visibles et devis sans friction.",
    pricingSuggestion: "Afficher un prix d'appel, une fourchette ou les criteres qui font varier le devis.",
    leadCapture: "Formulaire devis court, telephone visible et demande urgente separee.",
    trustElements: ["Zones", "Delais", "Avis", "Garanties", "Assurance"],
    objections: ["Intervenez-vous chez moi ?", "Combien de temps attendre ?", "Le devis sera-t-il clair ?"],
    recommendedSections: ["Hero devis", "Problemes", "Services", "Zones", "Process", "Contact urgent"],
    layoutDirection: "mobile-first, telephone visible, zones desservies, preuve locale et process court",
    visualMood: "rassurant, direct, local, professionnel",
    components: ["LocalServiceHero", "ProblemSolutionGrid", "ServiceZoneMap", "EmergencyCTA", "QuoteSteps"],
    sections: (input) => [
      section(
        "local-quote-hero",
        "hero",
        `${input.businessName}, intervention ${input.niche} claire et rapide${cityText(input.city)}`,
        "Le visiteur doit savoir en quelques secondes si le service couvre son besoin et sa zone.",
        input.offer || "Devis rapide, zones desservies visibles et prochaines etapes simples.",
        "Demander un devis rapide",
        ["Devis clair", `Zone ${input.city}`, "Delai indique", "Contact direct"],
        "local-service-urgent-hero",
        "transformer le besoin en demande qualifiee",
      ),
      section(
        "problems-solved",
        "problem-solution",
        "Les situations prises en charge",
        "Un service local convertit mieux quand il nomme les vrais problemes client.",
        "Lister les cas concrets aide le visiteur a se reconnaitre et evite les demandes hors sujet.",
        "Identifier mon besoin",
        ["Urgence", "Installation", "Entretien", "Diagnostic"],
        "problem-solution-grid",
        "creer l'identification",
      ),
      section(
        "services-zones",
        "services",
        "Services et zones desservies",
        "La zone d'intervention doit etre aussi visible que l'offre.",
        "Chaque service relie un probleme, une zone et une prochaine action.",
        "Voir les zones",
        ["Centre-ville", "Peripherie", "Intervention pro", "Intervention particulier"],
        "service-zone-map",
        "qualifier la demande",
      ),
      section(
        "quote-process",
        "process",
        "Comment se passe le devis",
        "Le process rassure sur les delais, le prix et la preparation.",
        "Demande, verification, estimation, intervention: quatre etapes courtes et lisibles.",
        "Comprendre le devis",
        ["Demande", "Verification", "Estimation", "Intervention"],
        "quote-steps",
        "reduire la friction",
      ),
      section(
        "local-proof-contact",
        "contact",
        "Demande rapide avec preuves locales",
        "Le dernier bloc doit combiner avis, garanties, telephone et formulaire.",
        "Le visiteur ne doit pas choisir entre appeler et envoyer un devis: les deux options sont visibles.",
        "Demander un devis rapide",
        ["Avis locaux", "Garantie", "Telephone", "Formulaire"],
        "proof-contact-split",
        "capturer le lead local",
      ),
    ],
  },
  {
    key: "ecommerce",
    match: /(e-commerce|ecommerce|boutique|produit|produits|acheter|vente|shop|store|catalogue)/,
    primaryCTA: "Acheter maintenant",
    mainPromise: ({ businessName }) => `${businessName} transforme l'interet produit en achat rassure.`,
    marketingAngle: () => "Benefices, preuve, garanties et FAQ rapproches du CTA pour augmenter la conversion.",
    tagline: () => "Un produit compris vite, desire vite, achete sans hesitation.",
    valueProposition: () => "Benefices concrets, avis, garanties, livraison et objections traitees.",
    pricingSuggestion: "Mettre prix, garanties, livraison et retour pres du CTA.",
    leadCapture: "CTA achat, email de rappel panier ou offre de lancement.",
    trustElements: ["Avis", "Garantie", "Livraison", "Retour", "Paiement securise"],
    objections: ["Est-ce fiable ?", "Est-ce livre vite ?", "Puis-je retourner le produit ?"],
    recommendedSections: ["Hero produit", "Benefices", "Produits", "Garanties", "FAQ achat"],
    layoutDirection: "page produit orientee decision avec benefices et garanties toujours proches",
    visualMood: "desirable, clair, marchand, premium",
    components: ["ProductHero", "BenefitGrid", "ProductCards", "GuaranteeStrip", "CheckoutCTA"],
    sections: (input) => [
      section(
        "product-hero",
        "hero",
        `${input.businessName}, le produit ${input.niche} presente pour vendre clairement`,
        "Le hero doit montrer le benefice principal, le prix ou l'offre et une raison d'acheter maintenant.",
        input.offer || "Un produit premium, explique simplement, avec garanties et avis visibles.",
        "Acheter maintenant",
        ["Benefice clair", "Garantie", "Livraison", "Avis"],
        "product-decision-hero",
        "declencher l'intention d'achat",
      ),
      section(
        "benefits-stack",
        "benefits",
        "Pourquoi ce produit change vraiment l'usage",
        "Les benefices doivent remplacer les descriptions vagues.",
        "Chaque bloc relie une caracteristique a un gain concret pour l'acheteur.",
        "Voir les benefices",
        ["Gain de temps", "Confort", "Durabilite", "Style"],
        "benefit-proof-stack",
        "creer le desir",
      ),
      section(
        "product-selection",
        "products",
        "Choisir la version adaptee",
        "Les variantes doivent aider a acheter, pas compliquer.",
        "Afficher les differences, les usages et la meilleure option recommandee.",
        "Comparer les options",
        ["Essentiel", "Premium", "Pack"],
        "commerce-comparison-cards",
        "clarifier le panier",
      ),
      section(
        "guarantees",
        "trust",
        "Garanties visibles avant le checkout",
        "Les garanties reduisent les abandons au moment critique.",
        "Retour, livraison, paiement et support doivent etre visibles dans une bande rassurante.",
        "Voir les garanties",
        ["Retour", "Livraison", "Paiement", "Support"],
        "guarantee-strip",
        "rassurer avant achat",
      ),
      section(
        "checkout-faq",
        "cta",
        "Acheter avec les bonnes reponses sous les yeux",
        "La FAQ traite les doutes juste avant le CTA final.",
        "Disponibilite, livraison, entretien et retours doivent etre repondus sans quitter la page.",
        "Acheter maintenant",
        ["Disponibilite", "Livraison", "Retour", "Entretien"],
        "checkout-faq-panel",
        "finaliser l'achat",
      ),
    ],
  },
  {
    key: "barber-salon",
    match: /(barber|barbershop|coiffeur|coiffure|salon|beaute|ongles|esthetique|spa)/,
    primaryCTA: "Reserver un creneau",
    mainPromise: ({ businessName, city }) => `${businessName} rend le style, les tarifs et la reservation evidents${cityText(city)}.`,
    marketingAngle: () => "Prestations, prix, galerie, avis et disponibilites visibles pour convertir sur mobile.",
    tagline: () => "Voir le style, choisir la prestation, reserver vite.",
    valueProposition: () => "Prestations lisibles, galerie, avis et reservation rapide.",
    pricingSuggestion: "Afficher les prix par prestation pour eviter les demandes mal qualifiees.",
    leadCapture: "Bouton reservation, telephone et horaires.",
    trustElements: ["Galerie", "Tarifs", "Avis", "Hygiene", "Horaires"],
    objections: ["Quel style puis-je obtenir ?", "Combien ca coute ?", "Quand est-ce disponible ?"],
    recommendedSections: ["Hero style", "Prestations", "Galerie", "Avis", "Reservation"],
    layoutDirection: "mobile-first, galerie forte, tarifs en cartes, CTA reservation sticky",
    visualMood: "stylise, local, premium accessible",
    components: ["StyleHero", "PriceCards", "GalleryGrid", "ReviewStrip", "BookingCTA"],
    sections: (input) => [
      section(
        "style-hero",
        "hero",
        `${input.businessName}, le style ${input.niche} que l'on reserve vite${cityText(input.city)}`,
        "La premiere section doit montrer le style, le niveau et le CTA reservation.",
        input.offer || "Prestations claires, tarifs visibles, galerie et creneaux faciles a demander.",
        "Reserver un creneau",
        ["Tarifs visibles", "Galerie", "Reservation", input.city],
        "salon-style-hero",
        "declencher la reservation mobile",
      ),
      section(
        "prices-services",
        "pricing",
        "Prestations et tarifs sans surprise",
        "Les tarifs rendent la decision plus rapide et filtrent les demandes.",
        "Coupe, soin, barbe, couleur ou prestation signature doivent etre compares clairement.",
        "Voir les tarifs",
        ["Coupe", "Soin", "Signature", "Pack"],
        "price-menu-cards",
        "clarifier la valeur",
      ),
      section(
        "visual-proof",
        "gallery",
        "Des resultats que l'on peut projeter sur soi",
        "La galerie doit montrer des styles reels et variés.",
        "Avant/apres, details et ambiances remplacent les promesses generiques.",
        "Voir la galerie",
        ["Avant/apres", "Details", "Ambiance", "Equipe"],
        "style-gallery-grid",
        "rassurer visuellement",
      ),
      section(
        "reviews-local",
        "proof",
        "Pourquoi les clients reviennent",
        "Les avis doivent parler de ponctualite, resultat et accueil.",
        "Une preuve locale vaut mieux qu'un long discours.",
        "Lire les avis",
        ["Ponctualite", "Resultat", "Accueil", "Conseil"],
        "local-review-strip",
        "creer confiance",
      ),
      section(
        "booking-location",
        "contact",
        "Reservation, horaires et acces",
        "Tout doit etre clair pour reserver depuis un telephone.",
        "Horaires, adresse, telephone et lien reservation doivent etre visibles en un bloc.",
        "Reserver un creneau",
        [`${input.city}`, "Horaires", "Telephone", "Acces"],
        "booking-location-panel",
        "capturer le rendez-vous",
      ),
    ],
  },
  {
    key: "agency",
    match: /(agence|studio|saas|startup|marketing|design|developpement|web|digital|communication)/,
    primaryCTA: "Demander un audit",
    mainPromise: ({ businessName }) => `${businessName} transforme une idee business en plan digital clair et priorise.`,
    marketingAngle: () => "Positionnement expert avec methode, cas, offres et CTA audit.",
    tagline: () => "Strategie, execution, preuves : moins de flou, plus d'impact.",
    valueProposition: () => "Diagnostic, plan d'action, execution et optimisation conversion.",
    pricingSuggestion: "Presenter des packs ou un audit d'entree pour qualifier les prospects.",
    leadCapture: "Audit, appel strategie ou formulaire projet.",
    trustElements: ["Methode", "Cas clients", "Stack", "Process", "Resultats"],
    objections: ["Est-ce adapte a mon business ?", "Quel budget ?", "Quel delai ?"],
    recommendedSections: ["Hero expertise", "Services", "Methode", "Cas", "Audit"],
    layoutDirection: "dashboard premium, preuves business, process visible, CTA audit",
    visualMood: "expert, net, startup premium",
    components: ["AgencyHero", "ServicePillars", "SprintTimeline", "CaseCards", "AuditCTA"],
    sections: (input) => [
      section(
        "growth-hero",
        "hero",
        `${input.businessName} structure ton projet digital pour le rendre plus credible et vendable`,
        "Le hero doit vendre une direction claire, pas une liste de services.",
        input.offer || "Audit, strategie, design et execution pour lancer une base digitale solide.",
        "Demander un audit",
        ["Strategie", "Design", "Execution", "Optimisation"],
        "agency-dashboard-hero",
        "positionner l'expertise",
      ),
      section(
        "service-pillars",
        "services",
        "Trois leviers pour passer de l'idee au projet concret",
        "Les services sont regroupes par resultat business.",
        "Clarifier l'offre, construire l'experience, mesurer ce qui convertit.",
        "Voir les leviers",
        ["Clarifier", "Construire", "Optimiser"],
        "pillar-cards-with-metrics",
        "rendre l'offre lisible",
      ),
      section(
        "sprint-method",
        "process",
        "Une methode courte pour eviter les projets interminables",
        "Le process doit rassurer sur les etapes, les decisions et les livrables.",
        "Brief, plan, prototype, validation et amelioration continue.",
        "Comprendre la methode",
        ["Brief", "Prototype", "Validation", "Iteration"],
        "sprint-timeline",
        "reduire la peur du projet",
      ),
      section(
        "business-proof",
        "proof",
        "Des preuves orientees business",
        "Les cas doivent montrer probleme, action, resultat et prochain levier.",
        "Afficher quelques cas concrets est plus fort qu'un mur de logos.",
        "Voir les cas",
        ["Probleme", "Action", "Resultat", "Levier"],
        "case-study-cards",
        "prouver la competence",
      ),
      section(
        "audit-cta",
        "cta",
        "Savoir quoi ameliorer en premier",
        "L'audit transforme un prospect flou en demande claire.",
        "Le CTA final promet une prochaine etape simple, pas un engagement lourd.",
        "Demander un audit",
        ["Priorites", "Budget", "Delai", "Plan"],
        "audit-request-panel",
        "capturer un lead qualifie",
      ),
    ],
  },
  {
    key: "default",
    match: /.*/,
    primaryCTA: "Demander un diagnostic",
    mainPromise: ({ businessName, niche }) => `${businessName} clarifie l'offre ${niche} et la transforme en parcours de conversion.`,
    marketingAngle: ({ niche, city }) => `Structure ${niche} adaptee au contexte client, aux objections et a la conversion${cityText(city)}.`,
    tagline: () => "Une offre comprise vite, prouvee clairement, contactee facilement.",
    valueProposition: () => "Promesse specifique, parcours de decision, preuves et prochaine action.",
    pricingSuggestion: "Afficher un point d'entree ou une fourchette pour qualifier les demandes.",
    leadCapture: "Diagnostic, devis, appel ou formulaire court selon l'objectif.",
    trustElements: ["Methode", "Preuves", "FAQ", "Process", "Contact"],
    objections: ["Pourquoi vous ?", "Quel resultat ?", "Combien ca coute ?"],
    recommendedSections: ["Hero specifique", "Carte offre", "Process", "Preuves", "CTA"],
    layoutDirection: "parcours de decision, sections courtes, preuves proches des CTA",
    visualMood: "premium, clair, business-first",
    components: ["SpecificHero", "OfferMap", "DecisionProof", "ProcessSteps", "ConversionCTA"],
    sections: (input) => [
      section(
        "specific-hero",
        "hero",
        `${input.businessName} rend ton projet ${input.niche} clair, credible et actionnable`,
        `Une page concue pour ${input.targetAudience || "des clients exigeants"}${cityText(input.city)}.`,
        input.offer || "Une offre expliquee simplement, des preuves visibles et une prochaine etape claire.",
        ctaForGoal(input.goal, "Demander un diagnostic"),
        [input.niche, input.city, input.goal],
        "specific-conversion-hero",
        "clarifier la promesse",
      ),
      section(
        "offer-map",
        "offer",
        "Ce que le client obtient vraiment",
        "L'offre doit etre presentee par resultats et non par phrases vagues.",
        "Chaque bloc relie le service a un benefice, une preuve ou une decision.",
        "Voir l'offre",
        ["Resultat", "Preuve", "Delai", "Etape"],
        "offer-map-grid",
        "rendre la valeur tangible",
      ),
      section(
        "decision-path",
        "process",
        "Le parcours simple avant de passer a l'action",
        "Un process lisible rend l'achat ou la prise de contact moins risquee.",
        "Comprendre, comparer, valider, contacter : le site guide chaque etape.",
        "Comprendre le process",
        ["Comprendre", "Comparer", "Valider", "Contacter"],
        "decision-path-timeline",
        "reduire la friction",
      ),
      section(
        "proof-stack",
        "proof",
        "Les preuves qui rendent la promesse credible",
        "La preuve doit etre choisie selon la niche : avis, resultats, methode, photos ou garanties.",
        "Un bloc preuve utile remplace les slogans interchangeables.",
        "Voir les preuves",
        ["Avis", "Methode", "Resultats", "Garanties"],
        "proof-stack-panel",
        "rassurer",
      ),
      section(
        "conversion-final",
        "cta",
        "Passer a la prochaine etape sans engagement lourd",
        "Le CTA final doit rappeler le benefice et la simplicite de l'action.",
        "Une demande claire permet de repondre vite, avec une recommandation adaptee.",
        ctaForGoal(input.goal, "Demander un diagnostic"),
        ["Reponse claire", "Priorite", "Sans engagement"],
        "final-decision-card",
        "capturer une demande qualifiee",
      ),
    ],
  },
];

export const resolveSiteBlueprint = (input: SiteBlueprintInput): SiteBlueprint => {
  const haystack = normalize(
    [input.businessName, input.niche, input.city, input.goal, input.offer, input.targetAudience, input.style]
      .filter(Boolean)
      .join(" "),
  );
  return blueprints.find((blueprint) => blueprint.match.test(haystack)) ?? blueprints[blueprints.length - 1];
};

export const createNicheSiteProjectParts = (input: SiteBlueprintInput) => {
  const blueprint = resolveSiteBlueprint(input);
  const cta = ctaForGoal(input.goal, blueprint.primaryCTA);
  const sections = blueprint.sections(input).map((item) => ({
    ...item,
    cta: { ...item.cta, label: item.type === "hero" || item.type === "cta" || item.type === "contact" ? cta : item.cta.label },
  }));

  return {
    blueprint,
    cta,
    sections,
    strategy: {
      mainPromise: blueprint.mainPromise(input),
      marketingAngle: blueprint.marketingAngle(input),
      trustStrategy: `${blueprint.trustElements.join(", ")} places pres des decisions importantes.`,
      objectionsToHandle: blueprint.objections,
    },
    brand: {
      tagline: blueprint.tagline(input),
      tone: `${blueprint.visualMood}, direct, concret`,
    },
    business: {
      valueProposition: blueprint.valueProposition(input),
      pricingSuggestion: blueprint.pricingSuggestion,
      leadCapture: blueprint.leadCapture,
      trustElements: blueprint.trustElements,
    },
    conversion: {
      ctaStrategy: `CTA principal "${cta}" dans le hero, rappel apres les preuves et CTA final contextualise.`,
      objections: blueprint.objections,
      proofElements: blueprint.trustElements,
      recommendedSections: blueprint.recommendedSections,
    },
    design: {
      layoutDirection: blueprint.layoutDirection,
      visualMood: blueprint.visualMood,
      components: blueprint.components,
    },
  };
};

export const genericSiteCopyPatterns = [
  /lorem/i,
  /placeholder/i,
  /todo/i,
  /debug/i,
  /votre entreprise/i,
  /nom de votre/i,
  /secteur d.?activite/i,
  /services? de qualite/i,
  /solutions? sur mesure/i,
  /solutions? adaptees?/i,
  /solutions? innovantes?/i,
  /nous accompagnons nos clients/i,
  /decouvrez nos services/i,
  /bienvenue sur notre site/i,
  /au service de vos besoins/i,
  /repondre a vos besoins/i,
  /votre partenaire de confiance/i,
  /expertise a votre service/i,
  /qualite et professionnalisme/i,
  /accompagnement personnalise/i,
  /des services adaptes a vos besoins/i,
];
