import type { AIProviderId, AITaskType } from "../schemas/ai-task.schema";

export type AIProviderConfig = {
  providerId: AIProviderId;
  providerName: string;
  displayName: string;
  role: string;
  defaultModel: string;
  status: "configured" | "missing" | "invalid" | "mock" | "disabled";
  serverOnly: boolean;
  supportedTasks: AITaskType[];
};

export const vercelGatewayModelStack = {
  fast: "mistral/mistral-small",
  cheapLongContext: "mistral/ministral-8b",
  balanced: "openai/gpt-4o-mini",
  generalValue: "meta/llama-3.3-70b",
  reasoning: "anthropic/claude-3.5-haiku",
  designValue: "mistral/pixtral-12b",
  designPremium: "mistral/pixtral-large",
  codeValue: "mistral/codestral",
  safety: "openai/gpt-oss-safeguard-20b",
  wow: "openai/gpt-4o",
  premiumDeepWork: "anthropic/claude-opus-4.5",
  deepResearch: "openai/o3-deep-research",
  embedding: "openai/text-embedding-3-small",
  fallback: [
    "openai/gpt-4o-mini",
    "mistral/mistral-small",
    "meta/llama-3.3-70b",
    "anthropic/claude-3.5-haiku",
  ],
} as const;

const allGeneralTasks: AITaskType[] = [
  "project_type_detection",
  "brief_analysis",
  "integration_mapping",
  "dashboard_recommendations",
  "output_normalization",
  "final_fusion",
];

export const aiProvidersConfig: Record<AIProviderId, AIProviderConfig> = {
  "vercel-gateway": {
    providerId: "vercel-gateway",
    providerName: "Moteur IA Pixelrises",
    displayName: "Pixelrises Gateway",
    role: "Provider unifie server-only pour router les meilleurs modeles qualite/prix via AI Gateway avec fallback et suivi des couts.",
    defaultModel: vercelGatewayModelStack.balanced,
    status: "missing",
    serverOnly: true,
    supportedTasks: [
      "project_type_detection",
      "brief_analysis",
      "strategy_analysis",
      "business_positioning",
      "offer_generation",
      "site_structure",
      "site_copywriting",
      "site_design",
      "site_seo",
      "site_conversion",
      "site_improvement",
      "design_system",
      "ui_layout",
      "component_suggestion",
      "agent_config",
      "agent_prompt",
      "agent_permissions",
      "game_design",
      "game_mechanics",
      "game_level_design",
      "game_script",
      "game_assets",
      "game_publishing",
      "integration_mapping",
      "dashboard_recommendations",
      "analytics_insights",
      "code_generation",
      "code_review",
      "bug_fix",
      "refactor",
      "quality_gate",
      "output_normalization",
      "final_fusion",
    ],
  },
  gemini: {
    providerId: "gemini",
    providerName: "Gemini",
    displayName: "Pixelrises AI General",
    role: "Moteur general, detection, normalisation, suggestions et fallback principal.",
    defaultModel: "gemini-backend",
    status: "mock",
    serverOnly: true,
    supportedTasks: allGeneralTasks,
  },
  openai: {
    providerId: "openai",
    providerName: "OpenAI",
    displayName: "Pixelrises Strategy",
    role: "Strategie business, copywriting, SEO, conversion, offres et recommandations marketing.",
    defaultModel: "openai-backend",
    status: "missing",
    serverOnly: true,
    supportedTasks: [
      "strategy_analysis",
      "business_positioning",
      "offer_generation",
      "site_copywriting",
      "site_seo",
      "site_conversion",
      "agent_prompt",
      "analytics_insights",
    ],
  },
  claude: {
    providerId: "claude",
    providerName: "Claude",
    displayName: "Pixelrises Logic",
    role: "Raisonnement profond, structure, planification, critique qualite et coherence globale.",
    defaultModel: "claude-backend",
    status: "missing",
    serverOnly: true,
    supportedTasks: [
      "site_structure",
      "site_improvement",
      "agent_config",
      "agent_permissions",
      "game_design",
      "game_mechanics",
      "game_publishing",
      "quality_gate",
    ],
  },
  "cloud-design": {
    providerId: "cloud-design",
    providerName: "Design Vision",
    displayName: "Pixelrises Design",
    role: "Direction artistique, design system, UI/UX, layout, spacing et coherence visuelle via le meilleur modele design qualite/prix.",
    defaultModel: "design-backend",
    status: "missing",
    serverOnly: true,
    supportedTasks: ["site_design", "design_system", "ui_layout", "component_suggestion", "game_level_design", "game_assets"],
  },
  "cloud-code": {
    providerId: "cloud-code",
    providerName: "Code Studio",
    displayName: "Pixelrises Code",
    role: "Architecture technique, code, debug, refactor, tests, securite et scripts game builder via un modele code rentable.",
    defaultModel: "code-backend",
    status: "missing",
    serverOnly: true,
    supportedTasks: ["game_script", "code_generation", "code_review", "bug_fix", "refactor"],
  },
  mistral: {
    providerId: "mistral",
    providerName: "Mistral",
    displayName: "Pixelrises Fast",
    role: "Classification, resume, extraction, tags, pre-routing et fallback economique.",
    defaultModel: "mistral-backend",
    status: "missing",
    serverOnly: true,
    supportedTasks: ["project_type_detection", "brief_analysis", "dashboard_recommendations"],
  },
  mock: {
    providerId: "mock",
    providerName: "Mock Provider",
    displayName: "Pixelrises Mock",
    role: "Developpement local, tests et fallback sans cle API.",
    defaultModel: "mock-v2",
    status: "mock",
    serverOnly: false,
    supportedTasks: [
      "project_type_detection",
      "brief_analysis",
      "strategy_analysis",
      "business_positioning",
      "offer_generation",
      "site_structure",
      "site_copywriting",
      "site_design",
      "site_seo",
      "site_conversion",
      "site_improvement",
      "design_system",
      "ui_layout",
      "component_suggestion",
      "agent_config",
      "agent_prompt",
      "agent_permissions",
      "game_design",
      "game_mechanics",
      "game_level_design",
      "game_script",
      "game_assets",
      "game_publishing",
      "integration_mapping",
      "dashboard_recommendations",
      "analytics_insights",
      "code_generation",
      "code_review",
      "bug_fix",
      "refactor",
      "quality_gate",
      "output_normalization",
      "final_fusion",
    ],
  },
  future: {
    providerId: "future",
    providerName: "Future Provider",
    displayName: "Future Provider",
    role: "Adapter reserve aux futurs providers IA.",
    defaultModel: "future-provider",
    status: "disabled",
    serverOnly: true,
    supportedTasks: [],
  },
};

export const getProviderConfig = (providerId: AIProviderId) => aiProvidersConfig[providerId] ?? aiProvidersConfig.mock;
