import type { AIExecutionMode, AIProviderId, AITaskType } from "../schemas/ai-task.schema";

export type AIRoutingRule = {
  taskType: AITaskType;
  provider: AIProviderId;
  fallbackProvider: AIProviderId;
  schema: string;
  reason: string;
};

export const globalFallbackChain: AIProviderId[] = ["gemini", "mistral", "mock"];

export const defaultRoutingRules: Record<AITaskType, AIRoutingRule> = {
  project_type_detection: {
    taskType: "project_type_detection",
    provider: "gemini",
    fallbackProvider: "mock",
    schema: "project-type-detection",
    reason: "Gemini sert de moteur general pour detecter rapidement le type de projet.",
  },
  brief_analysis: {
    taskType: "brief_analysis",
    provider: "gemini",
    fallbackProvider: "mock",
    schema: "brief-analysis",
    reason: "Gemini enrichit et normalise le brief initial.",
  },
  strategy_analysis: {
    taskType: "strategy_analysis",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "strategy-analysis",
    reason: "OpenAI est reserve a la strategie business, conversion et clarte commerciale.",
  },
  business_positioning: {
    taskType: "business_positioning",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "business-positioning",
    reason: "OpenAI optimise positionnement, promesse, objections et offre.",
  },
  offer_generation: {
    taskType: "offer_generation",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "offer-generation",
    reason: "OpenAI genere des offres claires et orientee conversion.",
  },
  site_structure: {
    taskType: "site_structure",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "site-structure",
    reason: "OpenAI gere la logique, la structure, la clarte commerciale et la coherence du site.",
  },
  site_copywriting: {
    taskType: "site_copywriting",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "site-copywriting",
    reason: "OpenAI gere les textes, CTA, SEO et objections commerciales.",
  },
  site_design: {
    taskType: "site_design",
    provider: "claude-design",
    fallbackProvider: "gemini",
    schema: "site-design",
    reason: "Claude Design gere direction artistique, UI, spacing et coherence visuelle.",
  },
  site_seo: {
    taskType: "site_seo",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "site-seo",
    reason: "OpenAI gere SEO, titres, descriptions et mots-cles.",
  },
  site_conversion: {
    taskType: "site_conversion",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "site-conversion",
    reason: "OpenAI optimise CTA, preuves, objections et tunnel de contact.",
  },
  site_improvement: {
    taskType: "site_improvement",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "site-improvement",
    reason: "OpenAI analyse les changements cibles sans regenerer tout le projet.",
  },
  design_system: {
    taskType: "design_system",
    provider: "claude-design",
    fallbackProvider: "gemini",
    schema: "design-system",
    reason: "Claude Design prepare tokens, composants, layout et hierarchie UI.",
  },
  ui_layout: {
    taskType: "ui_layout",
    provider: "claude-design",
    fallbackProvider: "gemini",
    schema: "ui-layout",
    reason: "Claude Design propose des interfaces premium adaptees au contexte.",
  },
  component_suggestion: {
    taskType: "component_suggestion",
    provider: "claude-design",
    fallbackProvider: "gemini",
    schema: "component-suggestion",
    reason: "Claude Design suggere composants, sections et patterns UI.",
  },
  agent_config: {
    taskType: "agent_config",
    provider: "claude",
    fallbackProvider: "gemini",
    schema: "agent-config",
    reason: "Claude structure role, contexte, limites et logique de l'agent.",
  },
  agent_prompt: {
    taskType: "agent_prompt",
    provider: "openai",
    fallbackProvider: "gemini",
    schema: "agent-prompt",
    reason: "OpenAI redige les instructions, ton et reponses attendues.",
  },
  agent_permissions: {
    taskType: "agent_permissions",
    provider: "claude",
    fallbackProvider: "mock",
    schema: "agent-permissions",
    reason: "Claude verifie les permissions et actions sensibles.",
  },
  game_design: {
    taskType: "game_design",
    provider: "claude",
    fallbackProvider: "gemini",
    schema: "game-design",
    reason: "Claude construit concept, contraintes, loop et coherence gameplay.",
  },
  game_research: {
    taskType: "game_research",
    provider: "gemini",
    fallbackProvider: "mock",
    schema: "game-research",
    reason: "Gemini prepare tendances, sources officielles et contraintes connues sans inventer de donnees live.",
  },
  game_mechanics: {
    taskType: "game_mechanics",
    provider: "claude",
    fallbackProvider: "gemini",
    schema: "game-mechanics",
    reason: "Claude detaille mecaniques, progression, economie et regles.",
  },
  game_level_design: {
    taskType: "game_level_design",
    provider: "claude-design",
    fallbackProvider: "gemini",
    schema: "game-level-design",
    reason: "Claude Design gere map structure, zones, flow et assets visuels.",
  },
  game_platform_constraints: {
    taskType: "game_platform_constraints",
    provider: "claude",
    fallbackProvider: "gemini",
    schema: "game-platform-constraints",
    reason: "Claude verifie ce qui est faisable sur Web, Roblox Studio, UEFN ou Minecraft.",
  },
  game_script: {
    taskType: "game_script",
    provider: "claude-code",
    fallbackProvider: "gemini",
    schema: "game-script",
    reason: "Claude Code prepare snippets Luau, Verse, JSON Minecraft ou JS.",
  },
  game_assets: {
    taskType: "game_assets",
    provider: "claude-design",
    fallbackProvider: "gemini",
    schema: "game-assets",
    reason: "Claude Design liste assets, prompts visuels, UI et thumbnails.",
  },
  game_ui_ux: {
    taskType: "game_ui_ux",
    provider: "claude-design",
    fallbackProvider: "gemini",
    schema: "game-ui-ux",
    reason: "Claude Design prepare HUD, feedback, onboarding, menus et experience joueur.",
  },
  game_prototype_code: {
    taskType: "game_prototype_code",
    provider: "claude-code",
    fallbackProvider: "mock",
    schema: "game-prototype-code",
    reason: "Claude Code prepare le prototype web jouable ou les snippets techniques de base.",
  },
  game_publishing: {
    taskType: "game_publishing",
    provider: "claude",
    fallbackProvider: "mock",
    schema: "game-publishing",
    reason: "Claude prepare checklist de publication sans promesse automatique.",
  },
  integration_mapping: {
    taskType: "integration_mapping",
    provider: "gemini",
    fallbackProvider: "mock",
    schema: "integration-mapping",
    reason: "Gemini mappe integration, permissions et prochaine etape.",
  },
  dashboard_recommendations: {
    taskType: "dashboard_recommendations",
    provider: "gemini",
    fallbackProvider: "mistral",
    schema: "dashboard-recommendations",
    reason: "Gemini transforme les signaux en recommandations actionnables.",
  },
  analytics_insights: {
    taskType: "analytics_insights",
    provider: "openai",
    fallbackProvider: "mistral",
    schema: "analytics-insights",
    reason: "OpenAI transforme les donnees en decisions business.",
  },
  creator_image_concept: {
    taskType: "creator_image_concept",
    provider: "gemini",
    fallbackProvider: "claude-design",
    schema: "creator-image-concept",
    reason: "Gemini prepare les pistes visuelles, couleurs, variantes et contraintes avant une generation image plus couteuse.",
  },
  creator_premium_image: {
    taskType: "creator_premium_image",
    provider: "pollojourney",
    fallbackProvider: "claude-design",
    schema: "creator-premium-image",
    reason: "Pollojourney est reserve aux images premium photorealistes, outpainting, upscale et multi-image blending.",
  },
  creator_avatar_video: {
    taskType: "creator_avatar_video",
    provider: "pollojourney",
    fallbackProvider: "claude-design",
    schema: "creator-avatar-video",
    reason: "Pollojourney/Pollo sert aux avatars et visuels video premium quand l'API serveur est configuree.",
  },
  creator_ad_creative: {
    taskType: "creator_ad_creative",
    provider: "openai",
    fallbackProvider: "claude-design",
    schema: "creator-ad-creative",
    reason: "OpenAI prepare l'angle, le hook, le message et le brief d'annonce avant une generation premium eventuelle.",
  },
  code_generation: {
    taskType: "code_generation",
    provider: "claude-code",
    fallbackProvider: "mock",
    schema: "code-generation",
    reason: "Claude Code gere generation technique et scripts.",
  },
  code_review: {
    taskType: "code_review",
    provider: "claude-code",
    fallbackProvider: "mock",
    schema: "code-review",
    reason: "Claude Code gere review, securite, tests et performance.",
  },
  bug_fix: {
    taskType: "bug_fix",
    provider: "claude-code",
    fallbackProvider: "mock",
    schema: "bug-fix",
    reason: "Claude Code corrige erreurs build, TypeScript, React et imports.",
  },
  refactor: {
    taskType: "refactor",
    provider: "claude-code",
    fallbackProvider: "mock",
    schema: "refactor",
    reason: "Claude Code gere refactor et maintenabilite.",
  },
  quality_gate: {
    taskType: "quality_gate",
    provider: "claude",
    fallbackProvider: "gemini",
    schema: "quality-gate",
    reason: "Claude critique la coherence et la qualite globale.",
  },
  output_normalization: {
    taskType: "output_normalization",
    provider: "gemini",
    fallbackProvider: "mock",
    schema: "output-normalization",
    reason: "Gemini normalise vers les formats Pixelrises.",
  },
  final_fusion: {
    taskType: "final_fusion",
    provider: "gemini",
    fallbackProvider: "mock",
    schema: "final-fusion",
    reason: "Gemini assemble les sorties en resultat final stable.",
  },
};

export const routingModeOverrides: Record<AIExecutionMode, Partial<Record<AITaskType, AIProviderId>>> = {
  simple: {},
  qualite: {
    site_design: "claude-design",
    creator_image_concept: "claude-design",
    creator_premium_image: "pollojourney",
    creator_avatar_video: "pollojourney",
    creator_ad_creative: "openai",
    code_generation: "claude-code",
    game_script: "claude-code",
  },
  rapide: {
    project_type_detection: "mistral",
    brief_analysis: "mistral",
    dashboard_recommendations: "mistral",
  },
  business: {
    strategy_analysis: "openai",
    business_positioning: "openai",
    site_conversion: "openai",
    analytics_insights: "openai",
  },
  cout_optimise: {
    project_type_detection: "mistral",
    brief_analysis: "mistral",
    site_design: "gemini",
    creator_image_concept: "gemini",
    creator_premium_image: "claude-design",
    creator_ad_creative: "openai",
    game_assets: "gemini",
  },
  avance: {},
};
