import { businessAISystemPrompt } from "./prompts/business-ai.prompt";
import { creatorAISystemPrompt } from "./prompts/creator-ai.prompt";
import { enterpriseAISystemPrompt } from "./prompts/enterprise-ai.prompt";
import { generalAISystemPrompt } from "./prompts/general-ai.prompt";
import { managementAISystemPrompt } from "./prompts/management-ai.prompt";
import { studentAISystemPrompt } from "./prompts/student-ai.prompt";
import type { AISpaceConfig, AISpaceType } from "./types";

const starterAccessRule =
  "Business AI reste l'espace universel. Le modèle conseillé est hybride : l'abonnement ouvre les espaces, les crédits contrôlent les actions coûteuses.";

export const aiSpacesRegistry: Record<AISpaceType, AISpaceConfig> = {
  business: {
    id: "business",
    name: "Business AI",
    shortName: "Business",
    tagline: "Créer, structurer et développer un projet business.",
    description: "Crée, structure et développe un projet ou un business avec l'IA Pixelrises.",
    status: "active",
    tone: "business",
    icon: "briefcase",
    accent: "from-[#F5C542]/24 via-[#F5C542]/8 to-transparent",
    targetUsers: ["entrepreneurs", "indépendants", "e-commerçants", "créateurs de projets"],
    capabilities: [
      "Trouver une idée de business",
      "Structurer une offre",
      "Créer une landing page",
      "Optimiser conversion et CTA",
      "Préparer une stratégie de lancement",
    ],
    quickActions: [
      {
        id: "business-idea",
        label: "Trouver une idée de business",
        description: "Transforme tes compétences, envies et contraintes en piste business claire.",
        prompt: "Aide-moi à trouver une idée de business réaliste et rentable selon mon profil.",
        resultType: "Idées priorisées",
      },
      {
        id: "offer",
        label: "Structurer mon offre",
        description: "Clarifie promesse, cible, prix, preuves et objections.",
        prompt: "Structure mon offre business avec promesse, cible, bénéfices, objections et CTA.",
        resultType: "Offre business",
      },
      {
        id: "landing",
        label: "Créer une landing page",
        description: "Prépare le brief à envoyer au Site Builder.",
        prompt: "Prépare une landing page orientée conversion pour mon idée.",
        resultType: "Brief Site Builder",
        builderLink: { label: "Envoyer vers Site Builder", href: "/builder/site", status: "ready" },
      },
      {
        id: "clients",
        label: "Trouver des clients",
        description: "Propose canaux, messages et actions de prospection propres.",
        prompt: "Donne-moi un plan simple pour trouver mes premiers clients.",
        resultType: "Plan acquisition",
      },
    ],
    recommendedAgents: ["Business Agent", "SEO Agent", "Conversion Agent", "Design Agent", "Copywriting Agent"],
    recommendedTemplates: ["Landing premium", "Service local", "Agence B2B", "E-commerce produit"],
    builderLinks: [
      { label: "Créer un site", href: "/builder/site", status: "ready" },
      { label: "Créer un agent", href: "/builder/agent", status: "ready" },
      { label: "Ouvrir Creator AI", href: "/ai-spaces/creator", status: "ready" },
      { label: "Préparer une boutique", href: "/create", status: "prepared" },
    ],
    dashboard: {
      primaryMetric: "Business Score",
      secondaryMetrics: ["Offres", "Sites", "Leads", "Conversions"],
      nextBestAction: "Clarifier l'offre puis créer le premier projet lié.",
      emptyState: "Commence par décrire ton idée, ton public cible et ton objectif.",
    },
    safetyRules: ["Pas de promesse de revenu garanti", "Validation requise avant action sensible"],
    systemPrompt: businessAISystemPrompt,
    workspace: {
      headline: "Atelier business-first",
      description:
        "Un espace universel pour passer d'une idée floue à une offre, un plan d'action et un projet digital concret.",
      primaryOutput: "Offre claire + plan de lancement",
      expertFocus: "Positionnement, conversion, preuve, priorité business",
      sections: [
        {
          id: "business-blueprints",
          title: "Livrables business",
          description: "Les livrables que l'espace Business AI doit produire avant d'envoyer vers un builder.",
          kind: "business",
          items: [
            {
              title: "Carte de l'offre",
              description: "Promesse, cible, problème, bénéfices, preuve, prix et objection principale.",
              status: "ready",
              actionLabel: "Structurer",
              tags: ["Offre", "Conversion"],
            },
            {
              title: "Plan de lancement",
              description: "Séquence 7 jours avec actions, canaux, messages et KPI simples.",
              status: "ready",
              actionLabel: "Planifier",
              tags: ["Go-to-market", "KPI"],
            },
            {
              title: "Brief Site Builder",
              description: "Brief prêt à transmettre au générateur pour éviter les sites génériques.",
              status: "ready",
              actionLabel: "Créer le site",
              href: "/builder/site",
              tags: ["Site", "SEO"],
            },
            {
              title: "Brief pub ou visuel final",
              description: "Business AI cadre l'angle, l'offre et le message, puis passe Creator AI pour produire le rendu marketing final.",
              status: "ready",
              actionLabel: "Ouvrir Creator AI",
              href: "/ai-spaces/creator",
              tags: ["Creator AI", "Brief", "Redirection"],
            },
          ],
        },
        {
          id: "business-tools",
          title: "Outils connectables",
          description: "Les connexions réelles se font uniquement après autorisation utilisateur.",
          kind: "tools",
          items: [
            {
              title: "Recherche marché assistée",
              description: "Prépare les requêtes et synthétise les résultats quand la recherche web est branchée.",
              status: "prepared",
              actionLabel: "Préparer",
              tags: ["Recherche", "Marché"],
            },
            {
              title: "Site Builder",
              description: "Envoie l'offre vers le générateur avec niche, preuve, CTA et style.",
              status: "ready",
              href: "/builder/site",
              actionLabel: "Ouvrir",
              tags: ["Builder"],
            },
            {
              title: "Analytics",
              description: "Relie les décisions à des métriques réelles quand les événements sont disponibles.",
              status: "prepared",
              href: "/analytics",
              actionLabel: "Analyser",
              tags: ["Score", "CA"],
            },
          ],
        },
      ],
      promptTips: [
        {
          title: "Donne le contexte business",
          description: "L'IA répond mieux si elle connaît la cible, le prix, le problème et l'objectif.",
          example: "Je vends [offre] à [cible], mon objectif est [leads/vente], mon prix est [prix].",
        },
        {
          title: "Demande un résultat mesurable",
          description: "Évite les réponses vagues en demandant une action, un KPI ou une décision.",
          example: "Donne-moi 3 options classées par impact, difficulté et risque.",
        },
      ],
      accessPolicy: {
        recommendedPlan: "starter",
        includedIn: ["Starter", "Pro", "Business", "Enterprise"],
        creditCost: 2,
        modelPolicy: "Sélection qualité côté serveur : stratégie et copywriting en mode premium, résumé en mode économique.",
        businessRule: starterAccessRule,
      },
    },
  },
  student: {
    id: "student",
    name: "Student AI",
    shortName: "Étudiant",
    tagline: "Apprendre, créer et avancer sans tricher.",
    description: "Révise, comprends tes cours, prépare tes évaluations et transforme tes projets en supports, sites, apps, jeux ou agents guidés.",
    status: "beta",
    tone: "pedagogical",
    icon: "graduation",
    accent: "from-violet-400/22 via-violet-300/7 to-transparent",
    targetUsers: ["étudiants", "lycéens", "apprenants", "parents", "alternants", "projets de groupe"],
    capabilities: [
      "Expliquer un cours simplement",
      "Créer une fiche de révision",
      "Générer un quiz",
      "Préparer un oral",
      "Créer un diaporama",
      "Corriger une interrogation avec méthode",
      "Préparer une recherche fiable",
      "Organiser devoirs et planning",
      "Préparer un site, une app ou un prototype",
      "Créer un mini-jeu éducatif",
      "Créer un agent IA étudiant",
    ],
    quickActions: [
      {
        id: "revision-sheet",
        label: "Faire une fiche de révision",
        description: "Résume un cours en notions, définitions, exemples et pièges.",
        prompt: "Crée une fiche de révision pédagogique à partir de mon cours.",
        resultType: "Fiche",
      },
      {
        id: "quiz",
        label: "Créer un quiz",
        description: "Génère des questions avec correction pour t'entraîner.",
        prompt: "Crée un quiz progressif pour m'entraîner sur ce sujet.",
        resultType: "Quiz",
      },
      {
        id: "oral",
        label: "Préparer un oral",
        description: "Structure intro, plan, transitions et entraînement.",
        prompt: "Aide-moi à préparer un oral clair et convaincant.",
        resultType: "Plan oral",
      },
      {
        id: "slides",
        label: "Créer un diaporama",
        description: "Plan, slides, transitions, script oral et questions possibles.",
        prompt: "Prépare un diaporama complet avec plan, slides, transitions, script oral et questions possibles.",
        resultType: "Diaporama",
      },
      {
        id: "correction",
        label: "Corriger une interrogation",
        description: "Repère les erreurs, explique la méthode et propose une version améliorée.",
        prompt: "Corrige mon interrogation avec méthode : points justes, erreurs, explication et version améliorée.",
        resultType: "Correction guidée",
      },
      {
        id: "homework-plan",
        label: "Organiser mes devoirs",
        description: "Transforme tes devoirs en planning réaliste.",
        prompt: "Organise mes devoirs et révisions en planning simple.",
        resultType: "Planning",
      },
      {
        id: "student-project",
        label: "Créer un projet digital",
        description: "Prépare un site, une app, un jeu ou un agent IA pour un projet étudiant.",
        prompt: "Transforme mon idée en projet digital étudiant : site, app, jeu ou agent IA, avec brief, étapes, limites et validation.",
        resultType: "Brief projet",
      },
    ],
    recommendedAgents: [
      "Study Agent",
      "Revision Agent",
      "Quiz Agent",
      "Oral Coach Agent",
      "Slides Agent",
      "Research Agent",
      "Project Builder Agent",
      "No-Cheat Tutor Agent",
    ],
    recommendedTemplates: [
      "Fiche révision",
      "Quiz",
      "Planning scolaire",
      "Présentation",
      "Correction guidée",
      "Recherche sourcée",
      "Brief site/app",
      "Brief jeu éducatif",
      "Brief agent IA",
    ],
    builderLinks: [
      { label: "Créer une fiche", href: "/ai-spaces/student", status: "prepared" },
      { label: "Préparer un site", href: "/builder/site", status: "ready" },
      { label: "Créer un agent", href: "/builder/agent", status: "ready" },
      { label: "Créer un jeu éducatif", href: "/builder/game", status: "ready" },
      { label: "App/prototype guidé", href: "/ai-spaces/student", status: "prepared" },
    ],
    dashboard: {
      primaryMetric: "Progression",
      secondaryMetrics: ["Fiches", "Quiz", "Slides", "Projets", "Oral", "Recherche"],
      nextBestAction: "Créer une fiche, un quiz ou un brief de projet pour avancer.",
      emptyState: "Colle un cours, décris ton contrôle ou donne ton idée de projet étudiant.",
    },
    safetyRules: [
      "Ne pas encourager la triche",
      "Toujours expliquer la méthode",
      "Ne pas inventer de source",
      "Ne pas publier ni envoyer sans validation humaine",
      "Présenter les sites, apps, jeux et agents comme brouillons ou briefs tant qu'ils ne sont pas générés dans le builder dédié",
    ],
    systemPrompt: studentAISystemPrompt,
    workspace: {
      headline: "Studio étudiant complet",
      description:
        "Un espace pédagogique qui aide à comprendre, mémoriser, s'entraîner et préparer des projets concrets. L'objectif est la progression, pas la triche.",
      primaryOutput: "Fiche + quiz + slides + projet guidé",
      expertFocus: "Pédagogie, méthode, mémorisation active, recherche, projets digitaux",
      sections: [
        {
          id: "student-study-kit",
          title: "Fiches de révision et entraînement",
          description: "Des formats prêts pour apprendre vraiment, avec correction et méthode.",
          kind: "study",
          items: [
            {
              title: "Fiche de révision structurée",
              description: "Notions clés, définitions, exemples, erreurs fréquentes et mini synthèse.",
              status: "ready",
              actionLabel: "Créer une fiche",
              tags: ["Révision", "Méthode"],
            },
            {
              title: "Quiz corrigé",
              description: "Questions faciles, moyennes et difficiles avec explication des réponses.",
              status: "ready",
              actionLabel: "M'entraîner",
              tags: ["Quiz", "Correction"],
            },
            {
              title: "Flashcards",
              description: "Cartes question/réponse pour mémoriser sans relire passivement.",
              status: "prepared",
              actionLabel: "Préparer",
              tags: ["Mémoire", "Active recall"],
            },
            {
              title: "Correction d'interrogation",
              description: "Analyse les réponses, explique les erreurs et donne une méthode pour refaire seul.",
              status: "ready",
              actionLabel: "Corriger",
              tags: ["Évaluation", "Méthode"],
            },
            {
              title: "Diaporama + oral",
              description: "Plan, slides, transitions, script oral et questions possibles pour présenter clairement.",
              status: "ready",
              actionLabel: "Préparer",
              tags: ["Slides", "Oral"],
            },
          ],
        },
        {
          id: "student-project-builders",
          title: "Projets digitaux étudiants",
          description: "Student AI peut préparer un brief exploitable pour les builders Pixelrises sans publier automatiquement.",
          kind: "tools",
          items: [
            {
              title: "Site web de projet",
              description: "Objectif, public, sections, contenu, CTA, SEO et style avant ouverture dans Site Builder.",
              status: "ready",
              actionLabel: "Créer le brief",
              href: "/builder/site",
              tags: ["Site Builder", "SEO"],
            },
            {
              title: "App ou prototype",
              description: "Écrans, fonctionnalités, parcours, données et logique technique de départ.",
              status: "prepared",
              actionLabel: "Préparer",
              tags: ["App", "Prototype"],
            },
            {
              title: "Mini-jeu éducatif",
              description: "Objectif pédagogique, règles, score, progression et limites de publication.",
              status: "ready",
              actionLabel: "Créer",
              href: "/builder/game",
              tags: ["Game Builder", "Prototype"],
            },
            {
              title: "Agent IA étudiant",
              description: "Rôle, mission, limites, permissions sûres et tests de comportement.",
              status: "ready",
              actionLabel: "Créer",
              href: "/builder/agent",
              tags: ["Agent Builder", "Sécurité"],
            },
          ],
        },
        {
          id: "student-research",
          title: "Recherche, méthodes et planning",
          description: "Préparé pour rechercher plus vite, vérifier les sources, expliquer les méthodes et organiser le travail.",
          kind: "tools",
          items: [
            {
              title: "Recherche Google préparée",
              description:
                "L'IA prépare les requêtes et la grille de vérification. La connexion recherche web réelle devra être autorisée.",
              status: "requires-connection",
              actionLabel: "Configurer",
              href: "/integrations",
              tags: ["Recherche", "Sources"],
            },
            {
              title: "Bibliographie simple",
              description: "Classe les sources par fiabilité, utilité et date quand les résultats sont fournis.",
              status: "prepared",
              actionLabel: "Analyser",
              tags: ["Sources", "Fiabilité"],
            },
            {
              title: "Planning de révision",
              description: "Transforme les échéances en sessions courtes avec priorités.",
              status: "ready",
              actionLabel: "Planifier",
              tags: ["Planning"],
            },
            {
              title: "Méthode d'exercice",
              description: "Découpe le raisonnement étape par étape avec exemple guidé et exercice d'entraînement.",
              status: "ready",
              actionLabel: "Comprendre",
              tags: ["Méthode", "Exercices"],
            },
          ],
        },
      ],
      promptTips: [
        {
          title: "Ajoute ton niveau",
          description: "Le niveau permet d'adapter vocabulaire, exemples et exercices.",
          example: "Je suis en terminale, niveau moyen, contrôle dans 5 jours sur les dérivées.",
        },
        {
          title: "Demande la méthode, pas juste la réponse",
          description: "Student AI doit expliquer le raisonnement pour t'aider à progresser.",
          example: "Explique étape par étape puis donne-moi 5 questions d'entraînement.",
        },
        {
          title: "Précise le livrable",
          description: "Dis si tu veux une fiche, un oral, un diaporama, un site, une app, un jeu ou un agent.",
          example: "Je veux un diaporama de 8 slides avec script oral et questions possibles.",
        },
        {
          title: "Pour les projets, donne le contexte",
          description: "Le builder sera meilleur si Student AI connaît le sujet, le public, les contraintes et le format final.",
          example: "Projet de groupe : créer un site pour présenter une association étudiante, niveau BTS, deadline vendredi.",
        },
      ],
      accessPolicy: {
        recommendedPlan: "starter",
        includedIn: ["Starter", "Pro", "Business", "Enterprise"],
        creditCost: 1,
        modelPolicy: "Mode économique prioritaire côté serveur, escalade qualité si raisonnement long ou document complexe.",
        businessRule: starterAccessRule,
      },
    },
  },
  management: {
    id: "management",
    name: "Management AI",
    shortName: "Gestion",
    tagline: "Organiser, prioriser et suivre sans se disperser.",
    description: "Organise tes tâches, tes relances, tes projets et ton planning.",
    status: "beta",
    tone: "organized",
    icon: "kanban",
    accent: "from-emerald-400/20 via-emerald-300/6 to-transparent",
    targetUsers: ["indépendants", "managers", "fondateurs", "équipes"],
    capabilities: ["Todo lists", "Planning semaine", "Relances", "Workflows", "Suivi projet"],
    quickActions: [
      {
        id: "week",
        label: "Organiser ma semaine",
        description: "Priorise tes objectifs, contraintes et blocs de travail.",
        prompt: "Organise ma semaine avec priorités, blocs de temps et actions importantes.",
        resultType: "Planning semaine",
      },
      {
        id: "workflow",
        label: "Créer un workflow",
        description: "Transforme une routine en processus simple.",
        prompt: "Crée un workflow simple pour organiser cette activité.",
        resultType: "Workflow",
      },
      {
        id: "follow-up",
        label: "Préparer des relances",
        description: "Crée messages, cadence et tableau de suivi.",
        prompt: "Prépare des relances client/prospect claires et non agressives.",
        resultType: "Relances",
      },
    ],
    recommendedAgents: ["Planning Agent", "Workflow Agent", "Client Follow-up Agent", "Task Agent"],
    recommendedTemplates: ["Todo business", "Pipeline client", "Planning hebdo", "Workflow simple"],
    builderLinks: [
      { label: "Automations", href: "/automations", status: "prepared" },
      { label: "Créer un agent gestion", href: "/builder/agent", status: "ready" },
    ],
    dashboard: {
      primaryMetric: "Clarté opérationnelle",
      secondaryMetrics: ["Tâches", "Relances", "Workflows", "Priorités"],
      nextBestAction: "Transformer les idées en actions planifiées.",
      emptyState: "Ajoute tes objectifs et contraintes de la semaine.",
    },
    safetyRules: ["Aucune relance envoyée sans validation", "Aucune connexion outil sans accord"],
    systemPrompt: managementAISystemPrompt,
    workspace: {
      headline: "Command center opérationnel",
      description:
        "Un espace pour transformer le chaos en tableaux, priorités, suivis et workflows compatibles avec les outils métier.",
      primaryOutput: "Plan + tableau + workflow",
      expertFocus: "Priorisation, coordination, suivi, automatisation prudente",
      sections: [
        {
          id: "management-boards",
          title: "Tableaux de pilotage",
          description: "Des vues simples pour suivre tâches, relances, projets et décisions.",
          kind: "management",
          items: [
            {
              title: "Tableau tâches prioritaires",
              description: "Liste triée par impact, urgence, effort et blocage.",
              status: "ready",
              actionLabel: "Organiser",
              tags: ["Priorités", "To-do"],
            },
            {
              title: "Pipeline de relances",
              description: "Statuts, message suivant, date de relance et risque de friction.",
              status: "ready",
              actionLabel: "Préparer",
              tags: ["CRM", "Relances"],
            },
            {
              title: "Rituel hebdomadaire",
              description: "Plan lundi-vendredi avec objectifs, check-in et revue finale.",
              status: "prepared",
              actionLabel: "Créer",
              tags: ["Planning"],
            },
          ],
        },
        {
          id: "management-integrations",
          title: "Excel, Sheets et intégrations",
          description: "Connexion préparée pour manipuler les données sans inventer de lien non autorisé.",
          kind: "tools",
          items: [
            {
              title: "Import Excel / CSV",
              description: "Préparé pour transformer un fichier en tableau d'actions et synthèse.",
              status: "prepared",
              actionLabel: "Préparer l'import",
              tags: ["Excel", "CSV"],
            },
            {
              title: "Google Sheets",
              description: "Synchronisation possible après connexion dans le hub d'intégrations.",
              status: "requires-connection",
              href: "/integrations",
              actionLabel: "Configurer",
              tags: ["Sheets"],
            },
            {
              title: "Notion / Slack / Make",
              description: "Préparé pour workflows, comptes rendus et notifications validées.",
              status: "requires-connection",
              href: "/integrations",
              actionLabel: "Voir les connexions",
              tags: ["Workflow", "Équipe"],
            },
          ],
        },
      ],
      promptTips: [
        {
          title: "Donne les contraintes",
          description: "Temps disponible, échéances, personnes impliquées et blocages changent le plan.",
          example: "J'ai 6h cette semaine, 3 clients à relancer, une livraison vendredi.",
        },
        {
          title: "Demande un tableau exploitable",
          description: "Pour Excel ou Sheets, demande des colonnes précises.",
          example: "Réponds en tableau avec tâche, priorité, responsable, échéance, prochaine action.",
        },
      ],
      accessPolicy: {
        recommendedPlan: "pro",
        includedIn: ["Pro", "Business", "Enterprise"],
        creditCost: 2,
        modelPolicy: "Router économique pour tri/tableaux, modèle qualité pour workflows complexes.",
        businessRule: "Management AI est idéal en Pro : assez puissant pour vendre l'organisation sans ouvrir les connecteurs sensibles en Starter.",
      },
    },
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise AI",
    shortName: "Entreprise",
    tagline: "Documents, process et supports professionnels.",
    description: "Crée des documents, process, comptes rendus et supports professionnels.",
    status: "beta",
    tone: "professional",
    icon: "building",
    accent: "from-blue-400/20 via-blue-300/6 to-transparent",
    targetUsers: ["entreprises", "équipes", "consultants", "managers"],
    capabilities: ["Procédures", "Comptes rendus", "Briefs", "Présentations", "Plans d'action"],
    quickActions: [
      {
        id: "procedure",
        label: "Créer une procédure",
        description: "Standardise une tâche en process réutilisable.",
        prompt: "Crée une procédure professionnelle claire pour ce processus.",
        resultType: "Procédure",
      },
      {
        id: "meeting",
        label: "Résumer une réunion",
        description: "Transforme notes en compte rendu, décisions et actions.",
        prompt: "Résume cette réunion avec décisions, actions, responsables et échéances.",
        resultType: "Compte rendu",
      },
      {
        id: "brief",
        label: "Créer un brief",
        description: "Structure contexte, objectif, contraintes, livrables.",
        prompt: "Crée un brief professionnel à partir de mes notes.",
        resultType: "Brief",
      },
    ],
    recommendedAgents: ["Enterprise Agent", "Docs Agent", "Meeting Summary Agent", "Process Agent"],
    recommendedTemplates: ["Procédure", "Compte rendu", "Brief projet", "Plan d'action"],
    builderLinks: [
      { label: "Créer un agent entreprise", href: "/builder/agent", status: "ready" },
      { label: "Docs module plus tard", href: "/create", status: "soon" },
    ],
    dashboard: {
      primaryMetric: "Qualité opérationnelle",
      secondaryMetrics: ["Documents", "Process", "Actions", "Équipes"],
      nextBestAction: "Standardiser le prochain process récurrent.",
      emptyState: "Colle tes notes, ton brief ou ton process actuel.",
    },
    safetyRules: ["Éviter les données sensibles dans les logs", "Validation avant partage externe"],
    systemPrompt: enterpriseAISystemPrompt,
    workspace: {
      headline: "Workspace documentaire sécurisé",
      description:
        "Un espace orienté entreprise pour produire, auditer et transformer des documents. Aucun fichier local n'est lu sans upload ou autorisation explicite.",
      primaryOutput: "Procédure + plan d'action",
      expertFocus: "Clarté, conformité, documentation, validation humaine",
      sections: [
        {
          id: "enterprise-docs",
          title: "Documents professionnels",
          description: "Formats utiles pour équipes, clients, opérations et direction.",
          kind: "enterprise",
          items: [
            {
              title: "Procédure interne",
              description: "Étapes, responsabilités, contrôles et erreurs à éviter.",
              status: "ready",
              actionLabel: "Créer",
              tags: ["Process", "Qualité"],
            },
            {
              title: "Compte rendu de réunion",
              description: "Décisions, actions, responsables, échéances et risques.",
              status: "ready",
              actionLabel: "Résumer",
              tags: ["Meeting", "Actions"],
            },
            {
              title: "Brief projet",
              description: "Objectif, périmètre, contraintes, livrables, calendrier et validation.",
              status: "ready",
              actionLabel: "Structurer",
              tags: ["Brief", "Projet"],
            },
          ],
        },
        {
          id: "enterprise-files",
          title: "Fichiers et accès contrôlés",
          description: "Préparé pour travailler avec fichiers, mais jamais en lecture automatique du PC.",
          kind: "security",
          items: [
            {
              title: "Upload sécurisé de fichiers",
              description: "À brancher pour analyser PDF, DOCX, CSV ou notes après validation utilisateur.",
              status: "prepared",
              actionLabel: "Préparer",
              tags: ["Fichiers", "Sécurité"],
            },
            {
              title: "Connecteur Drive / SharePoint",
              description: "Prévu pour accès autorisé, journalisé et révocable aux documents d'équipe.",
              status: "requires-connection",
              href: "/integrations",
              actionLabel: "Configurer",
              tags: ["Drive", "SharePoint"],
            },
            {
              title: "Accès local via agent de travail",
              description: "Possible plus tard via Codex/Claude ou connecteur agent, uniquement sur fichiers autorisés.",
              status: "soon",
              actionLabel: "Planifier",
              tags: ["Codex", "Claude", "PC"],
            },
          ],
        },
      ],
      promptTips: [
        {
          title: "Définis le contexte d'entreprise",
          description: "Le ton, les règles internes et le niveau de détail évitent les documents génériques.",
          example: "Document pour équipe support, ton professionnel, format procédure, 8 étapes maximum.",
        },
        {
          title: "Indique les données sensibles",
          description: "Demande une version anonymisée si le document contient clients, emails, contrats ou chiffres.",
          example: "Anonymise les noms et ne conserve que les décisions et actions.",
        },
      ],
      accessPolicy: {
        recommendedPlan: "enterprise",
        includedIn: ["Enterprise"],
        creditCost: 4,
        modelPolicy: "Modèle qualité pour documents longs et cohérence, avec logs non sensibles et redaction.",
        businessRule: "Enterprise AI doit rester un levier premium : fichiers, équipes, conformité et connecteurs avancés.",
      },
    },
  },
  creator: {
    id: "creator",
    name: "Creator AI",
    shortName: "Créateur",
    tagline: "Scripts, visuels premium, pubs, avatars et campagnes.",
    description: "Prépare des contenus, prompts image, publicités, avatars et campagnes créatives avec moteurs image/vidéo spécialisés et coûts maîtrisés.",
    status: "beta",
    tone: "creative",
    icon: "sparkles",
    accent: "from-pink-400/20 via-orange-300/6 to-transparent",
    targetUsers: ["créateurs", "marques personnelles", "e-commerçants", "community managers"],
    capabilities: [
      "Idées de vidéos",
      "Scripts courts",
      "Hooks",
      "Posts",
      "Calendrier éditorial",
      "Prompts image premium",
      "Publicités produit",
      "Avatars et UGC",
      "Moodboards de campagne",
      "Upscale / outpainting préparés",
    ],
    quickActions: [
      {
        id: "video-ideas",
        label: "Trouver des idées de vidéos",
        description: "Génère angles, formats et séries selon ta niche.",
        prompt: "Trouve des idées de vidéos adaptées à ma niche et à mon objectif.",
        resultType: "Idées contenu",
      },
      {
        id: "script",
        label: "Écrire un script TikTok",
        description: "Hook, structure, rythme, CTA et variation.",
        prompt: "Écris un script TikTok/Reels/Shorts avec hook fort et CTA.",
        resultType: "Script",
      },
      {
        id: "calendar",
        label: "Créer un calendrier de contenu",
        description: "Planifie thèmes, formats et objectifs.",
        prompt: "Crée un calendrier de contenu simple pour les 14 prochains jours.",
        resultType: "Calendrier",
      },
      {
        id: "premium-image",
        label: "Préparer une image premium",
        description: "Brief Pollojourney/MidJourney-like avec style, format, marque et coût estimé.",
        prompt:
          "/image-premium Prépare un visuel premium pour ma campagne. Demande-moi si tu dois vraiment lancer la génération image payante.",
        resultType: "Brief image premium",
      },
      {
        id: "product-ad",
        label: "Créer une pub produit",
        description: "Angle, hook, visuel, script court et CTA sans promettre de résultat garanti.",
        prompt: "Crée une publicité produit avec angle, visuel, script court, CTA et variantes pour réseaux sociaux.",
        resultType: "Pub créative",
      },
    ],
    recommendedAgents: ["Content Agent", "Script Agent", "Hook Agent", "Social Media Agent", "Visual Campaign Agent"],
    recommendedTemplates: ["Script court", "Calendrier contenu", "Hooks", "Posts", "Prompt image premium", "Pub produit"],
    builderLinks: [
      { label: "Cadrer la stratégie dans Business AI", href: "/ai-spaces/business", status: "ready" },
      { label: "Créer un agent contenu", href: "/builder/agent", status: "ready" },
      { label: "Marketing module plus tard", href: "/create", status: "soon" },
    ],
    dashboard: {
      primaryMetric: "Production créative",
      secondaryMetrics: ["Idées", "Scripts", "Images", "Publicités"],
      nextBestAction: "Transformer une idée en campagne avec brief visuel et coût estimé.",
      emptyState: "Décris ton produit, ta plateforme, ton style et le rendu attendu.",
    },
    safetyRules: [
      "Pas de promesse de viralité",
      "Adapter à la plateforme et au public",
      "Image ou vidéo payante uniquement après validation explicite",
      "Aucun provider, model id ou secret visible",
      "Aucun contenu trompeur, faux avant/après ou fausse preuve",
    ],
    systemPrompt: creatorAISystemPrompt,
    workspace: {
      headline: "Studio d'inspiration et de contenu",
      description:
        "Un espace pour trouver des angles, lire des inspirations, améliorer ses demandes et produire des contenus plus précis.",
      primaryOutput: "Inspiration + script + calendrier",
      expertFocus: "Hook, rythme, angle, cohérence de niche",
      sections: [
        {
          id: "creator-inspiration",
          title: "Inspirations et articles",
          description: "Un tableau d'inspiration éditoriale sans copier les créateurs ou les marques.",
          kind: "resources",
          items: [
            {
              title: "Bibliothèque d'angles",
              description: "Avant/après, erreur fréquente, coulisses, preuve, opinion, tutoriel, étude de cas.",
              status: "ready",
              actionLabel: "Explorer",
              tags: ["Hooks", "Angles"],
            },
            {
              title: "Articles à résumer",
              description: "Préparé pour importer un article ou un lien et en extraire idées, citations et limites.",
              status: "prepared",
              actionLabel: "Préparer",
              tags: ["Articles", "Veille"],
            },
            {
              title: "Moodboard de campagne",
              description: "Prépare ton style, ton ton, tes exemples et tes formats récurrents.",
              status: "prepared",
              actionLabel: "Créer",
              tags: ["Moodboard", "Brand"],
            },
          ],
        },
        {
          id: "creator-prompt-coach",
          title: "Coach de demande IA",
          description: "Aide l'utilisateur à écrire une meilleure demande pour obtenir une réponse plus utile.",
          kind: "creator",
          items: [
            {
              title: "Prompt en 6 blocs",
              description: "Objectif, audience, plateforme, ton, format, contraintes.",
              status: "ready",
              actionLabel: "Utiliser",
              tags: ["Prompt", "Qualité"],
            },
            {
              title: "Variations de hooks",
              description: "Génère plusieurs hooks avec niveau de risque, promesse et preuve.",
              status: "ready",
              actionLabel: "Générer",
              tags: ["Hook", "Script"],
            },
            {
              title: "Calendrier éditorial",
              description: "Plan 14 jours par pilier de contenu et objectif business.",
              status: "ready",
              actionLabel: "Planifier",
              tags: ["Calendrier"],
            },
          ],
        },
        {
          id: "creator-visual-studio",
          title: "Studio visuel premium",
          description: "Prépare les visuels haut de gamme avant génération payante: image, publicité, avatar, upscale et outpainting.",
          kind: "creator",
          items: [
            {
              title: "Image AI rapide",
              description: "Prépare un visuel simple, une variation ou une direction d'image rapide avant le mode premium.",
              status: "prepared",
              actionLabel: "Préparer",
              tags: ["Image AI", "Gemini", "Rapide"],
              meta: "Conçu pour idéation et variantes légères à coût modéré, sans prétendre qu'un moteur premium tourne déjà.",
            },
            {
              title: "Pollojourney image premium",
              description: "Pour photoréalisme, direction artistique forte, campagnes social ads et rendus plus premium.",
              status: "requires-connection",
              actionLabel: "Préparer",
              tags: ["Image", "Premium", "10+ crédits"],
              meta: "Nécessite POLLO_API_KEY côté serveur. Aucun appel automatique sans validation.",
            },
            {
              title: "Publicité produit",
              description: "Angle de vente, scène produit, prompt visuel, script court, CTA et variantes adaptées au canal.",
              status: "prepared",
              actionLabel: "Créer",
              tags: ["Ads", "Produit", "UGC"],
              meta: "Le brief est disponible sans coût élevé; génération réelle seulement si validée.",
            },
            {
              title: "Avatar et vidéo courte",
              description: "Prépare avatar, scène, dialogue, mouvement, format vertical et garde-fous de marque.",
              status: "requires-connection",
              actionLabel: "Préparer",
              tags: ["Video AI", "Avatar", "Premium"],
              meta: "Fonction premium Pollo à configurer et facturer plus cher.",
            },
            {
              title: "Upscale / outpainting",
              description: "Améliore un visuel existant ou étend une scène avec consignes de cohérence et limites claires.",
              status: "requires-connection",
              actionLabel: "Préparer",
              tags: ["Upscale", "Outpainting"],
              meta: "URLs image HTTPS requises; base64 non accepté par Pollojourney.",
            },
          ],
        },
      ],
      promptTips: [
        {
          title: "Donne la plateforme",
          description: "TikTok, Reels, YouTube ou LinkedIn ne demandent pas le même rythme.",
          example: "Plateforme TikTok, cible entrepreneurs débutants, ton direct, vidéo 35 secondes.",
        },
        {
          title: "Ajoute une inspiration sans copier",
          description: "Décris ce que tu aimes dans un style plutôt que de demander une copie.",
          example: "Je veux un ton premium, rapide, avec une preuve concrète et un CTA simple.",
        },
        {
          title: "Précise le niveau de qualité",
          description: "Plus la qualité visuelle est haute, plus le coût en crédits doit être élevé.",
          example: "Mode premium: publicité produit 9:16, rendu photoréaliste, couleurs noir/or, CTA clair.",
        },
      ],
      accessPolicy: {
        recommendedPlan: "pro",
        includedIn: ["Starter", "Pro", "Business", "Enterprise"],
        creditCost: 5,
        modelPolicy:
          "Idées/scripts en modèle économique; images premium via Pollojourney uniquement en mode validé, avec coût plus élevé.",
        businessRule: "Creator AI doit rester rentable: brief peu coûteux, génération image/video premium facturée plus cher.",
      },
    },
  },
  general: {
    id: "general",
    name: "General AI",
    shortName: "Généraliste",
    tagline: "L'assistant polyvalent intégré à Pixelrises.",
    description: "Pose une question, résume, rédige, organise ou réfléchis avec l'IA.",
    status: "active",
    tone: "general",
    icon: "message",
    accent: "from-cyan-400/18 via-cyan-300/6 to-transparent",
    targetUsers: ["débutants", "utilisateurs avancés", "clients", "équipes"],
    capabilities: ["Questions", "Résumé", "Rédaction", "Traduction", "Organisation", "Décision"],
    quickActions: [
      {
        id: "question",
        label: "Poser une question",
        description: "Obtiens une réponse claire et actionnable.",
        prompt: "Réponds clairement à ma question et propose la prochaine action.",
        resultType: "Réponse",
      },
      {
        id: "summary",
        label: "Résumer un texte",
        description: "Extrait l'essentiel, les décisions et les actions.",
        prompt: "Résume ce texte en points clairs, décisions et actions.",
        resultType: "Résumé",
      },
      {
        id: "plan",
        label: "Créer un plan",
        description: "Organise une idée en étapes simples.",
        prompt: "Transforme cette idée en plan clair et priorisé.",
        resultType: "Plan",
      },
    ],
    recommendedAgents: ["General Assistant", "Writing Agent", "Summary Agent", "Planning Agent"],
    recommendedTemplates: ["Plan simple", "Résumé", "Message", "Décision"],
    builderLinks: [
      { label: "Choisir un builder", href: "/create", status: "ready" },
      { label: "Ouvrir Business AI", href: "/ai-spaces/business", status: "ready" },
    ],
    dashboard: {
      primaryMetric: "Aide utile",
      secondaryMetrics: ["Questions", "Plans", "Textes", "Décisions"],
      nextBestAction: "Demander une réponse ou basculer vers un espace spécialisé.",
      emptyState: "Pose une question ou colle un texte à organiser.",
    },
    safetyRules: ["Orienter vers un espace spécialisé si utile", "Ne pas demander de secret"],
    systemPrompt: generalAISystemPrompt,
    workspace: {
      headline: "Assistant économique intelligent",
      description:
        "L'espace général sert aux tâches simples et rapides. Le choix du modèle reste côté serveur pour optimiser qualité, coût et disponibilité.",
      primaryOutput: "Réponse claire + prochaine action",
      expertFocus: "Rapidité, coût maîtrisé, orientation vers le bon espace",
      sections: [
        {
          id: "general-actions",
          title: "Actions polyvalentes",
          description: "Ce que l'assistant général doit gérer sans alourdir le coût.",
          kind: "general",
          items: [
            {
              title: "Résumé rapide",
              description: "Synthèse, décisions, actions, risques.",
              status: "ready",
              actionLabel: "Résumer",
              tags: ["Résumé"],
            },
            {
              title: "Rédaction simple",
              description: "Message, email, reformulation, traduction courte.",
              status: "ready",
              actionLabel: "Rédiger",
              tags: ["Texte"],
            },
            {
              title: "Orientation intelligente",
              description: "Bascule vers Business, Student, Creator ou Enterprise si le sujet devient spécialisé.",
              status: "ready",
              actionLabel: "Orienter",
              tags: ["Orientation"],
            },
          ],
        },
        {
          id: "general-model-policy",
          title: "Qualité et contrôle",
          description: "Masquer la complexité technique côté utilisateur, tout en contrôlant le coût côté serveur.",
          kind: "tools",
          items: [
            {
              title: "Mode rapide Pixelrises",
              description: "Utilise un mode rapide et économique pour les tâches simples selon disponibilité serveur.",
              status: "prepared",
              actionLabel: "Configurer serveur",
              tags: ["Coût", "Serveur"],
            },
            {
              title: "Escalade qualité",
              description: "Passe à un modèle plus fort uniquement si la demande exige stratégie, code ou raisonnement long.",
              status: "prepared",
              actionLabel: "Router",
              tags: ["Qualité"],
            },
          ],
        },
      ],
      promptTips: [
        {
          title: "Demande une réponse courte ou profonde",
          description: "Le niveau de détail aide à contrôler coût et précision.",
          example: "Réponds en 5 lignes, puis donne-moi 3 actions.",
        },
        {
          title: "Indique si tu veux un format",
          description: "Plan, tableau, email, checklist ou résumé changent la sortie.",
          example: "Réponds en tableau : idée, impact, difficulté, prochaine action.",
        },
      ],
      accessPolicy: {
        recommendedPlan: "starter",
        includedIn: ["Starter", "Pro", "Business", "Enterprise"],
        creditCost: 1,
        modelPolicy: "Mode économique pour les tâches courantes, escalade premium seulement si nécessaire.",
        businessRule: "General AI doit être inclus partout : il rassure les débutants et sert de porte d'entrée vers les espaces spécialisés.",
      },
    },
  },
};

export const aiSpacesList = Object.values(aiSpacesRegistry);

export const defaultAISpaceType: AISpaceType = "business";

export const getAISpaceConfig = (spaceType: string | undefined) => {
  if (!spaceType) return null;
  return aiSpacesRegistry[spaceType as AISpaceType] ?? null;
};
