import {
  BarChart3,
  Bot,
  Brain,
  Brush,
  Cable,
  Code2,
  CreditCard,
  Gamepad2,
  Globe2,
  MessageCircle,
  Palette,
  PenLine,
  Rocket,
  Search,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Store,
  Target,
  Trophy,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { ProjectType } from "@/modules/creation-engine";

export type RegistryStatus = "connected" | "available" | "development" | "soon" | "requested" | "beta" | "configure";

export type CreationCard = {
  type: ProjectType;
  title: string;
  benefit: string;
  description: string;
  example: string;
  href: string;
  status: RegistryStatus;
  icon: LucideIcon;
};

export const creationCards: CreationCard[] = [
  {
    type: "site",
    title: "Créer un site",
    benefit: "Transformer une idée en présence crédible.",
    description: "Génère structure, textes, CTA, SEO, preuves et preview responsive.",
    example: "Landing premium pour un coach, restaurant, service local ou agence.",
    href: "/builder/site",
    status: "available",
    icon: Globe2,
  },
  {
    type: "agent",
    title: "Créer un agent IA",
    benefit: "Avoir un assistant adapté à ton projet.",
    description: "Définis rôle, ton, contexte, permissions et prompts de test.",
    example: "Agent marketing, SEO, support, game design ou business strategy.",
    href: "/builder/agent",
    status: "available",
    icon: Bot,
  },
  {
    type: "game",
    title: "Créer un jeu",
    benefit: "Passer d'une idée à un blueprint exploitable.",
    description: "Prépare concept, gameplay loop, scripts, assets et checklist.",
    example: "Roblox obby, Minecraft add-on, île UEFN ou web game simple.",
    href: "/builder/game",
    status: "beta",
    icon: Gamepad2,
  },
];

export const componentRegistry = [
  "Hero",
  "Services",
  "Pricing",
  "Testimonials",
  "FAQ",
  "CTA",
  "Forms",
  "Product Cards",
  "Dashboard Cards",
  "Agent Cards",
  "Game Cards",
  "Integration Cards",
  "Preview Frames",
];

export const siteTemplateRegistry = [
  { id: "restaurant", name: "Restaurant premium", category: "site", score: 88, icon: Store },
  { id: "coach", name: "Coach transformation", category: "site", score: 86, icon: Target },
  { id: "service-local", name: "Service local devis", category: "site", score: 84, icon: ShieldCheck },
  { id: "ecommerce", name: "E-commerce produit", category: "site", score: 82, icon: ShoppingBag },
  { id: "agency", name: "Agence B2B", category: "site", score: 87, icon: Rocket },
  { id: "portfolio", name: "Portfolio expert", category: "site", score: 80, icon: Palette },
];

export const agentRegistry = [
  {
    id: "builder",
    name: "Agent Builder",
    role: "Création complète",
    description: "Crée une première version complète de projet.",
    status: "available" as RegistryStatus,
    badge: "Recommandé",
    exampleAction: "Créer une landing premium pour un service local.",
    icon: Sparkles,
  },
  {
    id: "seo",
    name: "Agent SEO",
    role: "Visibilité",
    description: "Optimise titres, descriptions, mots-clés, FAQ et structure.",
    status: "available" as RegistryStatus,
    badge: "Disponible",
    exampleAction: "Préparer le SEO local d'un site.",
    icon: Search,
  },
  {
    id: "design",
    name: "Agent Design",
    role: "Direction visuelle",
    description: "Améliore layout, spacing, cohérence et perception premium.",
    status: "available" as RegistryStatus,
    badge: "Disponible",
    exampleAction: "Rendre une page plus premium sans la surcharger.",
    icon: Brush,
  },
  {
    id: "copywriting",
    name: "Agent Copywriting",
    role: "Clarté et persuasion",
    description: "Réécrit les textes pour la clarté, la crédibilité et la conversion.",
    status: "available" as RegistryStatus,
    badge: "Disponible",
    exampleAction: "Améliorer un hero et ses CTA.",
    icon: PenLine,
  },
  {
    id: "conversion",
    name: "Agent Conversion",
    role: "CTA et preuves",
    description: "Analyse CTA, objections, preuves, tunnel et section contact.",
    status: "available" as RegistryStatus,
    badge: "Recommandé",
    exampleAction: "Identifier les freins qui bloquent les leads.",
    icon: Target,
  },
  {
    id: "business",
    name: "Agent Business",
    role: "Positionnement",
    description: "Améliore offre, promesse, pricing et proposition de valeur.",
    status: "available" as RegistryStatus,
    badge: "Disponible",
    exampleAction: "Clarifier une offre en une phrase.",
    icon: Brain,
  },
  {
    id: "support",
    name: "Agent Support",
    role: "Support client",
    description: "Prépare des réponses clients utiles, calmes et validables.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Préparer une réponse à un client mécontent sans l'envoyer.",
    icon: MessageCircle,
  },
  {
    id: "analytics",
    name: "Agent Analytics",
    role: "Analyse performance",
    description: "Analyse les métriques disponibles et propose la prochaine action.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Identifier pourquoi les conversions baissent.",
    icon: BarChart3,
  },
  {
    id: "automation",
    name: "Agent Automatisation",
    role: "Workflows contrôlés",
    description: "Prépare des scénarios trigger, analyse IA, validation et action.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Préparer une relance lead sans l'envoyer.",
    icon: Workflow,
  },
  {
    id: "content",
    name: "Agent Content",
    role: "Contenu et Creator",
    description: "Crée hooks, scripts, calendriers et idées de contenu.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Créer 5 idées de vidéos pour une offre.",
    icon: PenLine,
  },
  {
    id: "student",
    name: "Agent Student",
    role: "Apprentissage",
    description: "Aide à comprendre, réviser et s'entraîner sans encourager la triche.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Créer une fiche de révision et un quiz corrigé.",
    icon: Brain,
  },
  {
    id: "operations",
    name: "Agent Operations",
    role: "Management",
    description: "Transforme le chaos en tâches, priorités, relances et rituels.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Organiser la semaine et les relances importantes.",
    icon: Workflow,
  },
  {
    id: "improve",
    name: "Agent Improve",
    role: "Amélioration ciblée",
    description: "Propose des patchs concrets sans tout régénérer.",
    status: "available" as RegistryStatus,
    badge: "Disponible",
    exampleAction: "Améliorer uniquement la section FAQ.",
    icon: Zap,
  },
  {
    id: "game-design",
    name: "Agent Game Design",
    role: "Concept et gameplay",
    description: "Crée concept, gameplay loop, règles et progression.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Créer un concept Roblox tycoon.",
    icon: Gamepad2,
  },
  {
    id: "script",
    name: "Agent Script",
    role: "Snippets",
    description: "Prépare Luau, Verse, JSON ou JS selon la plateforme.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Préparer un snippet Luau de checkpoint.",
    icon: Code2,
  },
  {
    id: "assets",
    name: "Agent Assets",
    role: "Assets et prompts",
    description: "Prépare assets, prompts visuels, UI et thumbnails.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Lister les assets d'une map Minecraft.",
    icon: Palette,
  },
  {
    id: "publishing",
    name: "Agent Publishing",
    role: "Checklist",
    description: "Prépare une checklist publication sans publier automatiquement.",
    status: "beta" as RegistryStatus,
    badge: "Bêta",
    exampleAction: "Préparer une checklist UEFN.",
    icon: Trophy,
  },
];

export const gameTemplateRegistry = [
  { id: "roblox-obby", name: "Roblox Obby", platform: "Roblox", type: "Obby", icon: Gamepad2 },
  { id: "roblox-tycoon", name: "Roblox Tycoon", platform: "Roblox", type: "Tycoon", icon: Trophy },
  { id: "minecraft-addon", name: "Minecraft Add-on", platform: "Minecraft", type: "Add-on", icon: Code2 },
  { id: "uefn-island", name: "Fortnite UEFN Island", platform: "Fortnite / UEFN", type: "Island", icon: Target },
  { id: "web-quiz", name: "Web Quiz Game", platform: "Web game", type: "Quiz", icon: Brain },
  { id: "web-clicker", name: "Web Clicker Game", platform: "Web game", type: "Idle", icon: Zap },
];

export type IntegrationRegistryItem = {
  id: string;
  name: string;
  category:
    | "Business"
    | "Marketing"
    | "Data"
    | "Automatisation"
    | "Dev"
    | "Communication"
    | "IA"
    | "Domaines"
    | "Gaming";
  description: string;
  status: RegistryStatus;
  permissions: string[];
  icon: LucideIcon;
  logo?: {
    initials: string;
    accent: string;
    from: string;
    to: string;
    glyph:
      | "payments"
      | "chart"
      | "webhook"
      | "message"
      | "ai"
      | "code"
      | "game"
      | "workflow"
      | "domain"
      | "store"
      | "ads"
      | "sheet"
      | "cloud"
      | "voice"
      | "asset";
  };
  productUse?: string;
  setupSignals?: string[];
};

export const integrationRegistry: IntegrationRegistryItem[] = [
  {
    id: "stripe",
    name: "Stripe",
    category: "Business",
    description: "Paiements, abonnements et packs de crédits via backend sécurisé.",
    status: "configure",
    permissions: ["Créer checkout", "Lire statut paiement"],
    icon: CreditCard,
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    category: "Data",
    description: "Mesure visites, sources, conversions et clics CTA.",
    status: "development",
    permissions: ["Lire métriques", "Importer événements"],
    icon: BarChart3,
  },
  {
    id: "webhooks",
    name: "Webhooks",
    category: "Automatisation",
    description: "Prépare des événements sortants contrôlés par validation utilisateur.",
    status: "development",
    permissions: ["Envoyer événement", "Tester endpoint"],
    icon: Webhook,
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    category: "Communication",
    description: "Préparer la prise de contact et les réponses, sans envoyer automatiquement.",
    status: "soon",
    permissions: ["Préparer message", "Validation requise"],
    icon: MessageCircle,
  },
  {
    id: "gemini",
    name: "Gemini adapter",
    category: "IA",
    description: "Adapter mock-safe pour génération structurée; clé backend requise pour réel.",
    status: "development",
    permissions: ["Générer JSON", "Valider sortie"],
    icon: Sparkles,
  },
  {
    id: "github-game",
    name: "GitHub game repo",
    category: "Gaming",
    description: "Préparer un export repo pour jeux web, scripts et checklists.",
    status: "soon",
    permissions: ["Préparer export", "Aucune publication auto"],
    icon: Code2,
  },
  {
    id: "roblox",
    name: "Roblox",
    category: "Gaming",
    description: "Blueprint, Luau snippets et checklist Roblox Studio. Pas de publication automatique.",
    status: "beta",
    permissions: ["Préparer snippets", "Checklist Studio"],
    icon: Gamepad2,
  },
  {
    id: "make",
    name: "Make",
    category: "Automatisation",
    description: "Scénarios d'automatisation à connecter plus tard via webhooks.",
    status: "soon",
    permissions: ["Déclencher scénario", "Validation requise"],
    icon: Workflow,
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "Domaines",
    description: "Préparation domaines, DNS et SSL selon hébergeur futur.",
    status: "soon",
    permissions: ["Lire DNS", "Préparer instructions"],
    icon: Cable,
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "Business",
    description: "Catalogue, commandes et storefront pour les futurs projets e-commerce.",
    status: "soon",
    permissions: ["Lire catalogue", "Préparer produits", "Validation requise"],
    icon: ShoppingBag,
    logo: { initials: "S", accent: "#22c55e", from: "#092215", to: "#166534", glyph: "store" },
    productUse: "Préparer les boutiques et relier les projets business à un catalogue.",
    setupSignals: ["OAuth futur", "Scope catalogue", "Pas de checkout forcé"],
  },
  {
    id: "paypal",
    name: "PayPal",
    category: "Business",
    description: "Paiements alternatifs pour élargir les options de checkout plus tard.",
    status: "soon",
    permissions: ["Créer paiement", "Lire statut", "Validation requise"],
    icon: CreditCard,
    logo: { initials: "P", accent: "#60a5fa", from: "#082f49", to: "#1d4ed8", glyph: "payments" },
    productUse: "Offrir un moyen de paiement complémentaire sans mélanger les secrets.",
    setupSignals: ["Configuration serveur", "Sandbox d'abord", "Webhook requis"],
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    category: "Business",
    description: "Connexion prévue pour boutiques WordPress, produits et commandes.",
    status: "soon",
    permissions: ["Lire produits", "Lire commandes", "Synchronisation contrôlée"],
    icon: Store,
    logo: { initials: "W", accent: "#a855f7", from: "#2e1065", to: "#7e22ce", glyph: "store" },
    productUse: "Relier les projets e-commerce existants aux dashboards Pixelrises.",
    setupSignals: ["Clés chiffrées plus tard", "Lecture seule d'abord", "Action validée"],
  },
  {
    id: "google-sheets",
    name: "Google Sheets",
    category: "Data",
    description: "Synchronisation de leads, exports de rapports et listes opérationnelles.",
    status: "configure",
    permissions: ["Lire feuille", "Ajouter ligne", "Exporter rapport"],
    icon: BarChart3,
    logo: { initials: "GS", accent: "#22c55e", from: "#052e16", to: "#15803d", glyph: "sheet" },
    productUse: "Exporter les leads et les suivis business vers des feuilles simples.",
    setupSignals: ["OAuth futur", "Scope minimal", "Journal d'audit"],
  },
  {
    id: "google-drive",
    name: "Google Drive",
    category: "Data",
    description: "Stockage futur de documents, exports, briefs et assets de projet.",
    status: "soon",
    permissions: ["Créer dossier", "Déposer export", "Lire fichier validé"],
    icon: Globe2,
    logo: { initials: "GD", accent: "#38bdf8", from: "#082f49", to: "#0f766e", glyph: "cloud" },
    productUse: "Préparer l'espace projet avec exports, documents et assets.",
    setupSignals: ["Accès limité", "Validation fichier", "Pas de scan complet"],
  },
  {
    id: "search-console",
    name: "Search Console",
    category: "Data",
    description: "Suivi SEO, pages indexées, requêtes et opportunités de visibilité.",
    status: "soon",
    permissions: ["Lire requêtes", "Lire pages", "Rapport SEO"],
    icon: Search,
    logo: { initials: "SC", accent: "#3b82f6", from: "#0f172a", to: "#1d4ed8", glyph: "chart" },
    productUse: "Rendre les recommandations SEO plus réelles et mesurables.",
    setupSignals: ["Lecture seule", "Propriété vérifiée", "Rapport agrégé"],
  },
  {
    id: "meta-ads",
    name: "Meta Ads",
    category: "Marketing",
    description: "Préparation future des audiences, pixels et lectures de performance.",
    status: "soon",
    permissions: ["Lire campagnes", "Préparer audience", "Validation requise"],
    icon: Target,
    logo: { initials: "M", accent: "#3b82f6", from: "#0c1b3a", to: "#2563eb", glyph: "ads" },
    productUse: "Relier conversion, audience et recommandations business.",
    setupSignals: ["Pas de campagne auto", "Lecture d'abord", "Consentement requis"],
  },
  {
    id: "google-ads",
    name: "Google Ads",
    category: "Marketing",
    description: "Planification et audit futur des campagnes sans dépense automatique.",
    status: "soon",
    permissions: ["Lire campagne", "Préparer mots-clés", "Validation requise"],
    icon: Target,
    logo: { initials: "AD", accent: "#facc15", from: "#1f1a06", to: "#ca8a04", glyph: "ads" },
    productUse: "Transformer les pages générées en plans d'acquisition mesurables.",
    setupSignals: ["Jamais de dépense auto", "Validation humaine", "Scopes limités"],
  },
  {
    id: "tiktok",
    name: "TikTok",
    category: "Marketing",
    description: "Idées de contenus, suivi créateur et scénarios pour Creator AI.",
    status: "beta",
    permissions: ["Préparer script", "Lire tendances validées", "Plan contenu"],
    icon: Sparkles,
    logo: { initials: "TT", accent: "#ec4899", from: "#210617", to: "#0f172a", glyph: "ads" },
    productUse: "Aider Creator AI à préparer des contenus sans promettre la viralité.",
    setupSignals: ["Pas de publication auto", "Tendance vérifiée", "Validation créateur"],
  },
  {
    id: "instagram",
    name: "Instagram",
    category: "Marketing",
    description: "Calendrier, posts, hooks et assets pour les lancements de projets.",
    status: "beta",
    permissions: ["Préparer post", "Planifier idée", "Validation requise"],
    icon: Palette,
    logo: { initials: "IG", accent: "#f472b6", from: "#4a044e", to: "#be123c", glyph: "ads" },
    productUse: "Créer une continuité entre site, offre et contenu social.",
    setupSignals: ["Pas d'envoi auto", "Assets validés", "Données limitées"],
  },
  {
    id: "youtube",
    name: "YouTube",
    category: "Marketing",
    description: "Scripts, titres, descriptions et recherche de formats vidéo.",
    status: "beta",
    permissions: ["Préparer script", "Optimiser titre", "Checklist vidéo"],
    icon: Rocket,
    logo: { initials: "YT", accent: "#ef4444", from: "#2a0606", to: "#991b1b", glyph: "ads" },
    productUse: "Brancher Creator AI sur une logique de contenu actionnable.",
    setupSignals: ["Pas d'upload auto", "Validation humaine", "Conseils non garantis"],
  },
  {
    id: "zapier",
    name: "Zapier",
    category: "Automatisation",
    description: "Pont futur entre formulaires, CRM, emails et notifications.",
    status: "soon",
    permissions: ["Déclencher zap", "Lire statut", "Validation requise"],
    icon: Zap,
    logo: { initials: "Z", accent: "#fb923c", from: "#2c1204", to: "#c2410c", glyph: "workflow" },
    productUse: "Donner aux débutants des automatisations rapides et compréhensibles.",
    setupSignals: ["Connexion explicite", "Journal d'exécution", "Rollback manuel"],
  },
  {
    id: "n8n",
    name: "n8n",
    category: "Automatisation",
    description: "Automatisations avancées auto-hébergées ou serveur pour utilisateurs experts.",
    status: "soon",
    permissions: ["Déclencher workflow", "Lire statut", "Payload filtré"],
    icon: Workflow,
    logo: { initials: "n8n", accent: "#f43f5e", from: "#27050d", to: "#be123c", glyph: "workflow" },
    productUse: "Préparer une voie avancée pour entreprises et power users.",
    setupSignals: ["Endpoint serveur", "Scopes limités", "Validation humaine"],
  },
  {
    id: "gmail",
    name: "Gmail",
    category: "Communication",
    description: "Préparer emails, relances, réponses clients et notifications.",
    status: "soon",
    permissions: ["Préparer email", "Brouillon validé", "Lire réponse"],
    icon: MessageCircle,
    logo: { initials: "G", accent: "#ef4444", from: "#2b0707", to: "#b91c1c", glyph: "message" },
    productUse: "Créer des relances utiles sans envoyer à la place de l'utilisateur.",
    setupSignals: ["Brouillon d'abord", "Validation humaine", "Scopes minimaux"],
  },
  {
    id: "telegram",
    name: "Telegram",
    category: "Communication",
    description: "Notifications, bot support et alertes projet pour équipes légères.",
    status: "soon",
    permissions: ["Envoyer notification", "Lire commande", "Validation requise"],
    icon: MessageCircle,
    logo: { initials: "TG", accent: "#38bdf8", from: "#082f49", to: "#0369a1", glyph: "message" },
    productUse: "Recevoir des alertes sur leads, bugs et actions Product Lab.",
    setupSignals: ["Configuration serveur", "Aucun secret visible", "Salon validé"],
  },
  {
    id: "slack",
    name: "Slack",
    category: "Communication",
    description: "Alertes équipe, suivi Product Lab, leads et statuts de génération.",
    status: "soon",
    permissions: ["Envoyer alerte", "Lire canal", "Validation requise"],
    icon: MessageCircle,
    logo: { initials: "SL", accent: "#a855f7", from: "#240a35", to: "#7e22ce", glyph: "message" },
    productUse: "Centraliser les notifications de plateforme et les décisions d'équipe.",
    setupSignals: ["Webhook serveur", "Canal sélectionné", "Logs filtrés"],
  },
  {
    id: "vercel-ai-gateway",
    name: "Moteur IA Pixelrises",
    category: "IA",
    description: "Point d'entrée serveur pour sélectionner le mode IA adapté à chaque tâche.",
    status: "configure",
    permissions: ["Choisir le mode IA", "Secours sécurisé", "Historique filtré"],
    icon: Sparkles,
    logo: { initials: "AI", accent: "#f5c542", from: "#211a05", to: "#856404", glyph: "ai" },
    productUse: "Faire fonctionner le Multi-IA sans exposer les clés côté navigateur.",
    setupSignals: ["Clé serveur uniquement", "Logs filtrés", "Secours contrôlé"],
  },
  {
    id: "openai-gateway",
    name: "IA Stratégie Pixelrises",
    category: "IA",
    description: "Stratégie, copywriting, conversion, SEO et positionnement.",
    status: "configure",
    permissions: ["Générer stratégie", "Optimiser CTA", "Normaliser sortie"],
    icon: Brain,
    logo: { initials: "OA", accent: "#10b981", from: "#052e2b", to: "#065f46", glyph: "ai" },
    productUse: "Confier les tâches business et conversion au mode le plus adapté.",
    setupSignals: ["Serveur sécurisé", "Aucune clé visible", "Contrôle qualité obligatoire"],
  },
  {
    id: "claude-gateway",
    name: "IA Qualité Pixelrises",
    category: "IA",
    description: "Analyse complexe, structure, cohérence et validation qualité.",
    status: "configure",
    permissions: ["Analyser logique", "Quality gate", "Structurer plan"],
    icon: Brain,
    logo: { initials: "CL", accent: "#f97316", from: "#2d1304", to: "#9a3412", glyph: "ai" },
    productUse: "Sécuriser les décisions IA et les sorties structurées importantes.",
    setupSignals: ["Serveur sécurisé", "Validation sortie", "Mode secours"],
  },
  {
    id: "gemini-gateway",
    name: "IA Assistant Pixelrises",
    category: "IA",
    description: "Suggestions, normalisation, enrichissement de brief et fallback général.",
    status: "configure",
    permissions: ["Normaliser JSON", "Enrichir brief", "Secours contrôlé"],
    icon: Sparkles,
    logo: { initials: "G", accent: "#60a5fa", from: "#091735", to: "#2563eb", glyph: "ai" },
    productUse: "Stabiliser les réponses et garder une cohérence globale.",
    setupSignals: ["Serveur sécurisé", "Normalisation", "Aucune clé visible"],
  },
  {
    id: "mistral-gateway",
    name: "IA Rapide Pixelrises",
    category: "IA",
    description: "Classification rapide, résumé, tags et fallback économique.",
    status: "configure",
    permissions: ["Classifier", "Résumer", "Pré-router"],
    icon: Zap,
    logo: { initials: "MI", accent: "#f59e0b", from: "#2b1604", to: "#92400e", glyph: "ai" },
    productUse: "Réduire les coûts sur les tâches rapides sans perdre la qualité.",
    setupSignals: ["Serveur sécurisé", "Coût contrôlé", "Mode secours"],
  },
  {
    id: "image-generation",
    name: "Image generation",
    category: "IA",
    description: "Préparation des visuels de templates, assets jeux et moodboards.",
    status: "beta",
    permissions: ["Générer image", "Sauvegarder asset", "Validation humaine"],
    icon: Palette,
    logo: { initials: "IMG", accent: "#ec4899", from: "#330a22", to: "#be185d", glyph: "asset" },
    productUse: "Rendre les projets moins génériques avec des directions visuelles fortes.",
    setupSignals: ["Coût contrôlé", "Droits à vérifier", "Pas d'asset sensible"],
  },
  {
    id: "voice-generation",
    name: "Voice generation",
    category: "IA",
    description: "Voix off, scripts audio et futures expériences créateur.",
    status: "soon",
    permissions: ["Préparer voix", "Exporter audio", "Validation requise"],
    icon: MessageCircle,
    logo: { initials: "VO", accent: "#06b6d4", from: "#042f35", to: "#0e7490", glyph: "voice" },
    productUse: "Préparer la couche contenu sans lancer V3 maintenant.",
    setupSignals: ["Consentement voix", "Pas de clonage non autorisé", "Usage log"],
  },
  {
    id: "github",
    name: "GitHub",
    category: "Dev",
    description: "Issues, PR, exports projet, suivi Product Lab et repositories.",
    status: "configure",
    permissions: ["Créer issue", "Créer PR", "Lire workflow"],
    icon: Code2,
    logo: { initials: "GH", accent: "#f8fafc", from: "#111827", to: "#020617", glyph: "code" },
    productUse: "Transformer les décisions admin en PR contrôlées et auditables.",
    setupSignals: ["Permissions repo", "Pas de merge auto", "CI obligatoire"],
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Dev",
    description: "Déploiements, previews, domaines et monitoring front-end.",
    status: "configure",
    permissions: ["Lire déploiements", "Créer preview", "Lire logs"],
    icon: Rocket,
    logo: { initials: "V", accent: "#ffffff", from: "#101010", to: "#262626", glyph: "cloud" },
    productUse: "Préparer la publication sûre sans déployer automatiquement.",
    setupSignals: ["Preview d'abord", "Pas de prod auto", "Logs filtrés"],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Dev",
    description: "Base applicative, stockage, fonctions serveur et journaux non sensibles.",
    status: "configure",
    permissions: ["Lire projets", "Sauvegarder données", "Edge Functions"],
    icon: ShieldCheck,
    logo: { initials: "SB", accent: "#22c55e", from: "#052e16", to: "#047857", glyph: "cloud" },
    productUse: "Base réelle pour projets, générations, Product Lab et admin.",
    setupSignals: ["Accès contrôlé", "Configuration serveur", "Journaux sans clés"],
  },
  {
    id: "firebase",
    name: "Firebase",
    category: "Dev",
    description: "Option future pour notifications, analytics ou prototypes mobiles.",
    status: "soon",
    permissions: ["Lire projet", "Notifications", "Configuration future"],
    icon: Zap,
    logo: { initials: "FB", accent: "#f59e0b", from: "#2b1603", to: "#b45309", glyph: "cloud" },
    productUse: "Garder une option d'écosystème mobile sans disperser la V2.",
    setupSignals: ["Plus tard", "Pas de double auth", "Validation architecture"],
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "Dev",
    description: "Déploiement alternatif et previews pour projets web simples.",
    status: "soon",
    permissions: ["Préparer déploiement", "Lire preview", "Validation requise"],
    icon: Rocket,
    logo: { initials: "N", accent: "#14b8a6", from: "#042f2e", to: "#0f766e", glyph: "cloud" },
    productUse: "Prévoir des exports web flexibles pour certains clients.",
    setupSignals: ["Pas de déploiement auto", "Preview seulement", "Env séparé"],
  },
  {
    id: "minecraft",
    name: "Minecraft",
    category: "Gaming",
    description: "Maps, add-ons, behavior packs, resource packs et JSON de base.",
    status: "soon",
    permissions: ["Préparer JSON", "Lister assets", "Checklist Bedrock"],
    icon: Gamepad2,
    logo: { initials: "MC", accent: "#22c55e", from: "#11320c", to: "#365314", glyph: "game" },
    productUse: "Structurer les idées Minecraft en packs et checklists réutilisables.",
    setupSignals: ["Compatibilité à vérifier", "Marketplace plus tard", "Pas d'upload auto"],
  },
  {
    id: "fortnite-uefn",
    name: "Fortnite / UEFN",
    category: "Gaming",
    description: "Concept d'île, règles, level design, Verse snippets et checklist UEFN.",
    status: "soon",
    permissions: ["Préparer Verse", "Checklist UEFN", "Plan de publication"],
    icon: Gamepad2,
    logo: { initials: "UE", accent: "#38bdf8", from: "#0b1228", to: "#1d4ed8", glyph: "game" },
    productUse: "Préparer des blueprints de jeux ambitieux sans fausse promesse.",
    setupSignals: ["Pas de publication auto", "Verse explicatif", "Règles plateforme"],
  },
  {
    id: "asset-library",
    name: "Asset library",
    category: "Gaming",
    description: "Bibliothèque future d'assets, prompts visuels et packs de production.",
    status: "beta",
    permissions: ["Lister assets", "Préparer prompts", "Exporter pack"],
    icon: Palette,
    logo: { initials: "AS", accent: "#eab308", from: "#1f1a05", to: "#854d0e", glyph: "asset" },
    productUse: "Donner au Game Builder et aux templates une direction visuelle plus forte.",
    setupSignals: ["Droits assets", "Tags propres", "Validation humaine"],
  },
  {
    id: "vercel-domains",
    name: "Vercel Domains",
    category: "Domaines",
    description: "Sous-domaines, domaines personnalisés et previews de publication.",
    status: "soon",
    permissions: ["Préparer domaine", "Lire statut DNS", "Preview"],
    icon: Globe2,
    logo: { initials: "VD", accent: "#ffffff", from: "#080808", to: "#262626", glyph: "domain" },
    productUse: "Préparer une expérience publier/exporter simple et contrôlée.",
    setupSignals: ["Pas de prod auto", "Statut DNS", "Validation humaine"],
  },
  {
    id: "custom-domain",
    name: "Custom domain",
    category: "Domaines",
    description: "Assistant de configuration pour domaines personnalisés et DNS.",
    status: "configure",
    permissions: ["Préparer DNS", "Vérifier statut", "Guide client"],
    icon: Globe2,
    logo: { initials: "CD", accent: "#f5c542", from: "#1f1a05", to: "#7c5f09", glyph: "domain" },
    productUse: "Aider les utilisateurs à rendre leur projet crédible avec un vrai domaine.",
    setupSignals: ["Guide uniquement", "Vérification non destructive", "Historique admin"],
  },
  {
    id: "squarespace",
    name: "Squarespace",
    category: "Domaines",
    description: "Préparation future pour domaines et sites existants côté clients.",
    status: "soon",
    permissions: ["Préparer domaine", "Lire statut", "Guide migration"],
    icon: Globe2,
    logo: { initials: "SQ", accent: "#cbd5e1", from: "#111827", to: "#334155", glyph: "domain" },
    productUse: "Accompagner les clients qui possèdent déjà un domaine ailleurs.",
    setupSignals: ["Guide manuel", "Pas de migration auto", "Validation client"],
  },
];

export const analyticsMock = {
  visits: 1248,
  pageViews: 3810,
  ctaClicks: 138,
  leads: 52,
  conversionRate: 4.2,
  sevenDayProgress: 18,
  thirtyDayProgress: 31,
  topPages: ["/", "/builder/site", "/templates", "/integrations"],
};
