// Auto-generated by scripts/build-ai-builder-inspiration-index.mjs.
// Distilled AI builder and product UX signals only. Do not copy source text, screenshots, names or images into generated client sites.

export type AiBuilderInspiration = {
  sourceFamily: string;
  sourceType: string;
  keywordSignals: readonly string[];
  patternSignals: readonly string[];
  uxSignals: readonly string[];
  layoutSignals: readonly string[];
  visualSignals: readonly string[];
  useCaseSignals: readonly string[];
  safeUse: string;
};

export type AiBuilderCuratedPattern = {
  family: string;
  principle: string;
  bestFor: readonly string[];
  layoutSignals: readonly string[];
  variationSignals: readonly string[];
};

export const AI_BUILDER_INSPIRATIONS = [
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "1code",
      "claude",
      "code",
      "codex",
      "one",
      "app",
      "coding",
      "agent",
      "client",
      "switch",
      "between",
      "take",
      "best",
      "each",
      "ship",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "preview_canvas",
      "agent_plan",
      "workflow_pipeline",
      "creative_generation"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency",
      "fast_preview_iteration"
    ],
    "layoutSignals": [
      "split_chat_preview",
      "agent_timeline",
      "bento_tool_cards"
    ],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "infrastructure",
      "building",
      "blocks",
      "agentic",
      "internet",
      "ship",
      "powered",
      "products",
      "faster",
      "agents",
      "sdk",
      "developer",
      "tools",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "preview_canvas",
      "agent_plan",
      "workflow_pipeline",
      "tool_command_surface",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency",
      "fast_preview_iteration"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "developer_or_saas_product",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "agent",
      "registry",
      "developer",
      "tools",
      "agentic",
      "internet",
      "ship",
      "powered",
      "products",
      "faster",
      "browse",
      "discover",
      "ready",
      "use",
      "configs",
      "claude",
      "managed",
      "agents",
      "copy",
      "react"
    ],
    "patternSignals": [
      "preview_canvas",
      "agent_plan",
      "workflow_pipeline",
      "tool_command_surface",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency",
      "fast_preview_iteration"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "developer_or_saas_product",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "agent",
      "plan",
      "animated",
      "task",
      "including",
      "subtasks",
      "assigned",
      "mcp",
      "servers",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "motion_first_micro_interactions",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "gen",
      "image",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "prompt",
      "box",
      "chat",
      "input",
      "search",
      "think",
      "thinking",
      "canvas",
      "audio",
      "recording",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "prompt_composer",
      "conversation_builder",
      "preview_canvas",
      "agent_plan",
      "workflow_pipeline",
      "knowledge_assistant",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "guided_prompt_refinement",
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "split_chat_preview",
      "command_dock_bottom",
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "dark_glass_command_ui",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "ali",
      "imam",
      "browse",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "animated",
      "chat",
      "interface",
      "glass",
      "morphism",
      "design",
      "smart",
      "command",
      "features",
      "react",
      "framer",
      "motion",
      "smooth",
      "animations",
      "professional",
      "interactions",
      "agent",
      "workflow",
      "pixelrises",
      "pack"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan",
      "workflow_pipeline",
      "tool_command_surface",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "split_chat_preview",
      "command_dock_bottom",
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "dark_glass_command_ui",
      "motion_first_micro_interactions",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "chatgpt",
      "prompt",
      "input",
      "this",
      "complete",
      "replica",
      "some",
      "may",
      "call",
      "chat",
      "box",
      "promptbox",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "prompt_composer",
      "conversation_builder",
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "guided_prompt_refinement",
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "split_chat_preview",
      "command_dock_bottom",
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "dark_glass_command_ui",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "cursor",
      "agent",
      "that",
      "generates",
      "multiple",
      "styles",
      "every",
      "request",
      "compare",
      "variations",
      "pick",
      "best",
      "one",
      "available",
      "mcp",
      "server",
      "windsurf",
      "code",
      "web",
      "interface"
    ],
    "patternSignals": [
      "preview_canvas",
      "agent_plan",
      "workflow_pipeline",
      "creative_generation"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency",
      "fast_preview_iteration",
      "trust_and_error_surface"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards"
    ],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "hossain",
      "jahed",
      "browse",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "isaiah",
      "browse",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "jatin",
      "yadav",
      "browse",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "kokonut",
      "browse",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "chat",
      "design",
      "agent",
      "workflow",
      "pixelrises",
      "pack",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "preview_canvas",
      "agent_plan",
      "workflow_pipeline",
      "creative_generation",
      "marketplace_registry"
    ],
    "uxSignals": [
      "non_destructive_options",
      "visible_progress_steps",
      "tool_transparency",
      "fast_preview_iteration"
    ],
    "layoutSignals": [
      "split_chat_preview",
      "agent_timeline",
      "bento_tool_cards",
      "marketplace_grid"
    ],
    "visualSignals": [
      "dark_glass_command_ui",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "golang",
      "terminal",
      "chat",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "001",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan",
      "tool_command_surface"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "split_chat_preview",
      "command_dock_bottom"
    ],
    "visualSignals": [
      "dark_glass_command_ui",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "docs",
      "assistant",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "002",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan",
      "knowledge_assistant"
    ],
    "uxSignals": [
      "guided_prompt_refinement",
      "tool_transparency"
    ],
    "layoutSignals": [
      "docs_search_layout"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "support_or_documentation",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "lead",
      "deal",
      "pipeline",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "003",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "workflow_pipeline",
      "form_flow",
      "crm_sales"
    ],
    "uxSignals": [
      "visible_progress_steps",
      "tool_transparency"
    ],
    "layoutSignals": [
      "agent_timeline",
      "form_to_result_flow"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "lead_generation_and_sales",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "fill",
      "form",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "004",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "form_flow"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "form_to_result_flow"
    ],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "booking_or_contact_flow",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "chat",
      "app",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "005",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "split_chat_preview"
    ],
    "visualSignals": [
      "dark_glass_command_ui",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "support",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "006",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan",
      "knowledge_assistant"
    ],
    "uxSignals": [
      "guided_prompt_refinement",
      "tool_transparency",
      "human_handoff"
    ],
    "layoutSignals": [
      "docs_search_layout"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "support_or_documentation",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "docs",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "007",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan",
      "knowledge_assistant"
    ],
    "uxSignals": [
      "guided_prompt_refinement",
      "tool_transparency"
    ],
    "layoutSignals": [
      "docs_search_layout"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "support_or_documentation",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "app",
      "lead",
      "research",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "008",
      "meta",
      "json"
    ],
    "patternSignals": [
      "prompt_composer",
      "agent_plan",
      "workflow_pipeline",
      "knowledge_assistant",
      "form_flow",
      "crm_sales"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "command_dock_bottom",
      "form_to_result_flow"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "lead_generation_and_sales",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "security",
      "auditor",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "009",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "data_dashboard",
      "security_trust"
    ],
    "uxSignals": [
      "tool_transparency",
      "trust_and_error_surface"
    ],
    "layoutSignals": [
      "dashboard_panels"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "structured_data_visuals"
    ],
    "useCaseSignals": [
      "trust_security_or_audit",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "web",
      "scraper",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "010",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "data_dashboard"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "dashboard_panels"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "structured_data_visuals"
    ],
    "useCaseSignals": [
      "data_or_dashboard_experience",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "app",
      "support",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "011",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan",
      "knowledge_assistant"
    ],
    "uxSignals": [
      "guided_prompt_refinement",
      "tool_transparency",
      "human_handoff"
    ],
    "layoutSignals": [
      "docs_search_layout"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "support_or_documentation",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "app",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "012",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "lead",
      "research",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "013",
      "meta",
      "json"
    ],
    "patternSignals": [
      "prompt_composer",
      "agent_plan",
      "workflow_pipeline",
      "knowledge_assistant",
      "form_flow",
      "crm_sales"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "command_dock_bottom",
      "form_to_result_flow"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "lead_generation_and_sales",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "github",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "014",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "deep",
      "researcher",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "015",
      "meta",
      "json"
    ],
    "patternSignals": [
      "prompt_composer",
      "agent_plan",
      "knowledge_assistant"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "command_dock_bottom"
    ],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "email",
      "operations",
      "copilot",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "016",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "data",
      "analyst",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "017",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "data_dashboard"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "data_or_dashboard_experience",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "proposal",
      "builder",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "018",
      "meta",
      "json"
    ],
    "patternSignals": [
      "preview_canvas",
      "agent_plan"
    ],
    "uxSignals": [
      "tool_transparency",
      "fast_preview_iteration"
    ],
    "layoutSignals": [
      "split_chat_preview"
    ],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "api",
      "designer",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "019",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "tool_command_surface"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "developer_or_saas_product",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "cold",
      "outreach",
      "personalizer",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "020",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "what",
      "did",
      "ship",
      "this",
      "week",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "021",
      "meta",
      "json"
    ],
    "patternSignals": [
      "preview_canvas",
      "agent_plan"
    ],
    "uxSignals": [
      "tool_transparency",
      "fast_preview_iteration"
    ],
    "layoutSignals": [],
    "visualSignals": [
      "clean_saas_panels",
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "web",
      "scraper",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "022",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "data_dashboard"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "dashboard_panels"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "structured_data_visuals"
    ],
    "useCaseSignals": [
      "data_or_dashboard_experience",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "docs",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "agents",
      "001",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan",
      "knowledge_assistant",
      "marketplace_registry"
    ],
    "uxSignals": [
      "guided_prompt_refinement",
      "tool_transparency"
    ],
    "layoutSignals": [
      "docs_search_layout",
      "marketplace_grid"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "support_or_documentation",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "app",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "agents",
      "002",
      "meta",
      "json"
    ],
    "patternSignals": [
      "agent_plan",
      "marketplace_registry"
    ],
    "uxSignals": [
      "tool_transparency"
    ],
    "layoutSignals": [
      "marketplace_grid"
    ],
    "visualSignals": [
      "premium_tool_cards"
    ],
    "useCaseSignals": [
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  },
  {
    "sourceFamily": "21st.dev",
    "sourceType": "component_or_agent_or_workflow",
    "keywordSignals": [
      "docs",
      "agent",
      "importe",
      "automatiquement",
      "depuis",
      "super",
      "pack",
      "pixelrises",
      "agents",
      "003",
      "meta",
      "json"
    ],
    "patternSignals": [
      "conversation_builder",
      "agent_plan",
      "knowledge_assistant",
      "marketplace_registry"
    ],
    "uxSignals": [
      "guided_prompt_refinement",
      "tool_transparency"
    ],
    "layoutSignals": [
      "docs_search_layout",
      "marketplace_grid"
    ],
    "visualSignals": [
      "premium_tool_cards",
      "human_assistant_surface"
    ],
    "useCaseSignals": [
      "support_or_documentation",
      "ai_assisted_builder_experience",
      "visual_component_system"
    ],
    "safeUse": "Internal distilled inspiration only. Do not copy title, text, screenshot, image, URL, brand name or implementation."
  }
] as const satisfies readonly AiBuilderInspiration[];

export const AI_BUILDER_CURATED_PATTERNS = [
  {
    "family": "conversation_to_preview_builder",
    "principle": "A simple input drives a visible result canvas, then the user iterates without losing the brief.",
    "bestFor": [
      "ai_builder",
      "service_business",
      "creative_business",
      "local_business"
    ],
    "layoutSignals": [
      "split_chat_preview",
      "preview_only_canvas",
      "sticky_prompt_dock",
      "result_actions_after_preview"
    ],
    "variationSignals": [
      "short guided questions",
      "preview-first feedback",
      "non-destructive suggestions",
      "retry keeps existing result"
    ]
  },
  {
    "family": "structured_component_generation",
    "principle": "Every section has a clear role, reusable component anatomy and a strong visual hierarchy.",
    "bestFor": [
      "saas-tech",
      "professional-services",
      "education-training",
      "ecommerce"
    ],
    "layoutSignals": [
      "section inventory",
      "component families",
      "clean cards",
      "clear empty states"
    ],
    "variationSignals": [
      "different hero architecture",
      "different proof module",
      "different CTA rhythm",
      "different card density"
    ]
  },
  {
    "family": "premium_pattern_library",
    "principle": "Use modern product patterns as inspiration for rhythm and interaction, never as copied content.",
    "bestFor": [
      "premium-business",
      "creative-services",
      "personal-brand",
      "agency"
    ],
    "layoutSignals": [
      "bento feature story",
      "agent timeline",
      "command dock",
      "gallery proof rail"
    ],
    "variationSignals": [
      "asymmetric cards",
      "editorial media",
      "soft glass panels",
      "motion-led reveals"
    ]
  },
  {
    "family": "screen_clarity_pattern",
    "principle": "Make each screen readable in seconds with strong spacing, simple navigation and obvious next actions.",
    "bestFor": [
      "mobile-first",
      "booking",
      "dashboard",
      "consumer_service"
    ],
    "layoutSignals": [
      "mobile first stack",
      "single dominant CTA",
      "clean list/detail flow",
      "short labels"
    ],
    "variationSignals": [
      "compact mobile cards",
      "large touch targets",
      "clear form states",
      "no crowded grids"
    ]
  },
  {
    "family": "conversion_command_center",
    "principle": "The page behaves like a business system: proof, objections, action and contact are never buried.",
    "bestFor": [
      "local-services",
      "car-rental",
      "coach",
      "restaurant",
      "real-estate"
    ],
    "layoutSignals": [
      "hero action strip",
      "proof stack",
      "offer comparison",
      "contact module"
    ],
    "variationSignals": [
      "proof first",
      "process first",
      "offer first",
      "local trust first"
    ]
  },
  {
    "family": "agentic_workflow_story",
    "principle": "When the business is technical or automated, show steps, tools and outcomes in a visual workflow.",
    "bestFor": [
      "saas-tech",
      "automation",
      "consulting",
      "api",
      "data"
    ],
    "layoutSignals": [
      "workflow timeline",
      "tool cards",
      "status chips",
      "before after panels"
    ],
    "variationSignals": [
      "linear process",
      "radial system map",
      "dashboard blocks",
      "technical explainer"
    ]
  }
] as const satisfies readonly AiBuilderCuratedPattern[];
