// Distilled TemplateMo signals only: do not copy template HTML, CSS, texts, names or images into generated client sites.
export type TemplateMoInspiration = {
  sourceTemplate: string;
  title: string;
  likelyNiches: readonly string[];
  pageCount: number;
  htmlFiles: readonly string[];
  componentSignals: readonly string[];
  sectionPatterns: readonly string[];
  visualSignals: readonly string[];
  colorSignals: readonly string[];
  animationSignals: readonly string[];
  layoutSignals: readonly string[];
  keywordSignals: readonly string[];
  assetSignals: readonly string[];
  licenseNote: string;
};

export const TEMPLATEMO_TEMPLATE_INSPIRATIONS = [
  {
    "sourceTemplate": "templatemo_612_parallax_starter",
    "title": "Parallax Starter - Free HTML CSS Template",
    "likelyNiches": [
      "saas-tech",
      "creative-services",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "contact/lead form",
      "dashboard/data cards"
    ],
    "sectionPatterns": [
      "nav",
      "nav container",
      "parallax section",
      "parallax bg",
      "parallax overlay",
      "section content",
      "about cols",
      "about col",
      "about thumb",
      "thumb top left",
      "about thumb wide",
      "overlay dark",
      "services grid",
      "service item",
      "service icon",
      "content block",
      "stats row",
      "stat item",
      "overlay medium",
      "contact form wrap",
      "form row",
      "footer"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "dark premium surface, strong contrast, cinematic mood",
      "portfolio gallery, editorial images, case-study rhythm",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#ffffff",
      "#111",
      "rgba(255, 255, 255, 0.9)",
      "rgba(255, 255, 255, 0.7)",
      "rgba(255, 255, 255, 0.4)",
      "rgba(255, 255, 255, 0.2)",
      "rgba(0, 0, 0, 0.25)",
      "rgba(0, 0, 0, 0.85)",
      "rgba(0, 0, 0, 0.42)",
      "rgba(0, 0, 0, 0.55)",
      "rgba(0, 0, 0, 0.50)",
      "rgba(0, 0, 0, 0.4)",
      "rgba(255, 255, 255, 0.15)",
      "rgba(255, 255, 255, 0.08)",
      "rgba(0, 0, 0, 0.95)"
    ],
    "animationSignals": [],
    "layoutSignals": [
      "scrolled",
      "nav container",
      "nav logo",
      "nav links",
      "active",
      "nav toggle",
      "parallax section",
      "parallax bg",
      "parallax overlay",
      "overlay dark",
      "overlay medium",
      "section content",
      "section title",
      "hero title",
      "section subtitle",
      "6vw",
      "caps",
      "content block",
      "btn scroll",
      "unsplash credit",
      "about cols",
      "about col",
      "about thumb",
      "thumb top left",
      "about thumb wide",
      "services grid",
      "service item",
      "service icon",
      "stats row",
      "stat item",
      "stat number",
      "stat label",
      "contact form wrap",
      "contact form"
    ],
    "keywordSignals": [
      "templatemo 612 parallax starter",
      "parallax starter free html css template",
      "nav",
      "nav container",
      "parallax section",
      "parallax bg",
      "parallax overlay",
      "section content",
      "about cols",
      "about col",
      "about thumb",
      "thumb top left",
      "about thumb wide",
      "overlay dark",
      "services grid",
      "service item",
      "service icon",
      "content block",
      "stats row",
      "stat item",
      "overlay medium",
      "contact form wrap",
      "form row",
      "footer",
      "welcome",
      "studio",
      "about",
      "what",
      "design",
      "branding",
      "development",
      "work",
      "touch",
      "parallax",
      "starter",
      "home",
      "services",
      "gallery",
      "contact",
      "explore",
      "portfolio",
      "templates",
      "prompt",
      "generator",
      "unsplash",
      "create",
      "beautiful",
      "digital"
    ],
    "assetSignals": [
      "about",
      "parallax bg"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_602_graph_page",
    "title": "Graph Page - Modern Analytics Dashboard",
    "likelyNiches": [
      "saas-tech",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "process/timeline",
      "contact/lead form",
      "dashboard/data cards"
    ],
    "sectionPatterns": [
      "navbar",
      "nav container",
      "logo icon",
      "hamburger",
      "home",
      "hero bg",
      "geometric shapes",
      "shape",
      "shape1",
      "shape2",
      "shape3",
      "shape4",
      "shape5",
      "shape6",
      "hero content",
      "hero text",
      "hero visual",
      "city container",
      "building",
      "building1",
      "building fill",
      "building windows",
      "building2",
      "building3",
      "building4",
      "neon line",
      "neon line1",
      "neon line2",
      "ashboard",
      "ashboard container",
      "stats grid",
      "stat card"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "neon gradients, luminous accents, futuristic rhythm",
      "dashboard grids, metrics cards, data-led proof",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#0a0e27",
      "#ffffff",
      "#00ffcc",
      "#00ccff",
      "#ff6b6b",
      "#ff8e53",
      "#1a1f3a",
      "#a0a0a0",
      "#0f1329",
      "#707070",
      "#1a0033",
      "#2d1b69",
      "rgba(10, 14, 39, 0.95)",
      "rgba(255, 255, 255, 0.1)",
      "rgba(10, 14, 39, 0.98)",
      "rgba(0, 255, 204, 0.3)",
      "rgba(255, 107, 107, 0.5)",
      "rgba(0, 255, 204, 0.6)"
    ],
    "animationSignals": [
      "bgshift",
      "slideinleft",
      "slideinright",
      "pulse",
      "scan"
    ],
    "layoutSignals": [
      "scrolled",
      "nav container",
      "logo",
      "logo icon",
      "logo text",
      "nav links",
      "active",
      "search icon",
      "hero",
      "hero bg",
      "geometric shapes",
      "shape",
      "shape1",
      "shape2",
      "shape3",
      "shape4",
      "shape5",
      "shape6",
      "hero content",
      "hero text",
      "cta button",
      "hero visual",
      "city container",
      "building",
      "building fill",
      "building1",
      "building2",
      "building3",
      "building4",
      "building windows",
      "neon line",
      "neon line1",
      "neon line2",
      "dashboard section"
    ],
    "keywordSignals": [
      "templatemo 602 graph page",
      "graph page modern analytics dashboard",
      "navbar",
      "nav container",
      "logo icon",
      "hamburger",
      "home",
      "hero bg",
      "geometric shapes",
      "shape",
      "shape1",
      "shape2",
      "shape3",
      "shape4",
      "shape5",
      "shape6",
      "hero content",
      "hero text",
      "hero visual",
      "city container",
      "building",
      "building1",
      "building fill",
      "building windows",
      "building2",
      "building3",
      "building4",
      "neon line",
      "neon line1",
      "neon line2",
      "ashboard",
      "ashboard container",
      "stats grid",
      "stat card",
      "stat header",
      "stat icon",
      "stat title",
      "stat value",
      "data",
      "analytics",
      "dashboard",
      "overview",
      "advanced",
      "monthly",
      "trends",
      "growth",
      "geographic",
      "distribution"
    ],
    "assetSignals": [],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_604_christmas_piano",
    "title": "Christmas Piano - Free HTML CSS Template",
    "likelyNiches": [
      "saas-tech",
      "events-entertainment",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "contact/lead form",
      "dashboard/data cards"
    ],
    "sectionPatterns": [
      "snowflakes",
      "header logo row",
      "header nav row",
      "nav container",
      "nav decor",
      "navtoggle",
      "hero",
      "hero content",
      "mini player",
      "player header",
      "song info",
      "now playing",
      "currentsongtitle",
      "player controls",
      "song selector",
      "progress container",
      "progressbar",
      "progressfill",
      "time display",
      "mini piano container",
      "minipiano",
      "player controls row",
      "control group",
      "repeattoggle",
      "repeatswitch",
      "keyboard hint",
      "about",
      "section header",
      "about grid",
      "about media",
      "about content",
      "about stats"
    ],
    "visualSignals": [
      "neon gradients, luminous accents, futuristic rhythm",
      "dark premium surface, strong contrast, cinematic mood",
      "portfolio gallery, editorial images, case-study rhythm",
      "event countdown, seasonal hero, emotional reveal"
    ],
    "colorSignals": [
      "#d4af37",
      "#f4e4bc",
      "#c41e3a",
      "#8b0000",
      "#228b22",
      "#0d5d0d",
      "#0a0c10",
      "#0d1117",
      "#e8e8e8",
      "#888",
      "#fff",
      "#1a1a1a",
      "#0d0d0d",
      "#f8f8f8",
      "#ccc",
      "#f0f0f0",
      "#333",
      "#111"
    ],
    "animationSignals": [
      "snowfall",
      "logoglow",
      "swing"
    ],
    "layoutSignals": [
      "snowflakes",
      "snowflake",
      "header logo row",
      "logo",
      "logo icon",
      "header nav row",
      "nav container",
      "nav decor",
      "ornament",
      "nav links",
      "nav toggle",
      "hero content",
      "hero badge",
      "hero subtitle",
      "mini player",
      "player header",
      "song info",
      "now playing",
      "song title",
      "player controls",
      "control btn",
      "play btn",
      "nav btn",
      "song selector",
      "song tab",
      "active",
      "progress container",
      "progress bar",
      "progress fill",
      "time display",
      "mini piano container",
      "mini piano",
      "mini key",
      "white"
    ],
    "keywordSignals": [
      "templatemo 604 christmas piano",
      "christmas piano free html css template",
      "snowflakes",
      "header logo row",
      "header nav row",
      "nav container",
      "nav decor",
      "navtoggle",
      "hero",
      "hero content",
      "mini player",
      "player header",
      "song info",
      "now playing",
      "currentsongtitle",
      "player controls",
      "song selector",
      "progress container",
      "progressbar",
      "progressfill",
      "time display",
      "mini piano container",
      "minipiano",
      "player controls row",
      "control group",
      "repeattoggle",
      "repeatswitch",
      "keyboard hint",
      "about",
      "section header",
      "about grid",
      "about media",
      "about content",
      "about stats",
      "stat",
      "stat number",
      "stat label",
      "features",
      "christmas",
      "piano",
      "music",
      "digital",
      "experience",
      "works",
      "real",
      "time",
      "audio",
      "visual"
    ],
    "assetSignals": [
      "about piano",
      "christmas pic"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_603_nexaverse",
    "title": "NexaVerse - Digital Excellence",
    "likelyNiches": [
      "restaurant",
      "saas-tech",
      "creative-services",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "testimonials",
      "process/timeline",
      "countdown",
      "contact/lead form",
      "dashboard/data cards"
    ],
    "sectionPatterns": [
      "loadingscreen",
      "loader ring",
      "loading text",
      "ambient bg",
      "orb",
      "orb 1",
      "orb 2",
      "orb 3",
      "grid overlay",
      "mainheader",
      "logo",
      "menugrid",
      "menu item",
      "initial load",
      "menu badge",
      "menu title",
      "contentarea",
      "introduction",
      "section header small",
      "small logo",
      "small brand",
      "intro hero",
      "intro hero content",
      "intro cta group",
      "intro hero visual",
      "intro floating card",
      "card 1",
      "card 2",
      "card 3",
      "intro orb",
      "intro metrics",
      "metric item"
    ],
    "visualSignals": [
      "dashboard grids, metrics cards, data-led proof",
      "portfolio gallery, editorial images, case-study rhythm",
      "product/menu cards, collection blocks, warm commerce flow",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#00f0ff",
      "#ff00d4",
      "#9d4edd",
      "#0a0a12",
      "#12121f",
      "#1a1a2e",
      "#ffffff",
      "rgba(255, 255, 255, 0.03)",
      "rgba(255, 255, 255, 0.08)",
      "rgba(0, 240, 255, 0.4)",
      "rgba(255, 0, 212, 0.4)",
      "rgba(157, 78, 221, 0.3)",
      "rgba(255, 255, 255, 0.05)",
      "rgba(255, 255, 255, 0.5)",
      "rgba(255, 255, 255, 0.12)",
      "rgba(0, 240, 255, 0.08)",
      "rgba(0, 0, 0, 0.4)",
      "rgba(0, 200, 220, 0.2)"
    ],
    "animationSignals": [
      "float",
      "spin",
      "fadeup",
      "menuappear",
      "badgespin",
      "sectionin",
      "orbpulse",
      "floatcard",
      "floatcardalt",
      "marquee",
      "tabfade",
      "exitdown",
      "menureturn"
    ],
    "layoutSignals": [
      "ambient bg",
      "orb",
      "orb 1",
      "orb 2",
      "orb 3",
      "grid overlay",
      "loading screen",
      "hidden",
      "loader ring",
      "loading text",
      "header",
      "logo",
      "brand name",
      "tagline",
      "menu grid",
      "menu item",
      "175",
      "885",
      "visible",
      "initial load",
      "menu badge",
      "menu title",
      "content section",
      "active",
      "section header small",
      "small logo",
      "back btn",
      "section header",
      "section title",
      "section subtitle",
      "glass card",
      "intro hero",
      "intro hero content",
      "intro badge"
    ],
    "keywordSignals": [
      "templatemo 603 nexaverse",
      "nexaverse digital excellence",
      "loadingscreen",
      "loader ring",
      "loading text",
      "ambient bg",
      "orb",
      "orb 1",
      "orb 2",
      "orb 3",
      "grid overlay",
      "mainheader",
      "logo",
      "menugrid",
      "menu item",
      "initial load",
      "menu badge",
      "menu title",
      "contentarea",
      "introduction",
      "section header small",
      "small logo",
      "small brand",
      "intro hero",
      "intro hero content",
      "intro cta group",
      "intro hero visual",
      "intro floating card",
      "card 1",
      "card 2",
      "card 3",
      "intro orb",
      "intro metrics",
      "metric item",
      "metric divider",
      "intro values",
      "value card",
      "value number",
      "nexaverse",
      "build",
      "digital",
      "experiences",
      "matter",
      "innovation",
      "first",
      "human",
      "centered",
      "results"
    ],
    "assetSignals": [
      "support",
      "about our team",
      "ai mobile app",
      "ai optimized templates",
      "brand identity",
      "coding screen",
      "design screen",
      "digital strategy",
      "managed service",
      "motion design",
      "process optimized",
      "tech audit",
      "training center"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_605_xmas_countdown",
    "title": "Xmas Countdown - Christmas Countdown Template",
    "likelyNiches": [
      "saas-tech",
      "events-entertainment"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "pricing/plans",
      "countdown",
      "contact/lead form"
    ],
    "sectionPatterns": [
      "grid bg",
      "particles",
      "header",
      "logo icon",
      "nav",
      "navtoggle",
      "hero",
      "hero badge",
      "countdown wrapper",
      "countdown",
      "countdown item",
      "target date",
      "scroll indicator",
      "line",
      "about",
      "section header",
      "about grid",
      "about image",
      "about image stack",
      "about img item",
      "img 1",
      "img 2",
      "img 3",
      "about content",
      "about features",
      "about feature",
      "about templatemo",
      "events",
      "events grid",
      "event card",
      "event image",
      "event date badge"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "neon gradients, luminous accents, futuristic rhythm",
      "event countdown, seasonal hero, emotional reveal",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#0a0a0f",
      "#ffffff",
      "#ff3d5a",
      "#00d4aa",
      "#ffd700",
      "#4d9fff",
      "#ff6b6b",
      "#00b894",
      "rgba(255, 255, 255, 0.03)",
      "rgba(255, 255, 255, 0.05)",
      "rgba(255, 255, 255, 0.08)",
      "rgba(255, 255, 255, 0.15)",
      "rgba(255, 255, 255, 0.6)",
      "rgba(255, 255, 255, 0.4)",
      "rgba(255, 61, 90, 0.4)",
      "rgba(0, 212, 170, 0.4)",
      "rgba(255, 215, 0, 0.3)",
      "rgba(255, 255, 255, 0.02)"
    ],
    "animationSignals": [
      "float particle",
      "snowfall",
      "pulse",
      "fadeindown",
      "fadeinup",
      "blink",
      "bounce"
    ],
    "layoutSignals": [
      "grid bg",
      "particles",
      "particle",
      "snowflake",
      "glass",
      "glass strong",
      "scrolled",
      "logo",
      "logo icon",
      "logo text",
      "nav active",
      "nav cta",
      "nav toggle",
      "hero",
      "hero badge",
      "dot",
      "gradient",
      "hero subtitle",
      "countdown wrapper",
      "countdown",
      "countdown item",
      "countdown number",
      "countdown label",
      "countdown colon",
      "target date",
      "scroll indicator",
      "line",
      "section header",
      "section tag",
      "section title",
      "5rem",
      "section subtitle",
      "about",
      "about grid"
    ],
    "keywordSignals": [
      "templatemo 605 xmas countdown",
      "xmas countdown christmas countdown template",
      "grid bg",
      "particles",
      "header",
      "logo icon",
      "nav",
      "navtoggle",
      "hero",
      "hero badge",
      "countdown wrapper",
      "countdown",
      "countdown item",
      "target date",
      "scroll indicator",
      "line",
      "about",
      "section header",
      "about grid",
      "about image",
      "about image stack",
      "about img item",
      "img 1",
      "img 2",
      "img 3",
      "about content",
      "about features",
      "about feature",
      "about templatemo",
      "events",
      "events grid",
      "event card",
      "event image",
      "event date badge",
      "month",
      "event content",
      "event meta",
      "traditions",
      "christmas",
      "spirit",
      "time",
      "wonder",
      "celebration",
      "holiday",
      "carol",
      "night",
      "cookie",
      "exchange"
    ],
    "assetSignals": [
      "christmas pic"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_570_chain_app_dev",
    "title": "Chain App Dev - App Landing Page HTML5 Template",
    "likelyNiches": [
      "restaurant",
      "saas-tech",
      "education-training",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "features/services",
      "portfolio/gallery",
      "pricing/plans",
      "testimonials",
      "contact/lead form"
    ],
    "sectionPatterns": [
      "preloader",
      "preloader inner",
      "ots",
      "header area",
      "header sticky",
      "slideindown",
      "main nav",
      "gradient button",
      "popupcontainer",
      "popupheader",
      "popupbody",
      "social login",
      "centeredtext",
      "action btns",
      "one half",
      "last",
      "user login",
      "checkbox",
      "user register",
      "top",
      "lg 12",
      "lg 6",
      "self center",
      "left content",
      "show up",
      "header text",
      "inleft",
      "white button",
      "first button",
      "scroll to section",
      "right image",
      "inright"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "neon gradients, luminous accents, futuristic rhythm",
      "product/menu cards, collection blocks, warm commerce flow",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#eeeeee",
      "#ffffff",
      "#000",
      "#fff",
      "#afafaf",
      "#4b8ef1",
      "#2a2a2a",
      "#f7f7f7",
      "#eee",
      "#069",
      "#1e1e1e",
      "#e7e7e7",
      "#191a20",
      "#3b566e",
      "#7a7a7a",
      "#726ae3",
      "#e4e4e2",
      "#f4f4f2",
      "#ddd",
      "#3b5998",
      "#0d6efd",
      "#6610f2",
      "#6f42c1",
      "#d63384"
    ],
    "animationSignals": [
      "bounce",
      "flash",
      "pulse",
      "rubberband",
      "shake",
      "swing",
      "tada",
      "wobble",
      "bouncein",
      "bounceindown",
      "bounceinleft",
      "bounceinright",
      "bounceinup",
      "bounceout",
      "bounceoutdown",
      "bounceoutleft",
      "fa spin",
      "fadeout"
    ],
    "layoutSignals": [
      "animated",
      "infinite",
      "hinge",
      "215",
      "610",
      "355",
      "755",
      "050",
      "855",
      "bounce",
      "flash",
      "pulse",
      "rubberband",
      "shake",
      "swing",
      "tada",
      "wobble",
      "bouncein",
      "bounceindown",
      "bounceinleft",
      "bounceinright",
      "bounceinup",
      "bounceout",
      "bounceoutdown",
      "bounceoutleft",
      "bounceoutright",
      "bounceoutup",
      "fadein",
      "fadeindown",
      "fadeindownbig",
      "fadeinleft",
      "fadeinleftbig",
      "fadeinright",
      "fadeinrightbig"
    ],
    "keywordSignals": [
      "templatemo 570 chain app dev",
      "chain app dev app landing page html5 template",
      "preloader",
      "preloader inner",
      "ots",
      "header area",
      "header sticky",
      "slideindown",
      "main nav",
      "gradient button",
      "popupcontainer",
      "popupheader",
      "popupbody",
      "social login",
      "centeredtext",
      "action btns",
      "one half",
      "last",
      "user login",
      "checkbox",
      "user register",
      "top",
      "lg 12",
      "lg 6",
      "self center",
      "left content",
      "show up",
      "header text",
      "inleft",
      "white button",
      "first button",
      "scroll to section",
      "right image",
      "inright",
      "services",
      "lg 8",
      "offset lg 2",
      "section heading",
      "latest",
      "from",
      "stores",
      "amazing",
      "features",
      "maintenance",
      "rocket",
      "speed",
      "multi",
      "workflow"
    ],
    "assetSignals": [
      "flexslider icon",
      "fontawesome webfont",
      "slick",
      "about bg",
      "about right dec",
      "client bg",
      "client image",
      "footer bg",
      "heading line dec",
      "logo",
      "pricing table",
      "pro table bottom",
      "pro table top",
      "quote",
      "regular table bottom",
      "regular table top",
      "service bg",
      "service icon",
      "service icon hover",
      "services left dec"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_511_journey",
    "title": "Journey HTML CSS Template",
    "likelyNiches": [
      "events-entertainment"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "process/timeline",
      "contact/lead form"
    ],
    "sectionPatterns": [
      "top",
      "top bar bg",
      "top bar",
      "navbar",
      "navbar expand lg",
      "narbar light",
      "lapse",
      "navbar collapse",
      "bg white",
      "page wrap",
      "mx auto",
      "banner",
      "container outer",
      "banner bg",
      "banner row",
      "banner row header",
      "xs 12",
      "banner header",
      "section search",
      "form row",
      "search form row",
      "form group",
      "form group pad",
      "form group 1",
      "form group 2",
      "form group 3",
      "banner overlay",
      "p 5",
      "bg gray",
      "about text wrap",
      "center",
      "section 2"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections"
    ],
    "colorSignals": [
      "#007bff",
      "#6610f2",
      "#6f42c1",
      "#e83e8c",
      "#dc3545",
      "#fd7e14",
      "#ffc107",
      "#28a745",
      "#20c997",
      "#17a2b8",
      "#fff",
      "#868e96",
      "#343a40",
      "#f8f9fa",
      "#999",
      "#000",
      "#ddd",
      "#212529",
      "rgba(0, 0, 0, 0.3)",
      "rgba(0, 0, 0, 0.75)",
      "rgba(128, 128, 128, 0.4)",
      "rgba(0, 0, 0, 0.1)",
      "#69c6ba",
      "#c66995"
    ],
    "animationSignals": [
      "progress bar stripes",
      "fa spin"
    ],
    "layoutSignals": [
      "navbar",
      "badge",
      "table",
      "lead",
      "display 1",
      "display 2",
      "display 3",
      "display 4",
      "small",
      "mark",
      "list unstyled",
      "list inline",
      "list inline item",
      "initialism",
      "blockquote",
      "blockquote footer",
      "img fluid",
      "img thumbnail",
      "figure",
      "figure img",
      "figure caption",
      "pre scrollable",
      "container fluid",
      "row",
      "no gutters",
      "col",
      "col 1",
      "col 10",
      "col 11",
      "col 12",
      "col 2",
      "col 3",
      "col 4",
      "col 5"
    ],
    "keywordSignals": [
      "templatemo 511 journey",
      "journey html css template",
      "top",
      "top bar bg",
      "top bar",
      "navbar",
      "navbar expand lg",
      "narbar light",
      "lapse",
      "navbar collapse",
      "bg white",
      "page wrap",
      "mx auto",
      "banner",
      "container outer",
      "banner bg",
      "banner row",
      "banner row header",
      "xs 12",
      "banner header",
      "section search",
      "form row",
      "search form row",
      "form group",
      "form group pad",
      "form group 1",
      "form group 2",
      "form group 3",
      "banner overlay",
      "p 5",
      "bg gray",
      "about text wrap",
      "center",
      "section 2",
      "slideshow section",
      "slideshow",
      "slideshow description",
      "bg primary",
      "begin",
      "journey",
      "priority",
      "europe",
      "most",
      "visited",
      "places",
      "asia",
      "popular",
      "america"
    ],
    "assetSignals": [
      "fontawesome webfont",
      "africa",
      "antartica",
      "asia",
      "australia",
      "banner",
      "button curve",
      "dots",
      "europe",
      "logo",
      "north america",
      "south america",
      "tm img",
      "ajax loader",
      "slick"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_512_moonlight",
    "title": "Moonlight CSS Template",
    "likelyNiches": [
      "events-entertainment",
      "education-training"
    ],
    "pageCount": 2,
    "htmlFiles": [
      "index-test-added-1-page.html",
      "index.html"
    ],
    "componentSignals": [
      "features/services",
      "portfolio/gallery",
      "contact/lead form"
    ],
    "sectionPatterns": [
      "sequence",
      "seq preloader",
      "logo",
      "mini logo",
      "slides",
      "first content",
      "container fluid",
      "md 3",
      "author image",
      "md 9",
      "main btn",
      "fb btn",
      "second content",
      "md 6",
      "left content",
      "right image",
      "third content",
      "md 12",
      "first section",
      "second section",
      "left image",
      "right content",
      "fourth content",
      "md 4",
      "sm 6",
      "thumb",
      "hover effect",
      "hover content",
      "fifth content",
      "map",
      "footer"
    ],
    "visualSignals": [
      "dark premium surface, strong contrast, cinematic mood",
      "event countdown, seasonal hero, emotional reveal",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#fff",
      "#e0e0e0",
      "#ffffffff",
      "#ffe0e0e0",
      "#dbdbdb",
      "#ccc",
      "#337ab7",
      "#265a88",
      "#ff337ab7",
      "#ff265a88",
      "#245580",
      "#5cb85c",
      "#419641",
      "#ff5cb85c",
      "#ff419641",
      "#3e8f3e",
      "#5bc0de",
      "#2aabd2",
      "#000",
      "#ff0",
      "#c0c0c0",
      "#999",
      "#ddd",
      "#333"
    ],
    "animationSignals": [
      "progress bar stripes",
      "fa spin",
      "seq preloader",
      "fill",
      "fillcolour"
    ],
    "layoutSignals": [
      "btn default",
      "btn primary",
      "btn success",
      "btn info",
      "btn warning",
      "btn danger",
      "active",
      "badge",
      "btn",
      "thumbnail",
      "img thumbnail",
      "navbar default",
      "navbar brand",
      "navbar inverse",
      "navbar static top",
      "navbar fixed top",
      "navbar fixed bottom",
      "alert",
      "alert success",
      "alert info",
      "alert warning",
      "alert danger",
      "progress",
      "progress bar",
      "progress bar success",
      "progress bar info",
      "progress bar warning",
      "progress bar danger",
      "progress bar striped",
      "list group",
      "panel",
      "panel heading",
      "well",
      "navbar"
    ],
    "keywordSignals": [
      "templatemo 512 moonlight",
      "moonlight css template",
      "sequence",
      "seq preloader",
      "logo",
      "mini logo",
      "slides",
      "first content",
      "container fluid",
      "md 3",
      "author image",
      "md 9",
      "main btn",
      "fb btn",
      "second content",
      "md 6",
      "left content",
      "right image",
      "third content",
      "md 12",
      "first section",
      "second section",
      "left image",
      "right content",
      "fourth content",
      "md 4",
      "sm 6",
      "thumb",
      "hover effect",
      "hover content",
      "fifth content",
      "map",
      "footer",
      "mingalar",
      "second",
      "additional",
      "about",
      "quisque",
      "commodo",
      "quam",
      "maecenas",
      "purus",
      "sapien",
      "number",
      "three",
      "four",
      "fifth",
      "sixth"
    ],
    "assetSignals": [
      "flexslider icon",
      "fontawesome webfont",
      "glyphicons halflings regular",
      "about image",
      "author image",
      "close",
      "eight big item",
      "eight item",
      "fifth bg",
      "fifth big item",
      "fifth item",
      "first bg",
      "first big item",
      "first item",
      "first service",
      "fourth bg",
      "fourth big item",
      "fourth item",
      "loading",
      "logo"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_509_hydro",
    "title": "Hydro - Blog Page",
    "likelyNiches": [
      "saas-tech",
      "creative-services",
      "education-training",
      "premium-business"
    ],
    "pageCount": 2,
    "htmlFiles": [
      "blog-detail.html",
      "index.html"
    ],
    "componentSignals": [
      "features/services",
      "portfolio/gallery",
      "pricing/plans",
      "contact/lead form"
    ],
    "sectionPatterns": [
      "preloader",
      "spinner",
      "navbar",
      "custom navbar",
      "navbar fixed top",
      "navbar header",
      "lapse",
      "navbar collapse",
      "blog header",
      "overlay",
      "md offset 1",
      "md 5",
      "sm 12",
      "blog detail",
      "md 10",
      "blog detail thumb",
      "blog image",
      "blog ads",
      "blog social share",
      "footer thumb",
      "footer info",
      "md 2",
      "sm 4",
      "md 3",
      "md 12",
      "footer bottom",
      "md 6",
      "sm 5",
      "copyright text",
      "sm 7",
      "phone contact",
      "modal form"
    ],
    "visualSignals": [
      "portfolio gallery, editorial images, case-study rhythm",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#000",
      "#ff0",
      "#999",
      "#fff",
      "#ddd",
      "#333",
      "#337ab7",
      "#23527c",
      "#eee",
      "#777",
      "#fcf8e3",
      "#286090",
      "#3c763d",
      "#2b542c",
      "#31708f",
      "#245269",
      "#8a6d3b",
      "#66512c",
      "#0b0b0b",
      "#ccc",
      "#3f3f3f",
      "#444",
      "#bdbdbd",
      "#f3f3f3"
    ],
    "animationSignals": [
      "progress bar stripes",
      "fa spin",
      "spinner"
    ],
    "layoutSignals": [
      "navbar",
      "caret",
      "label",
      "table",
      "glyphicon",
      "glyphicon asterisk",
      "glyphicon plus",
      "glyphicon eur",
      "glyphicon euro",
      "glyphicon minus",
      "glyphicon cloud",
      "glyphicon envelope",
      "glyphicon pencil",
      "glyphicon glass",
      "glyphicon music",
      "glyphicon search",
      "glyphicon heart",
      "glyphicon star",
      "glyphicon star empty",
      "glyphicon user",
      "glyphicon film",
      "glyphicon th large",
      "glyphicon th",
      "glyphicon th list",
      "glyphicon ok",
      "glyphicon remove",
      "glyphicon zoom in",
      "glyphicon zoom out",
      "glyphicon off",
      "glyphicon signal",
      "glyphicon cog",
      "glyphicon trash",
      "glyphicon home",
      "glyphicon file"
    ],
    "keywordSignals": [
      "templatemo 509 hydro",
      "hydro blog page",
      "preloader",
      "spinner",
      "navbar",
      "custom navbar",
      "navbar fixed top",
      "navbar header",
      "lapse",
      "navbar collapse",
      "blog header",
      "overlay",
      "md offset 1",
      "md 5",
      "sm 12",
      "blog detail",
      "md 10",
      "blog detail thumb",
      "blog image",
      "blog ads",
      "blog social share",
      "footer thumb",
      "footer info",
      "md 2",
      "sm 4",
      "md 3",
      "md 12",
      "footer bottom",
      "md 6",
      "sm 5",
      "copyright text",
      "sm 7",
      "phone contact",
      "modal form",
      "modal dialog",
      "modal lg",
      "modal content",
      "modal popup",
      "know",
      "what",
      "thing",
      "really",
      "makes",
      "artist",
      "nowadays",
      "happy",
      "everyday",
      "blog"
    ],
    "assetSignals": [
      "fontawesome webfont",
      "about image",
      "blog detail image",
      "blog header bg",
      "blog image",
      "home bg",
      "work image"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_588_ebook_landing",
    "title": "ebook landing page template",
    "likelyNiches": [
      "saas-tech",
      "creative-services",
      "education-training",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "testimonials",
      "contact/lead form"
    ],
    "sectionPatterns": [
      "navbar",
      "navbar expand lg",
      "lg none",
      "ms auto",
      "me 3",
      "navbarnav",
      "none",
      "lg block",
      "section 1",
      "lg 6",
      "mb 5",
      "pb 5",
      "pb lg 0",
      "mb lg 0",
      "hero image wrap",
      "mt 3",
      "mt lg 0",
      "featured section",
      "lg 8",
      "avatar group",
      "flex",
      "wrap",
      "items center",
      "reviews group",
      "py lg 5",
      "section 2",
      "book section info",
      "lg 12",
      "center",
      "lg 4",
      "h 100",
      "column"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "neon gradients, luminous accents, futuristic rhythm",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#0d6efd",
      "#6610f2",
      "#6f42c1",
      "#d63384",
      "#dc3545",
      "#fd7e14",
      "#ffc107",
      "#198754",
      "#20c997",
      "#0dcaf0",
      "#000",
      "#fff",
      "#6c757d",
      "#343a40",
      "#f8f9fa",
      "#e9ecef",
      "#dee2e6",
      "#ced4da",
      "#ffffff",
      "#e76f51",
      "#e9c46a",
      "#f0f8ff",
      "#f4a261",
      "#000000"
    ],
    "animationSignals": [
      "progress bar stripes",
      "spinner border",
      "spinner grow",
      "placeholder glow",
      "placeholder wave",
      "lineup",
      "anim naira 1"
    ],
    "layoutSignals": [
      "bi 123",
      "bi alarm fill",
      "bi alarm",
      "bi align bottom",
      "bi align center",
      "bi align end",
      "bi align middle",
      "bi align start",
      "bi align top",
      "bi alt",
      "bi app indicator",
      "bi app",
      "bi archive fill",
      "bi archive",
      "bi arrow 90deg down",
      "bi arrow 90deg left",
      "bi arrow 90deg right",
      "bi arrow 90deg up",
      "bi arrow bar down",
      "bi arrow bar left",
      "bi arrow bar right",
      "bi arrow bar up",
      "bi arrow clockwise",
      "bi arrow counterclockwise",
      "bi arrow down circle fill",
      "bi arrow down circle",
      "bi arrow down left circle fill",
      "bi arrow down left circle",
      "bi arrow down left square fill",
      "bi arrow down left square",
      "bi arrow down left",
      "bi arrow down right circle fill",
      "bi arrow down right circle",
      "bi arrow down right square fill"
    ],
    "keywordSignals": [
      "templatemo 588 ebook landing",
      "ebook landing page template",
      "navbar",
      "navbar expand lg",
      "lg none",
      "ms auto",
      "me 3",
      "navbarnav",
      "none",
      "lg block",
      "section 1",
      "lg 6",
      "mb 5",
      "pb 5",
      "pb lg 0",
      "mb lg 0",
      "hero image wrap",
      "mt 3",
      "mt lg 0",
      "featured section",
      "lg 8",
      "avatar group",
      "flex",
      "wrap",
      "items center",
      "reviews group",
      "py lg 5",
      "section 2",
      "book section info",
      "lg 12",
      "center",
      "lg 4",
      "h 100",
      "column",
      "items stretch",
      "nav",
      "nav pills",
      "scrollspy example 2",
      "introducing",
      "ebook",
      "landing",
      "professionals",
      "modern",
      "creative",
      "about",
      "book",
      "what",
      "inside"
    ],
    "assetSignals": [
      "portrait beautiful young woman standing grey wall",
      "portrait young redhead bearded male",
      "pretty blonde woman",
      "studio portrait emotional happy funny smiling boyfriend",
      "businessman sitting by table cafe",
      "circle scatter haikei",
      "education online books",
      "portrait mature smiling authoress sitting desk",
      "tablet screen contents"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_540_lava_landing_page",
    "title": "Lava Landing Page HTML Template",
    "likelyNiches": [
      "restaurant",
      "creative-services",
      "education-training",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "features/services",
      "testimonials",
      "contact/lead form",
      "interactive sections"
    ],
    "sectionPatterns": [
      "preloader",
      "jumper",
      "header area",
      "header sticky",
      "main nav",
      "welcome",
      "header text",
      "left text",
      "lg 6",
      "md 12",
      "sm 12",
      "xs 12",
      "about",
      "lg 4",
      "md 6",
      "features item",
      "features icon",
      "left image decor",
      "promotion",
      "left image",
      "lg 5",
      "mobile bottom fix big",
      "right text",
      "offset lg 1",
      "mobile bottom fix",
      "right image decor",
      "testimonials",
      "lg 8",
      "offset lg 2",
      "center heading",
      "lg 10",
      "owl carousel"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "product/menu cards, collection blocks, warm commerce flow"
    ],
    "colorSignals": [
      "#007bff",
      "#6610f2",
      "#6f42c1",
      "#e83e8c",
      "#dc3545",
      "#fd7e14",
      "#ffc107",
      "#28a745",
      "#20c997",
      "#17a2b8",
      "#fff",
      "#6c757d",
      "#343a40",
      "#f8f9fa",
      "#212529",
      "#0056b3",
      "#fcf8e3",
      "#dee2e6",
      "#000",
      "#666",
      "#333",
      "rgba(0, 0, 0, 0.2)",
      "rgba(0, 0, 0, 0.8)",
      "rgba(255, 255, 255, 0.3)"
    ],
    "animationSignals": [
      "progress bar stripes",
      "spinner border",
      "spinner grow",
      "fa spin",
      "fadeout",
      "jumper"
    ],
    "layoutSignals": [
      "lead",
      "display 1",
      "display 2",
      "display 3",
      "display 4",
      "small",
      "mark",
      "list unstyled",
      "list inline",
      "list inline item",
      "initialism",
      "blockquote",
      "blockquote footer",
      "img fluid",
      "img thumbnail",
      "figure",
      "figure img",
      "figure caption",
      "pre scrollable",
      "container fluid",
      "row",
      "no gutters",
      "col",
      "col 1",
      "col 10",
      "col 11",
      "col 12",
      "col 2",
      "col 3",
      "col 4",
      "col 5",
      "col 6",
      "col 7",
      "col 8"
    ],
    "keywordSignals": [
      "templatemo 540 lava landing page",
      "lava landing page html template",
      "preloader",
      "jumper",
      "header area",
      "header sticky",
      "main nav",
      "welcome",
      "header text",
      "left text",
      "lg 6",
      "md 12",
      "sm 12",
      "xs 12",
      "about",
      "lg 4",
      "md 6",
      "features item",
      "features icon",
      "left image decor",
      "promotion",
      "left image",
      "lg 5",
      "mobile bottom fix big",
      "right text",
      "offset lg 1",
      "mobile bottom fix",
      "right image decor",
      "testimonials",
      "lg 8",
      "offset lg 2",
      "center heading",
      "lg 10",
      "owl carousel",
      "owl theme",
      "service item",
      "author",
      "testimonial content",
      "simple",
      "create",
      "trend",
      "analysis",
      "site",
      "optimization",
      "email",
      "design",
      "vestibulum",
      "pulvinar"
    ],
    "assetSignals": [
      "flexslider icon",
      "fontawesome webfont",
      "slick",
      "about icon",
      "banner bg",
      "features icon",
      "footer bg",
      "left bg decor",
      "left image",
      "right bg decor",
      "testimonial author"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_598_sleeky_pro",
    "title": "Sleeky Pro - Premium Photography & Nature",
    "likelyNiches": [
      "saas-tech",
      "creative-services",
      "fashion-beauty",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "process/timeline",
      "countdown",
      "contact/lead form",
      "dashboard/data cards",
      "interactive sections"
    ],
    "sectionPatterns": [
      "header",
      "nav container",
      "hero",
      "slider container",
      "progress ring",
      "progressbar",
      "sliderstage",
      "overlay",
      "controls",
      "ots",
      "thumbnails",
      "services",
      "section container",
      "section header",
      "services container",
      "services tabs",
      "service tab",
      "active",
      "services content",
      "photography",
      "service content icon",
      "expeditions",
      "prints",
      "about",
      "about grid",
      "about timeline",
      "timeline line",
      "timeline item",
      "timeline dot",
      "timeline year",
      "timeline title",
      "timeline description"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "gold accents, luxury spacing, premium cards",
      "dashboard grids, metrics cards, data-led proof",
      "product/menu cards, collection blocks, warm commerce flow",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#333",
      "#ff6b6b",
      "#7fffd4",
      "#555",
      "#e57373",
      "#9090cf",
      "#ffab91",
      "#666",
      "#f8f9fa",
      "#e9ecef",
      "#ff8a65",
      "#1a1a2e",
      "#16213e",
      "#0f3460",
      "#94a3b8",
      "#1e3c72",
      "#0ea5e9",
      "#38bdf8"
    ],
    "animationSignals": [
      "rotate",
      "fillprogress",
      "fadeinup"
    ],
    "layoutSignals": [
      "header",
      "scrolled",
      "nav container",
      "logo container",
      "logo svg",
      "logo text",
      "nav menu",
      "active",
      "hamburger",
      "hero",
      "slider container",
      "slider stage",
      "slice container",
      "slice cube",
      "rotate 1",
      "rotate 2",
      "rotate 3",
      "slice face",
      "face 1",
      "face 2",
      "face 3",
      "face 4",
      "slice image",
      "text overlay",
      "hiding",
      "slide title",
      "slide description",
      "controls",
      "control btn",
      "nav arrow",
      "prev",
      "next",
      "play pause btn",
      "play icon"
    ],
    "keywordSignals": [
      "templatemo 598 sleeky pro",
      "sleeky pro premium photography nature",
      "header",
      "nav container",
      "hero",
      "slider container",
      "progress ring",
      "progressbar",
      "sliderstage",
      "overlay",
      "controls",
      "ots",
      "thumbnails",
      "services",
      "section container",
      "section header",
      "services container",
      "services tabs",
      "service tab",
      "active",
      "services content",
      "photography",
      "service content icon",
      "expeditions",
      "prints",
      "about",
      "about grid",
      "about timeline",
      "timeline line",
      "timeline item",
      "timeline dot",
      "timeline year",
      "timeline title",
      "timeline description",
      "about tech",
      "tech card",
      "tech icon",
      "tech title",
      "mountain",
      "peak",
      "cinematic",
      "alpine",
      "fine",
      "landscape",
      "expedition",
      "museum",
      "grade",
      "future"
    ],
    "assetSignals": [
      "unsplash image",
      "unsplash thumb"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_600_prism_flux",
    "title": "PRISM FLUX - Digital Innovation Studio",
    "likelyNiches": [
      "restaurant",
      "saas-tech",
      "creative-services",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "features/services",
      "portfolio/gallery",
      "countdown",
      "contact/lead form",
      "dashboard/data cards",
      "interactive sections"
    ],
    "sectionPatterns": [
      "loader",
      "loader content",
      "loader prism",
      "prism face",
      "header",
      "nav container",
      "logo icon",
      "logo prism",
      "prism shape",
      "menutoggle",
      "home",
      "carousel container",
      "carousel",
      "carousel controls",
      "indicators",
      "about",
      "philosophy container",
      "prism line",
      "philosophy pillars",
      "pillar",
      "pillar icon",
      "particles",
      "stats",
      "section header",
      "stats grid",
      "stat card",
      "stat icon",
      "stat number",
      "stat label",
      "skills",
      "skills container",
      "skill categories"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "neon gradients, luminous accents, futuristic rhythm",
      "dashboard grids, metrics cards, data-led proof",
      "product/menu cards, collection blocks, warm commerce flow"
    ],
    "colorSignals": [
      "#0a0a0a",
      "#121212",
      "#1a1a1a",
      "#2a2a2a",
      "#3a3a3a",
      "#4a4a4a",
      "#ff3333",
      "#00a8ff",
      "#00ff88",
      "#9945ff",
      "#00ffff",
      "#ffffff",
      "#b0b0b0",
      "#808080",
      "rgba(255, 255, 255, 0.03)",
      "rgba(255, 51, 51, 0.05)",
      "rgba(18, 18, 18, 0.98)",
      "rgba(18, 18, 18, 0.9)"
    ],
    "animationSignals": [
      "gridmove",
      "prismrotate",
      "prismshine",
      "scanline",
      "prismsweep",
      "gradientflow",
      "pulse",
      "float particle",
      "slideright",
      "float",
      "filllevel"
    ],
    "layoutSignals": [
      "loader",
      "hidden",
      "loader content",
      "loader prism",
      "prism face",
      "header",
      "scrolled",
      "nav container",
      "logo",
      "logo icon",
      "logo prism",
      "prism shape",
      "logo text",
      "prism",
      "flux",
      "nav menu",
      "active",
      "menu toggle",
      "hero",
      "carousel container",
      "carousel",
      "carousel item",
      "card number",
      "card image",
      "card title",
      "card description",
      "card tech",
      "tech badge",
      "card cta",
      "carousel controls",
      "carousel btn",
      "carousel indicators",
      "indicator",
      "philosophy section"
    ],
    "keywordSignals": [
      "templatemo 600 prism flux",
      "prism flux digital innovation studio",
      "loader",
      "loader content",
      "loader prism",
      "prism face",
      "header",
      "nav container",
      "logo icon",
      "logo prism",
      "prism shape",
      "menutoggle",
      "home",
      "carousel container",
      "carousel",
      "carousel controls",
      "indicators",
      "about",
      "philosophy container",
      "prism line",
      "philosophy pillars",
      "pillar",
      "pillar icon",
      "particles",
      "stats",
      "section header",
      "stats grid",
      "stat card",
      "stat icon",
      "stat number",
      "stat label",
      "skills",
      "skills container",
      "skill categories",
      "category tab",
      "active",
      "skillsgrid",
      "contact",
      "refracting",
      "ideas",
      "into",
      "reality",
      "innovation",
      "precision",
      "evolution",
      "performance",
      "metrics",
      "technical"
    ],
    "assetSignals": [
      "ar interface",
      "blockchain vault",
      "cyber defense",
      "data nexus",
      "iot matrix",
      "neural network",
      "quantum cloud"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_599_noir_fashion",
    "title": "NOIR - Fashion Forward",
    "likelyNiches": [
      "restaurant",
      "saas-tech",
      "fashion-beauty"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "contact/lead form",
      "dashboard/data cards",
      "interactive sections"
    ],
    "sectionPatterns": [
      "navbar",
      "nav container",
      "menutoggle",
      "mobilenav",
      "home",
      "hero bg",
      "hero container",
      "hero left",
      "hero badge",
      "hero stats",
      "stat",
      "cta group",
      "hero right",
      "hero image wrapper",
      "hero carousel",
      "carousel slide",
      "active",
      "carousel overlay",
      "carousel indicators",
      "floating tags",
      "tag",
      "scroll indicator",
      "lections",
      "section header",
      "category tabs",
      "lectionsgrid",
      "lection card",
      "lection thumbnail",
      "card content",
      "featured",
      "featured container",
      "featured hero"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "dark premium surface, strong contrast, cinematic mood",
      "gold accents, luxury spacing, premium cards",
      "product/menu cards, collection blocks, warm commerce flow",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#0a0a0a",
      "#ff3366",
      "#ff1149",
      "#ffffff",
      "#999",
      "#000",
      "#fff",
      "#ff6690",
      "#1a1a1a",
      "#2a2a2a",
      "#333",
      "#222",
      "#444",
      "#cc0044",
      "#111",
      "rgba(0, 0, 0, 0.95)",
      "rgba(0, 0, 0, 0.98)",
      "rgba(0, 0, 0, 0.5)"
    ],
    "animationSignals": [
      "spin",
      "shimmer",
      "slideup",
      "slideinleft",
      "kenburns",
      "fadeinscale",
      "bounce",
      "scrolldot",
      "fadeinup",
      "fadein",
      "rotate",
      "slidedown"
    ],
    "layoutSignals": [
      "scrolled",
      "nav container",
      "logo link",
      "logo svg",
      "logo text",
      "nav links",
      "active",
      "nav cta",
      "hero container",
      "hero left",
      "hero stats",
      "hero right",
      "grid",
      "featured container",
      "featured hero",
      "featured content",
      "feature highlights",
      "featured image section",
      "testimonials grid",
      "testimonial card",
      "hero title",
      "hero image wrapper",
      "tag",
      "collections",
      "featured",
      "contact",
      "menu toggle",
      "mobile nav",
      "mobile nav links",
      "hero",
      "hero bg",
      "hero badge",
      "line",
      "accent"
    ],
    "keywordSignals": [
      "templatemo 599 noir fashion",
      "noir fashion forward",
      "navbar",
      "nav container",
      "menutoggle",
      "mobilenav",
      "home",
      "hero bg",
      "hero container",
      "hero left",
      "hero badge",
      "hero stats",
      "stat",
      "cta group",
      "hero right",
      "hero image wrapper",
      "hero carousel",
      "carousel slide",
      "active",
      "carousel overlay",
      "carousel indicators",
      "floating tags",
      "tag",
      "scroll indicator",
      "lections",
      "section header",
      "category tabs",
      "lectionsgrid",
      "lection card",
      "lection thumbnail",
      "card content",
      "featured",
      "featured container",
      "featured hero",
      "featured content",
      "feature highlights",
      "highlight item",
      "highlight icon",
      "redefine",
      "style",
      "revolution",
      "latest",
      "collections",
      "urban",
      "edge",
      "midnight",
      "luxe",
      "classic"
    ],
    "assetSignals": [
      "accent pieces",
      "art of fashion",
      "avant garde",
      "midnight luxe",
      "minimal chic",
      "neo classic",
      "noir fashion hero",
      "spring bloom",
      "street rebel",
      "urban edge"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_596_electric_xtra",
    "title": "ELECTRIC XTRA - Cyberpunk Landing Page by TemplateMo",
    "likelyNiches": [
      "restaurant",
      "saas-tech",
      "education-training"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "contact/lead form",
      "dashboard/data cards",
      "interactive sections"
    ],
    "sectionPatterns": [
      "grid bg",
      "gradient overlay",
      "scanlines",
      "shapes container",
      "shape",
      "shape circle",
      "shape triangle",
      "shape square",
      "particles",
      "navbar",
      "nav container",
      "menutoggle",
      "home",
      "hero content",
      "rotator",
      "set",
      "active",
      "cta container",
      "features",
      "features container",
      "feature tabs",
      "tab item",
      "feature content",
      "performance",
      "security",
      "network",
      "analytics",
      "integration",
      "about",
      "about content",
      "about text",
      "about visual"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "neon gradients, luminous accents, futuristic rhythm",
      "dashboard grids, metrics cards, data-led proof",
      "product/menu cards, collection blocks, warm commerce flow"
    ],
    "colorSignals": [
      "#0a0a0a",
      "#ffffff",
      "#ff5e00",
      "#00b2ff",
      "rgba(255, 94, 0, 0.03)",
      "rgba(0, 178, 255, 0.03)",
      "rgba(0, 178, 255, 0.2)",
      "rgba(255, 94, 0, 0.15)",
      "rgba(0, 178, 255, 0.15)",
      "rgba(0, 0, 0, 0.8)",
      "rgba(10, 10, 10, 0.8)",
      "rgba(255, 94, 0, 0.1)",
      "rgba(10, 10, 10, 0.95)",
      "rgba(255, 94, 0, 0.2)",
      "rgba(255, 94, 0, 0.5)",
      "rgba(255, 94, 0, 0.8)",
      "rgba(255, 255, 255, 0.3)",
      "rgba(255, 255, 255, 0.2)"
    ],
    "animationSignals": [
      "float rotate",
      "gradient shift",
      "grid move",
      "float up",
      "glow",
      "charflyin",
      "charflyout",
      "subtitlefade",
      "fade in up",
      "glitch 1",
      "glitch 2",
      "fade in",
      "pulse",
      "hexagon rotate",
      "scan",
      "scanlines"
    ],
    "layoutSignals": [
      "grid bg",
      "shapes container",
      "shape",
      "shape circle",
      "shape triangle",
      "shape square",
      "gradient overlay",
      "particle",
      "scrolled",
      "nav container",
      "logo link",
      "logo svg",
      "logo text",
      "nav links",
      "active",
      "menu toggle",
      "hero",
      "hero content",
      "text rotator",
      "text set",
      "glitch text",
      "98rem",
      "94vw",
      "char",
      "out",
      "subtitle",
      "visible",
      "6rem",
      "cta container",
      "cta button",
      "cta primary",
      "cta secondary",
      "features",
      "section title"
    ],
    "keywordSignals": [
      "templatemo 596 electric xtra",
      "electric xtra cyberpunk landing page by templatemo",
      "grid bg",
      "gradient overlay",
      "scanlines",
      "shapes container",
      "shape",
      "shape circle",
      "shape triangle",
      "shape square",
      "particles",
      "navbar",
      "nav container",
      "menutoggle",
      "home",
      "hero content",
      "rotator",
      "set",
      "active",
      "cta container",
      "features",
      "features container",
      "feature tabs",
      "tab item",
      "feature content",
      "performance",
      "security",
      "network",
      "analytics",
      "integration",
      "about",
      "about content",
      "about text",
      "about visual",
      "about graphic",
      "about graphic alt",
      "hexagon",
      "contact",
      "future",
      "beyond",
      "limits",
      "electric",
      "dreams",
      "core",
      "lightning",
      "fast",
      "military",
      "grade"
    ],
    "assetSignals": [],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_610_aurum_gold",
    "title": "Aurum Gold - Premium Gold Investment & Trading",
    "likelyNiches": [
      "restaurant",
      "creative-services",
      "premium-business"
    ],
    "pageCount": 2,
    "htmlFiles": [
      "index.html",
      "templatemo.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "pricing/plans",
      "testimonials",
      "contact/lead form",
      "dashboard/data cards"
    ],
    "sectionPatterns": [
      "navbar",
      "nav inner",
      "nav cta",
      "mobilemenuoverlay",
      "mobilemenu",
      "mobile menu cta",
      "hero",
      "hero grid",
      "hero content",
      "hero badge",
      "hero actions",
      "hero stats",
      "stat item",
      "stat value",
      "stat label",
      "hero visual",
      "price card",
      "price header",
      "price main",
      "price value",
      "price metals",
      "metal item",
      "metal name",
      "metal price",
      "metal change",
      "own",
      "services",
      "section header",
      "section label",
      "services grid",
      "service card",
      "service icon"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "gold accents, luxury spacing, premium cards",
      "portfolio gallery, editorial images, case-study rhythm",
      "product/menu cards, collection blocks, warm commerce flow",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#b8860b",
      "#d4a84b",
      "#8b6914",
      "#c9a227",
      "#0f0e0c",
      "#1a1815",
      "#252119",
      "#f5f0e8",
      "#a69f94",
      "#6b6560",
      "#2a2622",
      "#4a7c59",
      "#8b3a3a",
      "#1f1d1a",
      "#151412",
      "rgba(15, 14, 12, 0.95)",
      "rgba(0, 0, 0, 0.7)",
      "rgba(184, 134, 11, 0.3)"
    ],
    "animationSignals": [
      "pulse",
      "fadeinup"
    ],
    "layoutSignals": [
      "nav",
      "scrolled",
      "nav inner",
      "logo",
      "nav links",
      "active",
      "nav cta",
      "mobile menu",
      "open",
      "mobile menu overlay",
      "mobile menu close",
      "mobile nav links",
      "mobile menu cta",
      "btn",
      "btn outline",
      "btn primary",
      "mobile menu btn",
      "menu open",
      "hero",
      "hero grid",
      "hero content",
      "hero badge",
      "dot",
      "hero title",
      "gold",
      "hero desc",
      "hero actions",
      "hero stats",
      "stat item",
      "stat value",
      "stat label",
      "hero visual",
      "price card",
      "price header"
    ],
    "keywordSignals": [
      "templatemo 610 aurum gold",
      "aurum gold premium gold investment trading",
      "navbar",
      "nav inner",
      "nav cta",
      "mobilemenuoverlay",
      "mobilemenu",
      "mobile menu cta",
      "hero",
      "hero grid",
      "hero content",
      "hero badge",
      "hero actions",
      "hero stats",
      "stat item",
      "stat value",
      "stat label",
      "hero visual",
      "price card",
      "price header",
      "price main",
      "price value",
      "price metals",
      "metal item",
      "metal name",
      "metal price",
      "metal change",
      "own",
      "services",
      "section header",
      "section label",
      "services grid",
      "service card",
      "service icon",
      "why gold",
      "why grid",
      "why content",
      "why text",
      "invest",
      "gold",
      "secure",
      "future",
      "complete",
      "investment",
      "solutions",
      "bullion",
      "sell",
      "storage"
    ],
    "assetSignals": [
      "tm gold",
      "tm silver"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_609_crypto_vault",
    "title": "Dashboard - CryptoVault",
    "likelyNiches": [
      "restaurant",
      "saas-tech",
      "creative-services"
    ],
    "pageCount": 6,
    "htmlFiles": [
      "index.html",
      "login.html",
      "markets.html",
      "settings.html",
      "templatemo.html",
      "wallet.html"
    ],
    "componentSignals": [
      "features/services",
      "portfolio/gallery",
      "contact/lead form",
      "dashboard/data cards",
      "interactive sections"
    ],
    "sectionPatterns": [
      "hamburger",
      "sidebaroverlay",
      "ashboard",
      "sidebar",
      "logo",
      "logo icon",
      "nav section",
      "nav label",
      "sidebar footer",
      "theme toggle",
      "theme toggle label",
      "themeswitch",
      "main content",
      "header",
      "header left",
      "header right",
      "header search",
      "user menu",
      "user avatar",
      "user info",
      "content wrapper",
      "content left",
      "charts grid",
      "chart card",
      "card header",
      "chart tabs",
      "chart container",
      "chart labels",
      "trading pair",
      "candlestick chart",
      "bottom row",
      "onut chart container"
    ],
    "visualSignals": [
      "dark premium surface, strong contrast, cinematic mood",
      "dashboard grids, metrics cards, data-led proof",
      "portfolio gallery, editorial images, case-study rhythm",
      "product/menu cards, collection blocks, warm commerce flow",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#1c1c1e",
      "#f7931a",
      "#627eea",
      "#26a17b",
      "#b87333",
      "#fff",
      "rgba(28, 28, 30, 0.2)",
      "rgba(184, 115, 51, 0.15)",
      "rgba(107, 142, 107, 0.2)",
      "rgba(194, 120, 120, 0.2)",
      "rgba(184, 115, 51, 0.2)",
      "#c9a878",
      "rgba(255,255,255,0.1)",
      "rgba(0,0,0,0.1)",
      "rgba(184, 115, 51, 0.3)",
      "radial-gradient",
      "#c77b15",
      "#4a5fc1",
      "#1a7a5c",
      "#9945ff",
      "#14f195",
      "#c27878",
      "#6b8e6b",
      "#e2761b"
    ],
    "animationSignals": [
      "float"
    ],
    "layoutSignals": [
      "header",
      "header subtitle",
      "header right",
      "header search",
      "notification btn",
      "notification badge",
      "user menu",
      "user avatar",
      "user info",
      "user name",
      "user role",
      "content wrapper",
      "content left",
      "charts grid",
      "content right",
      "stat card",
      "primary",
      "stat label",
      "stat value",
      "stat change",
      "stat icon",
      "stat content",
      "positive",
      "negative",
      "chart card",
      "chart tabs",
      "chart tab",
      "active",
      "chart container",
      "line chart",
      "bar chart",
      "chart labels",
      "trading pair",
      "pair price"
    ],
    "keywordSignals": [
      "templatemo 609 crypto vault",
      "dashboard cryptovault",
      "hamburger",
      "sidebaroverlay",
      "ashboard",
      "sidebar",
      "logo",
      "logo icon",
      "nav section",
      "nav label",
      "sidebar footer",
      "theme toggle",
      "theme toggle label",
      "themeswitch",
      "main content",
      "header",
      "header left",
      "header right",
      "header search",
      "user menu",
      "user avatar",
      "user info",
      "content wrapper",
      "content left",
      "charts grid",
      "chart card",
      "card header",
      "chart tabs",
      "chart container",
      "chart labels",
      "trading pair",
      "candlestick chart",
      "bottom row",
      "onut chart container",
      "onut legend",
      "legend item",
      "gauge container",
      "gauge value",
      "dashboard",
      "portfolio",
      "overview",
      "asset",
      "performance",
      "allocation",
      "health",
      "risk",
      "level",
      "recent"
    ],
    "assetSignals": [],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_613_frost_bakery",
    "title": "Frost — Cool Treats for Warm Hearts",
    "likelyNiches": [
      "restaurant",
      "education-training"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "process/timeline"
    ],
    "sectionPatterns": [
      "hamburger lines",
      "sidebaroverlay",
      "sidebar",
      "sidebar brand",
      "sidebar logo",
      "sidebar tagline",
      "sidebar nav",
      "sidebar footer",
      "sidebar hours",
      "main",
      "hero",
      "hero content",
      "hero badge",
      "reveal",
      "hero actions",
      "reveal delay 3",
      "hero deco",
      "scoop",
      "scoop strawberry",
      "scoop highlight",
      "scoop mint",
      "scoop vanilla",
      "flavors",
      "section header",
      "marquee",
      "marquee track",
      "flavor card",
      "flavor card swatch",
      "flavor card info",
      "flavor card tag",
      "marquee track reverse",
      "builder"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "dark premium surface, strong contrast, cinematic mood",
      "product/menu cards, collection blocks, warm commerce flow"
    ],
    "colorSignals": [
      "#e07a5f",
      "#f4f1de",
      "#3d405b",
      "#81b29a",
      "#f0a58e",
      "#c4603f",
      "#e8e3c8",
      "#575a78",
      "#a8cfba",
      "#5f8e73",
      "#fff",
      "#f4a4b8",
      "#fff5e0",
      "#fce4b8",
      "#e6c68a",
      "#e07a8a",
      "#d4627a",
      "#e09030"
    ],
    "animationSignals": [
      "marquee scroll",
      "marquee scroll reverse",
      "seasonfadein"
    ],
    "layoutSignals": [
      "5vw",
      "sidebar",
      "sidebar brand",
      "sidebar logo",
      "sidebar tagline",
      "sidebar nav",
      "active",
      "nav icon",
      "sidebar footer",
      "sidebar hours",
      "hamburger",
      "hamburger lines",
      "sidebar overlay",
      "is visible",
      "main",
      "reveal",
      "reveal delay 1",
      "reveal delay 2",
      "reveal delay 3",
      "reveal delay 4",
      "hero",
      "hero content",
      "hero badge",
      "hero title",
      "8rem",
      "hero subtitle",
      "hero actions",
      "hero deco",
      "scoop",
      "scoop strawberry",
      "scoop mint",
      "scoop vanilla",
      "scoop highlight",
      "btn"
    ],
    "keywordSignals": [
      "templatemo 613 frost bakery",
      "frost cool treats for warm hearts",
      "frost cool treats for warm hearts handcrafted ice cream gelato and frozen desserts made with locally sourced ingredients",
      "hamburger lines",
      "sidebaroverlay",
      "sidebar",
      "sidebar brand",
      "sidebar logo",
      "sidebar tagline",
      "sidebar nav",
      "sidebar footer",
      "sidebar hours",
      "main",
      "hero",
      "hero content",
      "hero badge",
      "reveal",
      "hero actions",
      "reveal delay 3",
      "hero deco",
      "scoop",
      "scoop strawberry",
      "scoop highlight",
      "scoop mint",
      "scoop vanilla",
      "flavors",
      "section header",
      "marquee",
      "marquee track",
      "flavor card",
      "flavor card swatch",
      "flavor card info",
      "flavor card tag",
      "marquee track reverse",
      "builder",
      "builder layout",
      "builder steps",
      "builder step",
      "builder step num",
      "life",
      "short",
      "boring",
      "desserts",
      "pick",
      "perfect",
      "tahitian",
      "vanilla",
      "bean"
    ],
    "assetSignals": [
      "autumn collection",
      "spring collection",
      "summer collection",
      "the classic cart",
      "the grand parlor",
      "the mini scoop",
      "winter collection"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_614_quantix_saas",
    "title": "Quantix - AI-Powered Analytics",
    "likelyNiches": [
      "saas-tech",
      "premium-business"
    ],
    "pageCount": 2,
    "htmlFiles": [
      "index.html",
      "templates.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "pricing/plans",
      "contact/lead form",
      "dashboard/data cards",
      "interactive sections"
    ],
    "sectionPatterns": [
      "navbar",
      "nav actions",
      "hero",
      "hero inner",
      "hero content",
      "hero badge",
      "hero cta",
      "trusted row",
      "trusted logos",
      "hero mockup",
      "mockup window",
      "mockup toolbar",
      "mockup body",
      "mockup metric row",
      "mockup metric",
      "mm label",
      "mm value",
      "mm change",
      "mockup chart",
      "mockup chart label",
      "chart line",
      "features",
      "section header",
      "feature tabs",
      "feature panels",
      "feature panel",
      "active",
      "feature text",
      "feat icon",
      "feature visual",
      "fv toolbar",
      "fv body"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "neon gradients, luminous accents, futuristic rhythm",
      "dashboard grids, metrics cards, data-led proof",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#1e1e24",
      "#26262d",
      "#2e2e36",
      "#36363f",
      "#ff6b6b",
      "#ff9b9b",
      "#eeeef0",
      "#8a8b9e",
      "#55566a",
      "#22c55e",
      "#f59e0b",
      "#f43f5e",
      "#fff",
      "#ff8585",
      "#ffd4d4",
      "#28282f",
      "rgba(255, 107, 107, 0.35)",
      "rgba(255, 107, 107, 0.08)"
    ],
    "animationSignals": [
      "dotpulse",
      "panelin",
      "cursormove"
    ],
    "layoutSignals": [
      "mono",
      "navbar",
      "scrolled",
      "nav brand",
      "brand icon",
      "nav links",
      "nav mobile actions",
      "nav actions",
      "btn",
      "btn ghost",
      "btn primary",
      "btn secondary",
      "btn lg",
      "btn arrow",
      "nav toggle",
      "hero",
      "hero inner",
      "hero content",
      "hero badge",
      "badge dot",
      "gradient text",
      "hero desc",
      "hero cta",
      "trusted row",
      "trusted label",
      "trusted logos",
      "trusted logo",
      "t icon",
      "hero mockup",
      "mockup window",
      "mockup toolbar",
      "mockup dot",
      "mockup body",
      "mockup metric row"
    ],
    "keywordSignals": [
      "templatemo 614 quantix saas",
      "quantix ai powered analytics",
      "navbar",
      "nav actions",
      "hero",
      "hero inner",
      "hero content",
      "hero badge",
      "hero cta",
      "trusted row",
      "trusted logos",
      "hero mockup",
      "mockup window",
      "mockup toolbar",
      "mockup body",
      "mockup metric row",
      "mockup metric",
      "mm label",
      "mm value",
      "mm change",
      "mockup chart",
      "mockup chart label",
      "chart line",
      "features",
      "section header",
      "feature tabs",
      "feature panels",
      "feature panel",
      "active",
      "feature text",
      "feat icon",
      "feature visual",
      "fv toolbar",
      "fv body",
      "ash metrics",
      "ash metric",
      "m label",
      "m val",
      "analytics",
      "move",
      "needle",
      "everything",
      "need",
      "nothing",
      "real",
      "time",
      "dashboard",
      "funnel"
    ],
    "assetSignals": [],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_615_amber_folio",
    "title": "Amber Folio Dark Photography Portfolio by TemplateMo",
    "likelyNiches": [
      "restaurant",
      "saas-tech",
      "creative-services",
      "fashion-beauty",
      "premium-business"
    ],
    "pageCount": 2,
    "htmlFiles": [
      "index.html",
      "templatemo-showcase.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "contact/lead form",
      "dashboard/data cards"
    ],
    "sectionPatterns": [
      "loadingscreen",
      "loader",
      "header",
      "menutoggle",
      "home",
      "hero bg",
      "hero shapes",
      "floating accent",
      "accent 1",
      "accent 2",
      "accent 3",
      "hero content",
      "reveal",
      "portfolio",
      "section header",
      "coverflow wrapper",
      "coverflowcontainer",
      "coverflow item",
      "portfolio overlay",
      "portfolio category",
      "coverflow controls",
      "indicators",
      "indicator",
      "active",
      "about",
      "about container",
      "about image",
      "about content",
      "stats",
      "stat item",
      "stat number",
      "stat label"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "dark premium surface, strong contrast, cinematic mood",
      "gold accents, luxury spacing, premium cards",
      "dashboard grids, metrics cards, data-led proof",
      "portfolio gallery, editorial images, case-study rhythm",
      "product/menu cards, collection blocks, warm commerce flow",
      "SaaS hero, feature cards, product proof and pricing flow"
    ],
    "colorSignals": [
      "#0a0a0a",
      "#1a1a1a",
      "#f39c12",
      "#ffffff",
      "#a0a0a0",
      "#151515",
      "#0f0f0f",
      "rgba(10, 10, 10, 0.95)",
      "rgba(10, 10, 10, 0.98)",
      "rgba(255, 255, 255, 0.65)",
      "rgba(255, 255, 255, 0.85)",
      "rgba(255, 255, 255, 0.6)",
      "rgba(243, 156, 18, 0.15)",
      "rgba(255, 255, 255, 0.9)",
      "rgba(243, 156, 18, 0.08)",
      "rgba(243, 156, 18, 0.03)",
      "rgba(243, 156, 18, 0.2)",
      "rgba(243, 156, 18, 0.1)"
    ],
    "animationSignals": [
      "morphshape",
      "rotateshape",
      "float",
      "spin"
    ],
    "layoutSignals": [
      "scrolled",
      "logo",
      "nav menu",
      "active",
      "menu toggle",
      "hero section",
      "hero bg",
      "hero shapes",
      "floating accent",
      "accent 1",
      "accent 2",
      "accent 3",
      "hero content",
      "hero title",
      "5rem",
      "hero subtitle",
      "cta button",
      "portfolio section",
      "section header",
      "section title",
      "section subtitle",
      "coverflow wrapper",
      "coverflow container",
      "coverflow item",
      "portfolio image",
      "portfolio overlay",
      "portfolio category",
      "portfolio title",
      "portfolio description",
      "coverflow controls",
      "control btn",
      "playing",
      "indicators",
      "indicator"
    ],
    "keywordSignals": [
      "templatemo 615 amber folio",
      "amber folio dark photography portfolio by templatemo",
      "loadingscreen",
      "loader",
      "header",
      "menutoggle",
      "home",
      "hero bg",
      "hero shapes",
      "floating accent",
      "accent 1",
      "accent 2",
      "accent 3",
      "hero content",
      "reveal",
      "portfolio",
      "section header",
      "coverflow wrapper",
      "coverflowcontainer",
      "coverflow item",
      "portfolio overlay",
      "portfolio category",
      "coverflow controls",
      "indicators",
      "indicator",
      "active",
      "about",
      "about container",
      "about image",
      "about content",
      "stats",
      "stat item",
      "stat number",
      "stat label",
      "services",
      "services container",
      "services grid",
      "service card",
      "capturing",
      "moments",
      "featured",
      "work",
      "human",
      "stories",
      "nature",
      "canvas",
      "urban",
      "life"
    ],
    "assetSignals": [
      "templatemo about artist",
      "templatemo amber folio"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_617_pixel_forge",
    "title": "PixelForge AI - Create Stunning Images from Text",
    "likelyNiches": [
      "restaurant",
      "creative-services",
      "fashion-beauty",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "portfolio/gallery",
      "pricing/plans",
      "dashboard/data cards",
      "interactive sections"
    ],
    "sectionPatterns": [
      "ambient glow",
      "glow 1",
      "glow 2",
      "glow 3",
      "nav inner",
      "logo",
      "mobilemenu",
      "hero",
      "hero inner",
      "hero content",
      "hero badge",
      "hero stats",
      "stat",
      "stat value",
      "stat label",
      "hero demo",
      "floating badge",
      "badge 1",
      "badge 2",
      "emo container",
      "emo header",
      "emo dot",
      "prompt area",
      "prompt label",
      "emo controls",
      "control group",
      "aspect ratios",
      "loader",
      "output area",
      "outputplaceholder",
      "imageactions",
      "gallery"
    ],
    "visualSignals": [
      "neon gradients, luminous accents, futuristic rhythm",
      "portfolio gallery, editorial images, case-study rhythm",
      "product/menu cards, collection blocks, warm commerce flow"
    ],
    "colorSignals": [
      "#00f0ff",
      "#ff2d6a",
      "#a855f7",
      "#7c3aed",
      "#0a0a0f",
      "#e8e8ed",
      "#6b6b7a",
      "#fbbf24",
      "#f472b6",
      "#a78bfa",
      "#fff",
      "#ff5f57",
      "#ffbd2e",
      "#28c840",
      "#1a1a22",
      "#4a4a52",
      "#5a5a62",
      "#6a6a72"
    ],
    "animationSignals": [
      "pulse",
      "spin",
      "fadein",
      "float"
    ],
    "layoutSignals": [
      "ambient glow",
      "glow 1",
      "glow 2",
      "glow 3",
      "nav inner",
      "logo",
      "nav links",
      "nav cta",
      "hero",
      "hero inner",
      "hero content",
      "hero badge",
      "5rem",
      "line 1",
      "line 2",
      "line 3",
      "hero desc",
      "hero stats",
      "stat",
      "stat value",
      "stat label",
      "hero demo",
      "demo container",
      "demo header",
      "demo dot",
      "prompt area",
      "prompt label",
      "prompt input",
      "demo controls",
      "control group",
      "control label",
      "control select",
      "aspect ratios",
      "aspect btn"
    ],
    "keywordSignals": [
      "templatemo 617 pixel forge",
      "pixelforge ai create stunning images from text",
      "ambient glow",
      "glow 1",
      "glow 2",
      "glow 3",
      "nav inner",
      "logo",
      "mobilemenu",
      "hero",
      "hero inner",
      "hero content",
      "hero badge",
      "hero stats",
      "stat",
      "stat value",
      "stat label",
      "hero demo",
      "floating badge",
      "badge 1",
      "badge 2",
      "emo container",
      "emo header",
      "emo dot",
      "prompt area",
      "prompt label",
      "emo controls",
      "control group",
      "aspect ratios",
      "loader",
      "output area",
      "outputplaceholder",
      "imageactions",
      "gallery",
      "gallery inner",
      "section header",
      "filter tabs",
      "bento gallery",
      "turn",
      "words",
      "into",
      "seconds",
      "community",
      "showcase",
      "built",
      "different",
      "lightning",
      "fast"
    ],
    "assetSignals": [
      "tm pixel forge"
    ],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_618_the_catalyst",
    "title": "The Catalyst - Ship Faster, Scale Infinitely",
    "likelyNiches": [
      "saas-tech",
      "premium-business"
    ],
    "pageCount": 1,
    "htmlFiles": [
      "index.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "pricing/plans",
      "contact/lead form",
      "dashboard/data cards",
      "interactive sections"
    ],
    "sectionPatterns": [
      "nav",
      "nav inner",
      "nav cta",
      "hero",
      "hero badge",
      "reveal",
      "hero actions",
      "hero dashboard",
      "ashboard frame",
      "ashboard toolbar",
      "ashboard dots",
      "ashboard toolbar tabs",
      "ashboard body",
      "ash stat card",
      "ash stat label",
      "ash stat value",
      "ash stat change",
      "ashboard table area",
      "ash table header",
      "ash table",
      "ash table row",
      "head",
      "ash cell",
      "ash cell name",
      "metrics",
      "metrics grid",
      "metric item",
      "metric number",
      "engine",
      "section header",
      "bento grid",
      "bento card"
    ],
    "visualSignals": [
      "dashboard grids, metrics cards, data-led proof"
    ],
    "colorSignals": [
      "#fafafa",
      "#f0f0f0",
      "#111111",
      "#666666",
      "#999999",
      "#d4ff00",
      "#c2eb00",
      "#e5e5e5",
      "#eeeeee",
      "#ffffff",
      "#22c55e",
      "#ef4444",
      "#dcfce7",
      "#166534",
      "#fef3c7",
      "#92400e",
      "#e8e8e8",
      "#e0e0e0"
    ],
    "animationSignals": [
      "pulse dot"
    ],
    "layoutSignals": [
      "btn acid",
      "btn ghost",
      "nav",
      "nav inner",
      "nav logo",
      "nav logo mark",
      "nav links",
      "nav cta",
      "nav toggle",
      "hero",
      "hero badge",
      "hero badge dot",
      "accent word",
      "hero sub",
      "8vw",
      "hero actions",
      "hero dashboard",
      "dashboard frame",
      "dashboard toolbar",
      "dashboard dots",
      "dashboard toolbar tabs",
      "active",
      "dashboard body",
      "dash stat card",
      "dash stat label",
      "dash stat value",
      "dash stat change",
      "down",
      "dashboard table area",
      "dash table header",
      "dash filter",
      "dash table",
      "dash table row",
      "head"
    ],
    "keywordSignals": [
      "templatemo 618 the catalyst",
      "the catalyst ship faster scale infinitely",
      "nav",
      "nav inner",
      "nav cta",
      "hero",
      "hero badge",
      "reveal",
      "hero actions",
      "hero dashboard",
      "ashboard frame",
      "ashboard toolbar",
      "ashboard dots",
      "ashboard toolbar tabs",
      "ashboard body",
      "ash stat card",
      "ash stat label",
      "ash stat value",
      "ash stat change",
      "ashboard table area",
      "ash table header",
      "ash table",
      "ash table row",
      "head",
      "ash cell",
      "ash cell name",
      "metrics",
      "metrics grid",
      "metric item",
      "metric number",
      "engine",
      "section header",
      "bento grid",
      "bento card",
      "bento card icon",
      "bento card visual",
      "mini bars",
      "mini bar",
      "analytics",
      "platform",
      "built",
      "speed",
      "everything",
      "data",
      "team",
      "actually",
      "needs",
      "real"
    ],
    "assetSignals": [],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  },
  {
    "sourceTemplate": "templatemo_619_axis_industrial",
    "title": "AXIS INDUSTRIAL — Engineered Without Compromise",
    "likelyNiches": [
      "saas-tech",
      "creative-services",
      "industrial",
      "premium-business"
    ],
    "pageCount": 3,
    "htmlFiles": [
      "index.html",
      "landing-page.html",
      "the-observer.html"
    ],
    "componentSignals": [
      "hero",
      "features/services",
      "process/timeline",
      "contact/lead form",
      "dashboard/data cards"
    ],
    "sectionPatterns": [
      "header",
      "header inner",
      "header left",
      "headernav",
      "header right",
      "header status",
      "utcclock",
      "hero",
      "hero grid",
      "hero grid dense",
      "hero label",
      "reveal",
      "hero bottom",
      "hero stats",
      "hero stat num",
      "hero stat label",
      "hero scroll cue",
      "specs",
      "section header",
      "section eyebrow",
      "bento grid",
      "bento card",
      "bento card wide",
      "bento card number",
      "bar chart",
      "bar chart col",
      "bento card visual",
      "bento card narrow",
      "bento card dark",
      "bento card stat",
      "bento card mid",
      "bento card safety"
    ],
    "visualSignals": [
      "parallax depth, layered scroll, immersive sections",
      "dark premium surface, strong contrast, cinematic mood",
      "dashboard grids, metrics cards, data-led proof",
      "industrial grid, robust cards, process and capability blocks"
    ],
    "colorSignals": [
      "#ffffff",
      "#000000",
      "#ff3e00",
      "#888888",
      "#f5f5f0",
      "#08080a",
      "#00ff66",
      "#ffaa00",
      "rgba(0,0,0,0.10)",
      "rgba(255,255,255,0.12)",
      "rgba(255,255,255,0.10)",
      "rgba(255,255,255,0.5)",
      "rgba(255,255,255,0.06)",
      "rgba(0,0,0,0.045)",
      "rgba(0,0,0,0.06)",
      "rgba(255,255,255,0.2)",
      "rgba(255,255,255,0.35)",
      "linear-gradient",
      "rgba(255,255,255,0.15)",
      "rgba(255,255,255,0.25)",
      "rgba(0,255,102,0.3)",
      "rgba(255,170,0,0.3)",
      "rgba(255,62,0,0.3)",
      "#f0f0eb"
    ],
    "animationSignals": [
      "pulse",
      "herorotate",
      "scrollpulse",
      "tickerscroll",
      "sweeparm",
      "wavebar",
      "logscrollv"
    ],
    "layoutSignals": [
      "4rem",
      "6rem",
      "1rem",
      "6vw",
      "9rem",
      "1vw",
      "78rem",
      "9vw",
      "5vw",
      "font display",
      "grid 12",
      "accent",
      "tag",
      "tag filled",
      "tag safety",
      "tag ghost",
      "btn",
      "btn primary",
      "btn ghost",
      "header",
      "header inner",
      "header left",
      "header logo",
      "header logo mark",
      "header sep",
      "header product",
      "header nav",
      "active",
      "header right",
      "header status",
      "header status dot",
      "header clock",
      "header burger",
      "hero"
    ],
    "keywordSignals": [
      "templatemo 619 axis industrial",
      "axis industrial engineered without compromise",
      "axis industrial delivers precision engineered solutions for heavy industry built to endure designed to perform",
      "header",
      "header inner",
      "header left",
      "headernav",
      "header right",
      "header status",
      "utcclock",
      "hero",
      "hero grid",
      "hero grid dense",
      "hero label",
      "reveal",
      "hero bottom",
      "hero stats",
      "hero stat num",
      "hero stat label",
      "hero scroll cue",
      "specs",
      "section header",
      "section eyebrow",
      "bento grid",
      "bento card",
      "bento card wide",
      "bento card number",
      "bar chart",
      "bar chart col",
      "bento card visual",
      "bento card narrow",
      "bento card dark",
      "bento card stat",
      "bento card mid",
      "bento card safety",
      "bento card tall",
      "bento card text",
      "ticker",
      "ticker track",
      "built",
      "brutal",
      "what",
      "bring",
      "site",
      "structural",
      "analysis",
      "heavy",
      "fabrication"
    ],
    "assetSignals": [],
    "licenseNote": "Use as internal inspiration only. Do not copy HTML, CSS, texts, images or template names into generated client sites."
  }
] as const satisfies readonly TemplateMoInspiration[];
