-- Pixelrises V2 real data layer.
-- Stores generated projects, safe generation metadata, versions, agents, games,
-- analytics events, usage logs, and integration statuses.
-- Never store AI gateway keys or provider secrets in these tables.

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('site', 'agent', 'game')),
  name text not null,
  status text not null default 'generated' check (status in ('draft', 'planned', 'generated', 'improved', 'published')),
  score integer not null default 0 check (score >= 0 and score <= 100),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.generations (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'vercel-gateway',
  model text not null default 'unknown',
  mode text not null default 'build' check (mode in ('plan', 'build', 'improve')),
  input jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  quality_score integer not null default 0 check (quality_score >= 0 and quality_score <= 100),
  status text not null default 'success' check (status in ('success', 'failed', 'fallback')),
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.project_versions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  version_number integer not null,
  data jsonb not null default '{}'::jsonb,
  change_summary text not null default 'Generated by Pixelrises V2',
  created_at timestamptz not null default now(),
  unique (project_id, version_number)
);

create table if not exists public.agents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete cascade,
  name text not null,
  role text not null,
  goal text not null,
  config jsonb not null default '{}'::jsonb,
  permissions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.projects(id) on delete cascade,
  platform text not null,
  game_type text not null,
  title text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  project_id uuid references public.projects(id) on delete cascade,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_usage_logs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  project_id uuid references public.projects(id) on delete set null,
  generation_id uuid references public.generations(id) on delete set null,
  provider text not null,
  model text not null,
  task_type text not null,
  estimated_tokens integer not null default 0,
  estimated_cost numeric(12, 6) not null default 0,
  duration_ms integer not null default 0,
  success boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.integration_statuses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  integration_key text not null,
  status text not null default 'configure' check (status in ('connected', 'available', 'development', 'soon', 'requested', 'beta', 'configure')),
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, integration_key)
);

alter table public.projects enable row level security;
alter table public.generations enable row level security;
alter table public.project_versions enable row level security;
alter table public.agents enable row level security;
alter table public.games enable row level security;
alter table public.analytics_events enable row level security;
alter table public.ai_usage_logs enable row level security;
alter table public.integration_statuses enable row level security;

create index if not exists projects_user_updated_idx on public.projects (user_id, updated_at desc);
create index if not exists projects_user_type_idx on public.projects (user_id, type);
create index if not exists generations_project_created_idx on public.generations (project_id, created_at desc);
create index if not exists generations_user_created_idx on public.generations (user_id, created_at desc);
create index if not exists project_versions_project_version_idx on public.project_versions (project_id, version_number desc);
create index if not exists agents_user_updated_idx on public.agents (user_id, updated_at desc);
create index if not exists games_user_updated_idx on public.games (user_id, updated_at desc);
create index if not exists analytics_events_project_created_idx on public.analytics_events (project_id, created_at desc);
create index if not exists ai_usage_logs_generation_idx on public.ai_usage_logs (generation_id);
create index if not exists integration_statuses_user_key_idx on public.integration_statuses (user_id, integration_key);

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'update_projects_updated_at') then
    create trigger update_projects_updated_at before update on public.projects for each row execute function public.update_updated_at_column();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'update_agents_updated_at') then
    create trigger update_agents_updated_at before update on public.agents for each row execute function public.update_updated_at_column();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'update_games_updated_at') then
    create trigger update_games_updated_at before update on public.games for each row execute function public.update_updated_at_column();
  end if;
  if not exists (select 1 from pg_trigger where tgname = 'update_integration_statuses_updated_at') then
    create trigger update_integration_statuses_updated_at before update on public.integration_statuses for each row execute function public.update_updated_at_column();
  end if;
end$$;

drop policy if exists "Users can read own v2 projects" on public.projects;
create policy "Users can read own v2 projects" on public.projects for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own v2 projects" on public.projects;
create policy "Users can insert own v2 projects" on public.projects for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update own v2 projects" on public.projects;
create policy "Users can update own v2 projects" on public.projects for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users can delete own v2 projects" on public.projects;
create policy "Users can delete own v2 projects" on public.projects for delete using (auth.uid() = user_id);

drop policy if exists "Users can read own v2 generations" on public.generations;
create policy "Users can read own v2 generations" on public.generations for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own v2 generations" on public.generations;
create policy "Users can insert own v2 generations" on public.generations for insert with check (auth.uid() = user_id);

drop policy if exists "Users can read own v2 project versions" on public.project_versions;
create policy "Users can read own v2 project versions" on public.project_versions for select using (
  exists (select 1 from public.projects p where p.id = project_versions.project_id and p.user_id = auth.uid())
);
drop policy if exists "Users can insert own v2 project versions" on public.project_versions;
create policy "Users can insert own v2 project versions" on public.project_versions for insert with check (
  exists (select 1 from public.projects p where p.id = project_versions.project_id and p.user_id = auth.uid())
);

drop policy if exists "Users can manage own v2 agents" on public.agents;
create policy "Users can manage own v2 agents" on public.agents for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can manage own v2 games" on public.games;
create policy "Users can manage own v2 games" on public.games for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can read own v2 analytics" on public.analytics_events;
create policy "Users can read own v2 analytics" on public.analytics_events for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own v2 analytics" on public.analytics_events;
create policy "Users can insert own v2 analytics" on public.analytics_events for insert with check (auth.uid() = user_id or user_id is null);

drop policy if exists "Users can read own v2 usage logs" on public.ai_usage_logs;
create policy "Users can read own v2 usage logs" on public.ai_usage_logs for select using (auth.uid() = user_id);

drop policy if exists "Users can manage own v2 integration statuses" on public.integration_statuses;
create policy "Users can manage own v2 integration statuses" on public.integration_statuses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
