// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeLocalStorage } from '@/lib/browser-storage';
import { PUBLIC_ENV } from '@/lib/public-env';

export const isSupabaseConfigured =
  PUBLIC_ENV.supabaseUrl.length > 0 &&
  PUBLIC_ENV.supabasePublishableKey.length > 0;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  PUBLIC_ENV.supabaseUrl,
  PUBLIC_ENV.supabasePublishableKey,
  {
    auth: {
      storage: safeLocalStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
